import type { Metadata } from 'next';
import { PageShell } from '../components/SiteChrome';
import { FaqBlock, InfoHero } from '../components/InfoBlocks';
export const metadata:Metadata={title:'Responsible Play | Shree Win Game',description:'Use Shree Win responsibly with personal time and spending limits, risk awareness, session breaks, account safety and support guidance for adults.',alternates:{canonical:'/responsible-play'}};
const faqs:[string,string][]=[
 ['Is gaming a way to make income?','No. Gaming should be treated as paid entertainment, never as employment, investment or a way to solve financial problems.'],
 ['How can I set a personal limit?','Choose a fixed entertainment amount and session length before playing. Do not increase either limit to recover a loss.'],
 ['What are signs I should stop?','Stop if you feel pressure, hide activity, borrow money, chase losses, miss responsibilities or continue after gaming stops being enjoyable.'],
 ['Who should not use Shree Win?','Minors and anyone who does not meet the applicable age, location or legal requirements must not register or play.'],
 ['How can I secure my account?','Use a unique password, keep OTPs private, review transaction history and report unfamiliar access immediately.'],
];
export default function ResponsiblePage(){return <PageShell><main><InfoHero eyebrow="RESPONSIBLE PLAY" title="Keep every session" accent="within your personal limits." copy="Shree Win is entertainment for eligible adults. Set time and spending boundaries before playing and stop whenever it no longer feels balanced." current="Responsible Play" icon="⚖" primary={{label:'Use the checklist',href:'#details'}}/>
 <section className="content-section info-page" id="details"><div className="section-title centered"><span>PLAY WITH CONTROL</span><h2>Six habits for a balanced session.</h2></div><div className="info-card-grid three"><article><i>₹</i><h2>Set a budget</h2><p>Use only discretionary money you can afford to lose completely.</p></article><article><i>⏱</i><h2>Set a time limit</h2><p>Choose the session length before starting and take regular breaks.</p></article><article><i>↘</i><h2>Never chase losses</h2><p>A previous result does not make the next result more predictable.</p></article><article><i>🧠</i><h2>Check your mood</h2><p>Do not play when stressed, angry, pressured or impaired.</p></article><article><i>🔒</i><h2>Protect the account</h2><p>Keep login, OTP and payment credentials private.</p></article><article><i>✋</i><h2>Know when to stop</h2><p>Pause when play affects sleep, work, relationships or finances.</p></article></div></section>
 <section className="risk-band"><div><span>FINANCIAL RISK WARNING</span><h2>There is no guaranteed result, return or recovery strategy.</h2></div><ul><li>Never borrow money to deposit or continue playing.</li><li>Do not treat promotions as guaranteed value.</li><li>Do not use household or emergency funds.</li><li>Seek trusted personal or professional help if control becomes difficult.</li></ul></section>
 <section className="content-section two-column-copy"><div><span className="kicker dark"><i/>SELF-CHECK</span><h2>Pause and review your relationship with play.</h2></div><div><h3>Can you stop at the limit you set?</h3><p>If you repeatedly extend time or spending, take a longer break and use any account controls available in the live product.</p><h3>Are you chasing a previous result?</h3><p>Every new round should be treated independently. Past results do not guarantee what comes next.</p><h3>Is gaming affecting daily life?</h3><p>If gaming is interfering with responsibilities, sleep, finances or relationships, stop and ask a trusted person or qualified service for support.</p></div></section>
 <FaqBlock title="Responsible play FAQ" items={faqs}/><section className="page-cta"><span>KEEP CONTROL</span><h2>Your limit is more important than any game or promotion.</h2><a className="primary-button" href="/games">Return to game information →</a></section></main></PageShell>}
