import type { Metadata } from 'next';
import { PageShell } from '../components/SiteChrome';
import { FaqBlock, InfoHero, ProductNotice } from '../components/InfoBlocks';

export const metadata:Metadata={title:'Shree Win Wallet | Deposit, Bank Account & Withdrawal',description:'Learn how the Shree Win wallet handles deposits, payment methods, bank-account details, withdrawals, transaction records and account-safety checks.',alternates:{canonical:'/wallet'}};
const faqs:[string,string][]=[
 ['How do I add balance to Shree Win?','Log in, open Wallet, choose Deposit or Add Balance, select an available payment method and follow the on-screen confirmation.'],
 ['Which payment methods are supported?','Only methods shown in the live Wallet are currently supported. Availability can vary by account and location.'],
 ['How do I add a bank account?','Open the withdrawal or payment settings, enter the account-holder name and requested bank details exactly, then complete any verification shown.'],
 ['What is the minimum deposit or withdrawal?','Current limits and any fees are displayed in the live Wallet before confirmation; this website does not hard-code changing values.'],
 ['What should I do if a transaction is pending?','Keep the transaction ID and payment receipt, avoid repeating the payment immediately, and contact support through the in-product channel.'],
];
export default function WalletPage(){return <PageShell active="account"><main><InfoHero eyebrow="SHREE WIN WALLET" title="Payments and records" accent="in one secure journey." copy="Review available deposit methods, bank-account details, withdrawal requirements and transaction status from your Shree Win Wallet." current="Wallet" icon="₹" primary={{label:'View wallet flow',href:'#details'}}/>
  <section className="content-section info-page" id="details"><div className="section-heading"><div className="section-title"><span>WALLET ACTIONS</span><h2>Know what happens at every step.</h2></div><p>Amounts, limits, payment methods, fees and processing times must be confirmed in the live Wallet before you authorise a transaction.</p></div><div className="info-card-grid three"><article><i>＋</i><h2>Add balance</h2><p>Open Wallet, choose an available method, enter the amount and verify the recipient details before payment.</p></article><article><i>🏦</i><h2>Add bank account</h2><p>Enter the account holder name, bank details and IFSC exactly as requested, then complete verification.</p></article><article><i>↗</i><h2>Request withdrawal</h2><p>Choose the verified destination, review the current limit and fee information, and save the request record.</p></article></div></section>
  <section className="content-section process-section"><div className="section-title"><span>PAYMENT CHECKLIST</span><h2>Before you confirm any transaction</h2></div><div className="check-grid"><p><b>01</b>Make sure you are signed in to the correct account.</p><p><b>02</b>Use only payment options shown inside Shree Win Wallet.</p><p><b>03</b>Verify the amount, recipient and payment reference.</p><p><b>04</b>Never share an OTP, password or screen-control access.</p><p><b>05</b>Keep a receipt and transaction ID until completion.</p><p><b>06</b>Use in-product Support if the status does not update.</p></div><ProductNotice>The wallet screen is the source of truth for supported methods, minimum and maximum values, fees, processing time, verification and eligibility.</ProductNotice></section>
  <section className="risk-band"><div><span>PROTECT YOUR ACCOUNT</span><h2>Shree Win support should never ask for your password or OTP.</h2></div><ul><li>Do not pay to a personal number shared in a message.</li><li>Do not install remote-access apps for payment help.</li><li>Match bank-account details with the verified account holder.</li><li>Report an unfamiliar transaction immediately.</li></ul></section>
  <FaqBlock title="Wallet and payment FAQ" items={faqs}/><section className="page-cta purple"><span>NEED HELP?</span><h2>Keep your transaction reference ready when contacting support.</h2><a className="primary-button" href="/support">Open Support →</a></section></main></PageShell>}
