import type { Metadata } from 'next';
import { PageShell } from '../components/SiteChrome';
import { FaqBlock, InfoHero, ProductNotice } from '../components/InfoBlocks';
export const metadata:Metadata={title:'Shree Win App Download | Android APK Installation',description:'Get Shree Win app download information, Android APK installation steps, current-version checks, update guidance and mobile security tips.',alternates:{canonical:'/download'}};
const faqs:[string,string][]=[
 ['How do I download the Shree Win app?','Use the download button on the verified Shree Win product page when the current Android release is connected. Avoid APK links from unknown websites or messages.'],
 ['What is the latest Shree Win version?','The current version number should appear on the download screen and inside App information. Check that value before installing or updating.'],
 ['Why does Android ask for install permission?','Android may request permission to install an APK from the browser or file manager. Enable it only for the trusted source and turn it off after installation.'],
 ['Is the app on the Play Store?','Use only store links displayed by the verified Shree Win product. We do not claim a listing until it is confirmed.'],
 ['How do I update the app?','Compare your installed version with the current download screen, save your login details securely and follow the official update prompt.'],
];
export default function DownloadPage(){return <PageShell><main><InfoHero eyebrow="SHREE WIN APP" title="A mobile-first lobby" accent="for Android devices." copy="Review the current release, permissions and installation source before downloading the Shree Win Android app." current="Download App" icon="↓" primary={{label:'Installation steps',href:'#details'}}/>
 <section className="content-section app-facts" id="details"><div><span className="kicker dark"><i/>CURRENT APP INFORMATION</span><h2>Check the release before installing.</h2><p>Version, file size and compatibility can change with every release. The connected download screen—not an old article—should display the current values.</p></div><dl><div><dt>App name</dt><dd>Shree Win</dd></div><div><dt>Platform</dt><dd>Android app / mobile web</dd></div><div><dt>Current version</dt><dd>Shown on download screen</dd></div><div><dt>File size</dt><dd>Shown before download</dd></div><div><dt>Game categories</dt><dd>Lottery, mini games, arcade and casino-style</dd></div><div><dt>Download source</dt><dd>Verified Shree Win product page</dd></div></dl></section>
 <section className="content-section process-section"><div className="section-title"><span>ANDROID INSTALLATION</span><h2>Install the Shree Win APK carefully.</h2></div><div className="step-list horizontal"><article><b>01</b><div><h2>Open Download App</h2><p>Confirm the domain, release version and device compatibility.</p></div></article><article><b>02</b><div><h2>Download the APK</h2><p>Save the file from the verified Shree Win source only.</p></div></article><article><b>03</b><div><h2>Allow this source</h2><p>If Android asks, temporarily allow installation for that browser or file manager.</p></div></article><article><b>04</b><div><h2>Install and verify</h2><p>Open the downloaded file, review permissions and complete installation.</p></div></article></div><ProductNotice>The final APK link is intentionally a placeholder until a verified product file and checksum are provided. This prevents visitors from receiving an unverified download.</ProductNotice></section>
 <section className="risk-band"><div><span>APK SAFETY</span><h2>Never install a Shree Win file sent by an unknown person.</h2></div><ul><li>Match the version with the connected product download page.</li><li>Review requested permissions before installation.</li><li>Do not disable device protection permanently.</li><li>Delete unexpected duplicate APK files.</li></ul></section>
 <FaqBlock title="Shree Win app download FAQ" items={faqs}/><section className="page-cta"><span>AFTER INSTALLATION</span><h2>Register a new account or return through Shree Win Login.</h2><a className="primary-button" href="/login">Go to Login →</a></section></main></PageShell>}
