export type GuideSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type GuideContent = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  intro: string;
  sections: GuideSection[];
  related: { label: string; href: string }[];
  cta?: 'login' | 'register' | 'visit';
};

export const guidePages: Record<string, GuideContent> = {
  'shree-win-apk': {
    slug: 'shree-win-apk', title: 'Shree Win APK: App Features & Mobile Guide', description: 'Understand Shree Win APK, its mobile interface, visible game categories, app navigation and safe Android installation basics.', eyebrow: 'Mobile app overview', h1: 'Shree Win APK: Mobile App Features & Interface Guide', intro: 'A factual guide to the currently observed Shree Win mobile experience, the meaning of an APK and the information to review before installing an Android app.', cta: 'visit',
    sections: [
      { heading: 'What the Shree Win APK name means', paragraphs: ['APK stands for Android Package Kit, the file format Android uses to distribute and install applications. When people search for Shree Win APK, they are usually trying to locate the mobile application, understand the installation process or see what the interface contains before opening an account.', 'An APK name alone does not prove that a file is genuine or safe. The responsible approach is to verify the domain, confirm that the platform actually offers the file, review Android warnings and inspect permissions. ShreeWinAPK.net does not host a file while version, size and source details remain unverified.'] },
      { heading: 'The currently visible interface', paragraphs: ['The supplied Shree Win interface is organised around five main categories: Lobby, Lottery, Popular, Mini Game and Casino. The Lottery area currently shows TRX WinGo and MotoRace. At the bottom, users can move between Home, Activity, Promotion and Account.', 'Login and Register actions are available in the platform interface. This informational site keeps those actions external and never asks users to submit Shree Win credentials, verification codes or payment details.'], bullets: ['Lobby for the broad game view','Lottery with TRX WinGo and MotoRace','Popular and Mini Game category access','Casino category access','Home, Activity, Promotion and Account navigation'] },
      { heading: 'Information that still needs administrator verification', paragraphs: ['APK version, file size, direct file URL and release date can change. They are therefore stored as empty configuration values rather than guessed or copied from an unknown page. When verified details are supplied, they can be updated centrally without rewriting every guide.', 'Game artwork and interface structure may also change over time. Screenshots on this site are presented as observed interface previews, not as permanent guarantees of availability.'] },
    ], related: [{label:'APK download guide',href:'/shree-win-download'},{label:'Games overview',href:'/shree-win-games'},{label:'Login guide',href:'/shree-win-login'}],
  },
  'shree-win-download': {
    slug: 'shree-win-download', title: 'Shree Win Download: Safe APK Installation Guide', description: 'Follow a careful Shree Win APK download and Android installation checklist without using modified files or sharing credentials.', eyebrow: 'Android safety guide', h1: 'Shree Win APK Download & Installation Guide', intro: 'A step-by-step Android guide focused on source checks, device security and responsible credential handling. No unverified APK is hosted on this website.', cta: 'visit',
    sections: [
      { heading: 'Before downloading an Android APK', paragraphs: ['Confirm that you deliberately opened the intended source and read the address carefully. Similar-looking domain names can be used to distribute unrelated or modified files. Avoid packages advertised as cracked, modded, unlimited or guaranteed to produce a result.', 'Keep Google Play Protect or equivalent Android security features enabled. A request to disable protection permanently, install additional unknown apps or grant unrelated permissions is a reason to stop and investigate.'], bullets: ['Check the exact domain','Avoid files received in unsolicited messages','Do not install modified or cracked packages','Keep Android protection enabled','Back up important device data'] },
      { heading: 'Generic installation steps', paragraphs: ['If the platform provides an APK, download the file and review the browser or file-manager prompt. Android may request temporary permission to install from that source. Grant only the minimum permission needed for the intended installation and switch it off again afterwards if appropriate.', 'Review the application name and permissions before confirming. After installation, open the app directly from Android rather than through a third-party installer. Enter account credentials only in the intended platform interface and never disclose passwords, OTPs, UPI PINs or financial PINs to another person.'] },
      { heading: 'Why no direct file appears here yet', paragraphs: ['The administrator has not supplied a verified APK URL, version number, file size or checksum. Publishing a download button without those facts could mislead visitors or expose them to an unrelated file. The site therefore provides a Visit Shree Win action while keeping all unknown values blank.', 'When verified release data becomes available, the central configuration can display it consistently across the download, APK and update pages.'] },
    ], related: [{label:'What is Shree Win APK?',href:'/shree-win-apk'},{label:'Login guide',href:'/shree-win-login'},{label:'Privacy policy',href:'/privacy-policy'}],
  },
  'shree-win-login': {
    slug: 'shree-win-login', title: 'Shree Win Login Guide: Safe Account Access', description: 'Learn the Shree Win login flow, phone and email access basics, password safety and account troubleshooting without sharing credentials.', eyebrow: 'Account access', h1: 'Shree Win Login Guide', intro: 'Use this guide to understand the login journey before leaving ShreeWinAPK.net. Your username, password, OTP and financial details should never be entered on this informational website.', cta: 'login',
    sections: [
      { heading: 'How the observed login screen is organised', paragraphs: ['The supplied interface shows separate Phone Number and Email access options. A phone login area includes a country-code selector and password field, while the email view uses an email field and password. A remember-password control and forgot-password link are also visible.', 'Interface labels can change. Always verify that you are on the expected platform domain before entering credentials. ShreeWinAPK.net links outward for account access and does not embed or imitate the working login form.'] },
      { heading: 'Four-step login process', paragraphs: ['Open the configured Shree Win access page, choose the account method connected to your profile, enter the required credentials and review them before continuing to the dashboard. If the platform requests verification, complete it only within the intended service.', 'Never forward an OTP or password to a person claiming to be support. A legitimate verification flow should not require you to reveal a one-time code in chat, by phone or through an unrelated form.'], bullets: ['Open the account-access page','Choose phone or email when available','Enter only your own account credentials','Verify the domain and information','Continue to the account dashboard'] },
      { heading: 'Password and recovery safety', paragraphs: ['Use a unique password that is not reused for email, banking or other gaming accounts. If you forget it, use the platform’s own recovery option. The observed reset screen includes phone-based recovery, a new password, confirmation and verification-code step.', 'If a reset request was not initiated by you, do not share the code. Contact the platform through a verified support route and review account activity when that option exists.'] },
    ], related: [{label:'Registration guide',href:'/shree-win-register'},{label:'APK guide',href:'/shree-win-apk'},{label:'Contact information',href:'/contact'}],
  },
  'shree-win-register': {
    slug: 'shree-win-register', title: 'Shree Win Register Guide: Account Setup Steps', description: 'Review Shree Win registration by phone or email, verification, password safety and privacy guidance before creating an account.', eyebrow: 'New account guide', h1: 'How to Register on Shree Win', intro: 'A neutral walkthrough of the observed account-creation interface. This guide does not promise a bonus, referral reward, approval or access in any location.', cta: 'register',
    sections: [
      { heading: 'Phone and email registration views', paragraphs: ['The supplied registration interface includes phone and email tabs. The phone view displays a country code, phone-number field, password confirmation and invitation-code field. The email view displays email, password, confirmation and invitation-code fields. The exact required fields should be verified on the current platform.', 'An invitation code appearing in the interface does not prove that a reward is available. Eligibility, referral relationships and promotion terms can change, so no amount or benefit is stated on this website.'] },
      { heading: 'A careful registration sequence', paragraphs: ['Open the configured registration destination, choose the available method, provide only the information requested by the platform, create a unique password and complete any verification. Read the privacy agreement and account terms before submitting.', 'Registration may be restricted by age, location or local law. Creating an account does not remove the user’s responsibility to understand eligibility or financial risk.'], bullets: ['Check the destination domain','Use information that belongs to you','Create a unique password','Read the applicable privacy terms','Complete only the platform’s verification','Keep OTPs and passwords private'] },
      { heading: 'What this website does not collect', paragraphs: ['ShreeWinAPK.net does not provide a Shree Win registration form. It does not request phone numbers, platform passwords, OTPs, withdrawal passwords, UPI PINs, banking PINs, card details or referral credentials.', 'The external Register action opens in a new tab with safe link attributes. Visitors can review this guide without providing personal information.'] },
    ], related: [{label:'Login guide',href:'/shree-win-login'},{label:'Privacy policy',href:'/privacy-policy'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  'shree-win-games': {
    slug: 'shree-win-games', title: 'ShreeWin Games: WinGo, K3, 5D, Aviator & More', description: 'Explore ShreeWin games and categories including WinGo, K3, 5D, Aviator, TRX WinGo, MotoRace, Lottery, Mini Game and Casino.', eyebrow: 'Games directory', h1: 'ShreeWin Games and Categories', intro: 'A simple guide to the game names and category tabs shown in the supplied ShreeWin app information. Always check the live rules before you play.',
    sections: [
      { heading: 'Five visible categories', paragraphs: ['The main navigation row currently shows Lobby, Lottery, Popular, Mini Game and Casino. Lobby is the broad starting view, while the other labels separate platform content into recognisable groups.', 'Category availability can change. The names describe where content is organised, not a claim about fairness, legality, returns or availability in every location.'], bullets: ['Lobby','Lottery','Popular','Mini Game','Casino'] },
      { heading: 'Games shown in the supplied information', paragraphs: ['The supplied screens and administrator information show WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace. WinGo is presented as a colour and number game. K3 and 5D are number-style entries. Aviator is a crash-style entry, while TRX WinGo and MotoRace appear in the Lottery area.', 'This site does not provide a winning prediction, algorithm, signal group or fixed result. Random and prediction-style games should not be called skill-based income. Read the current game rules before choosing any paid option.'], bullets: ['WinGo','K3','5D','Aviator','TRX WinGo','MotoRace'] },
      { heading: 'How to review any game responsibly', paragraphs: ['Before participating, read the current rules, understand possible financial loss, confirm age and location eligibility, and set limits. Do not assume that a familiar name means a game works the same as a similarly named product elsewhere.', 'A recommended or popular label is a navigation treatment, not an endorsement or evidence that a game is safe, profitable or suitable for a particular user.'] },
    ], related: [{label:'Lottery guide',href:'/shree-win-lottery'},{label:'TRX WinGo guide',href:'/trx-wingo'},{label:'MotoRace guide',href:'/motorace'}],
  },
  'shree-win-lottery': {
    slug: 'shree-win-lottery', title: 'Shree Win Lottery: TRX WinGo & MotoRace Guide', description: 'Understand the Shree Win Lottery category and its currently visible TRX WinGo and MotoRace entries with responsible-play guidance.', eyebrow: 'Lottery category', h1: 'Shree Win Lottery Category Guide', intro: 'The current interface includes a dedicated Lottery category. This page explains its confirmed entries and the checks to make before participation.',
    sections: [
      { heading: 'Where the Lottery category appears', paragraphs: ['Lottery appears in the main category navigation near the top of the Shree Win mobile interface. Selecting it presents lottery-related entries separately from Popular, Mini Game and Casino.', 'The category label confirms organisation, but it does not establish a result schedule, stake range or payout rule. Those details must come from the current game interface and terms.'] },
      { heading: 'Currently confirmed entries', paragraphs: ['TRX WinGo and MotoRace are visible in the supplied Lottery view. The screenshots identify their names and artwork, but do not provide enough verified information to describe complete rules or financial mechanics.', 'For that reason, the dedicated guides focus on navigation, terminology and risk awareness. They do not publish invented round times, result formulas or return percentages.'], bullets: ['TRX WinGo','MotoRace'] },
      { heading: 'Lottery-style gaming risk', paragraphs: ['Any game involving money can result in financial loss. Randomness, platform rules and account conditions can affect outcomes. No guide, predictor or private group can guarantee a winning result.', 'Set a strict spending limit, avoid borrowed funds and stop when the limit is reached. Understand local laws and applicable age requirements before creating or using an account.'] },
    ], related: [{label:'TRX WinGo',href:'/trx-wingo'},{label:'MotoRace',href:'/motorace'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  'trx-wingo': {
    slug: 'trx-wingo', title: 'Shree Win TRX WinGo: Interface & Safety Guide', description: 'Learn where TRX WinGo appears in Shree Win, what is currently verified and why predictions or guaranteed outcomes should be avoided.', eyebrow: 'Known lottery entry', h1: 'Shree Win TRX WinGo Guide', intro: 'TRX WinGo has been observed in the Shree Win Lottery section. This guide stays within that confirmed information and avoids unsupported claims about mechanics or results.',
    sections: [
      { heading: 'How to locate TRX WinGo', paragraphs: ['Open the Shree Win lobby and use the Lottery category shown in the main navigation. The supplied interface displays a TRX WinGo card in that section alongside MotoRace.', 'Artwork and position may change when the platform is updated. If the entry is unavailable, check the current platform rather than using a third-party copy or similarly named app.'] },
      { heading: 'What is and is not verified', paragraphs: ['The confirmed facts are limited: the entry is named TRX WinGo and it appears in the Lottery section. The supplied information does not verify a schedule, rules, stake limits, payout values, win rate or connection to any separate TRX service.', 'This website therefore does not publish those details as fact. It also does not provide prediction signals, colour tips, automated bots or “sure-shot” methods.'] },
      { heading: 'Before opening the game', paragraphs: ['Read the live rules, understand possible loss and confirm whether participation is allowed where you live. Treat promotional or social-media claims independently from the game’s actual terms.', 'Decide a limit before play, never chase a loss and do not treat any outcome as income. Keep account credentials and financial PINs private.'] },
    ], related: [{label:'Lottery category',href:'/shree-win-lottery'},{label:'MotoRace guide',href:'/motorace'},{label:'Games overview',href:'/shree-win-games'}],
  },
  motorace: {
    slug: 'motorace', title: 'Shree Win MotoRace: Interface & Safety Guide', description: 'Learn where MotoRace appears in the Shree Win Lottery section, what is verified and how to approach game information responsibly.', eyebrow: 'Known lottery entry', h1: 'Shree Win MotoRace Guide', intro: 'MotoRace is a motorcycle-themed entry visible in the current Shree Win Lottery section. This page describes the observed listing without inventing rules or winning methods.',
    sections: [
      { heading: 'Where MotoRace appears', paragraphs: ['The supplied mobile interface shows MotoRace in the Lottery area next to TRX WinGo. Its motorcycle artwork makes the card easy to identify in the current version.', 'Game listings can move or change. Use the live Shree Win category navigation to verify current availability rather than assuming an older screenshot is permanent.'] },
      { heading: 'Limits of the available information', paragraphs: ['The provided material does not establish how a MotoRace round works, how outcomes are determined, what values can be selected or whether any reward is available. Stating those details would be speculation.', 'This guide therefore concentrates on interface location, account safety and responsible-play checks. No fixed result, pattern, hack or prediction is offered.'] },
      { heading: 'Responsible review checklist', paragraphs: ['Open the live rules before participating and confirm age and location eligibility. Understand that a themed interface does not reduce financial risk or make an outcome predictable.', 'Set limits before any paid participation, do not use borrowed money and stop rather than trying to recover a loss.'], bullets: ['Read current rules','Check local eligibility','Set time and spending limits','Ignore guaranteed-result claims','Protect passwords and OTPs'] },
    ], related: [{label:'Lottery category',href:'/shree-win-lottery'},{label:'TRX WinGo guide',href:'/trx-wingo'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  'shree-win-withdrawal': {
    slug: 'shree-win-withdrawal', title: 'Shree Win Withdrawal: UPI, Bank & USDT Guide', description: 'Understand Shree Win withdrawal options, including the supplied ₹100 UPI and bank minimum and ₹1,000 USDT minimum.', eyebrow: 'Wallet information', h1: 'Shree Win Withdrawal Guide', intro: 'The current information supplied by the site administrator lists three withdrawal routes: UPI and bank transfer from ₹100, and USDT from ₹1,000. This page explains what to check before submitting a request.',
    sections: [
      { heading: 'Withdrawal methods and supplied minimums', paragraphs: ['UPI and bank transfer are the two INR withdrawal routes identified in the supplied information. The stated minimum for each is ₹100. USDT is the crypto withdrawal route identified by the administrator, with a stated minimum of ₹1,000.', 'These are minimum request amounts, not a promise that every request will be approved or completed in a fixed time. The live withdrawal screen remains the place to confirm current limits, eligibility, fees and availability.'], bullets: ['UPI — minimum ₹100','Bank transfer — minimum ₹100','USDT — minimum ₹1,000'] },
      { heading: 'Before using UPI or bank transfer', paragraphs: ['Check that the account-holder name and payment details are accurate before submission. A wrong UPI ID or bank detail can cause delay, rejection or transfer to an unintended destination. Never share a UPI PIN, banking PIN or OTP with another person.', 'Review any identity, wagering or account-verification requirement shown by the platform. ShreeWinAPK.net does not process withdrawals and cannot view, approve, cancel or trace a platform transaction.'] },
      { heading: 'Before using USDT', paragraphs: ['Confirm the wallet address character by character and choose the exact network supported by the Shree Win withdrawal screen. Sending to an incompatible address or network can result in irreversible loss. Do not copy a wallet address from an unsolicited message.', 'The ₹1,000 minimum is the administrator-supplied amount. Check the live conversion, network fee, final receivable amount and platform rules immediately before confirming. Crypto values and network conditions can change.'] },
      { heading: 'Processing time and pending requests', paragraphs: ['The administrator says UPI and bank withdrawal requests are normally processed within 30 minutes, while USDT is described as instant. These are expected times, not guaranteed times. Verification, turnover conditions, payment-network checks, bank delays or wrong receiving details can make a request take longer.', 'If a request stays pending, check the Transaction area and then use the customer-support button in Settings. Share your user ID, amount, date, time and transaction reference. Never share your password, OTP, withdrawal password, UPI PIN or banking PIN.'] },
      { heading: 'Withdrawal safety checklist', paragraphs: ['Use only the withdrawal page inside the account you opened yourself. Ignore people who ask for an advance payment, remote screen access, OTP, password, withdrawal password or UPI PIN to “release” funds.', 'Keep a record of the request shown by the platform. For an account-specific problem, use the support button you independently verify in the live service.'], bullets: ['Confirm the current minimum','Review destination details','Check the USDT network','Read fees and account conditions','Never disclose PINs, OTPs or passwords','Keep the request reference'] },
    ], related: [{label:'Account login guide',href:'/shree-win-login'},{label:'Promotion rules',href:'/shree-win-promotion'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  'shree-win-agent': {
    slug: 'shree-win-agent', title: 'Shree Win Agent Work: Agency & Invitation Guide', description: 'Understand Shree Win agent work, invitation links and codes, the six-level team structure, agency records and commission-rule checks.', eyebrow: 'Agency information', h1: 'Shree Win Agent Work & Agency Guide', intro: 'The supplied Shree Win Agency screens describe an invitation-based team system with six subordinate levels. This guide explains the structure clearly without promising commission or income.',
    sections: [
      { heading: 'How Shree Win agent work begins', paragraphs: ['The agency flow starts with the invitation link or invitation code provided inside the platform. A person who wants an invitee connected to their team must share that platform-generated route. The supplied rules state that the relationship needs to be recorded during registration; adding an informal reference later may not create the same team link.', 'The registration screen includes an invitation-code field. Before sharing a code, an agent should read the current agency and privacy terms and explain that registration, deposits and game participation remain the invitee’s own decisions.'], bullets: ['Use the platform invitation link or code','Confirm the code before registration','Do not collect another person’s password or OTP','Do not promise guaranteed commission or winnings'] },
      { heading: 'The six-level subordinate structure', paragraphs: ['The supplied Agency page explains six subordinate levels. A direct invite is level 1 for the inviter. If that person later invites somebody else, the new account can sit at level 2 for the original inviter while remaining level 1 for the person who invited them. The same pattern continues through the six levels described by the platform.', 'This is a hierarchy for tracking team relationships. It does not mean every level automatically produces a commission. Eligibility depends on the current agency conditions, qualifying activity and the way the platform calculates records.'] },
      { heading: 'Team number, activity and commission records', paragraphs: ['The supplied rules refer to team number, team betting or game activity, team deposits, agency level and commission records. They also explain that different game types can use different commission percentages. An agent should therefore read the live rate table instead of applying one percentage to every game or team member.', 'The supplied screen says commission is calculated from recorded activity and made available through the commission collection record. Rates, qualifying periods, settlement timing and membership levels can change, so this website does not publish an income projection.'], bullets: ['Team number','Qualifying team activity','Team deposit records','Agency or rebate level','Game-specific rate table','Commission collection record'] },
      { heading: 'What responsible agent work looks like', paragraphs: ['A responsible agent explains the platform accurately, shares the correct invitation route and lets each person decide independently. They do not ask to control another account, take passwords, handle OTPs, impersonate support or guarantee that a deposit will produce earnings.', 'Gaming involving money carries risk for every team member. Never encourage borrowed deposits, loss chasing or account farming. Commission eligibility is a platform rule, not guaranteed employment, salary or investment return.'] },
    ], related: [{label:'Registration guide',href:'/shree-win-register'},{label:'Promotion guide',href:'/shree-win-promotion'},{label:'Withdrawal guide',href:'/shree-win-withdrawal'}],
  },
  'shree-win-promotion': {
    slug: 'shree-win-promotion', title: 'Shree Win Promotion Guide: Offers & Terms', description: 'Understand where Shree Win promotions appear, how to review eligibility and why offer amounts should be verified in the live platform.', eyebrow: 'Offer information', h1: 'Shree Win Promotion & Activity Guide', intro: 'The current mobile interface includes dedicated Activity and Promotion destinations. Offers can change, so this page focuses on how to review them instead of repeating unverified amounts.',
    sections: [
      { heading: 'Activity and Promotion are separate destinations', paragraphs: ['The bottom navigation currently includes both Activity and Promotion. Activity is intended for platform-related activities, while Promotion provides a dedicated area for offers or campaigns.', 'Their labels confirm that the sections exist. They do not prove that a particular user qualifies for an offer or that an older screenshot remains current.'] },
      { heading: 'First-deposit tiers shown in the supplied screen', paragraphs: ['The supplied first-deposit screen lists four one-time tiers: deposit ₹300 with a displayed ₹48 bonus, deposit ₹500 with ₹108, deposit ₹1,000 with ₹188, and deposit ₹5,000 with ₹488. The screen also states that each account can receive the first-deposit activity once.', 'These values describe the supplied interface state. Before depositing, confirm that the offer is still visible on the live account and read every condition attached to it. A displayed bonus is not guaranteed income and does not guarantee a game result.'], bullets: ['₹300 deposit — ₹48 displayed bonus','₹500 deposit — ₹108 displayed bonus','₹1,000 deposit — ₹188 displayed bonus','₹5,000 deposit — ₹488 displayed bonus'] },
      { heading: 'How to review an offer', paragraphs: ['Read the start and end dates, eligible users, qualifying action, reward conditions, turnover requirements, claim method and restrictions. If any term is unclear, use a verified platform support route before participating.', 'Do not rely on a banner, third-party message or referral claim alone. The complete in-platform terms should take priority.'], bullets: ['Eligibility','Campaign period','Qualifying action','Claim method','Turnover or usage conditions','Account restrictions'] },
      { heading: 'Turnover and account rules matter', paragraphs: ['The supplied rule screen says the bonus portion is subject to a one-times valid-bet or coding-turnover requirement before withdrawal. It also says repeated participation and technical abuse can lead to cancellation, deduction, freezing or account restrictions.', 'Read the current wording inside the platform because translations, qualifying games and enforcement details can change. Keep the deposit amount separate from the bonus when calculating your own risk.'] },
    ], related: [{label:'Registration guide',href:'/shree-win-register'},{label:'Disclaimer',href:'/disclaimer'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  blog: {
    slug: 'blog', title: 'Shree Win Guides & Information Hub', description: 'Browse original Shree Win APK, download, login, registration, games, Lottery, TRX WinGo, MotoRace and safety guides.', eyebrow: 'Content hub', h1: 'Latest Shree Win Guides', intro: 'A growing library of original, factual resources designed to scale as verified platform information, screenshots and update details become available.',
    sections: [
      { heading: 'Start with the account and app guides', paragraphs: ['The APK guide explains the mobile interface and Android terminology. The download guide adds a source and permission checklist. Login and registration pages explain the observed account journey without collecting credentials.', 'These foundational pages are the best starting point for visitors trying to understand Shree Win before opening the platform.'], bullets: ['Shree Win APK','Download Guide','Login Guide','Registration Guide'] },
      { heading: 'Explore the confirmed game information', paragraphs: ['The games directory covers Lobby, Lottery, Popular, Mini Game and Casino. The Lottery guide links to focused pages for TRX WinGo and MotoRace—the two currently confirmed game entries.', 'Future individual game pages should be added only after the administrator supplies verified names and supporting interface information.'] },
      { heading: 'Editorial standard', paragraphs: ['Every guide should distinguish observed facts from general safety advice. Unverified bonuses, app versions, payout timing, ratings, download counts and outcome claims are excluded.', 'When a product detail changes, the central configuration and affected guide should be updated together so visitors are not shown conflicting information.'] },
    ], related: [{label:'APK guide',href:'/shree-win-apk'},{label:'Games directory',href:'/shree-win-games'},{label:'Promotion guide',href:'/shree-win-promotion'}],
  },
  about: {
    slug: 'about', title: 'About ShreeWinAPK.net', description: 'Learn about ShreeWinAPK.net, an independent information website covering Shree Win APK, games, account guides and safety.', eyebrow: 'About this website', h1: 'About ShreeWinAPK.net', intro: 'ShreeWinAPK.net is an independent informational resource. It is not presented as the official Shree Win website and does not claim ownership of the platform.',
    sections: [
      { heading: 'Our purpose', paragraphs: ['The website organises publicly visible and administrator-supplied product information into readable guides. Topics include the Shree Win APK, Android installation, login, registration, visible categories, TRX WinGo, MotoRace, promotions and responsible gaming.', 'The goal is to help visitors understand what has been observed before they leave for an external platform.'] },
      { heading: 'Our information standard', paragraphs: ['We avoid fake ratings, user totals, download counts, payout speeds, earnings, win rates and guaranteed strategies. Unknown product values remain blank until the administrator can verify them.', 'Screenshots are used to describe interface structure. They may show an earlier state, so the live platform should be checked for current availability and terms.'] },
      { heading: 'Our boundaries', paragraphs: ['ShreeWinAPK.net does not collect Shree Win credentials, process deposits or withdrawals, operate games or decide account eligibility. Login and Register actions lead to a separately operated external site.', 'Visitors are responsible for understanding local law, age requirements and financial risk.'] },
    ], related: [{label:'Disclaimer',href:'/disclaimer'},{label:'Privacy policy',href:'/privacy-policy'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  contact: {
    slug: 'contact', title: 'Contact ShreeWinAPK.net', description: 'Contact information and safe reporting guidance for ShreeWinAPK.net, including what details should never be submitted.', eyebrow: 'Contact information', h1: 'Contact ShreeWinAPK.net', intro: 'Use this page to understand what information is appropriate to share with an independent guide website. A verified public contact channel will be added by the administrator.',
    sections: [
      { heading: 'What you can report', paragraphs: ['Useful reports include a broken internal link, outdated screenshot label, typographical error or a platform detail that can be supported with a current public source. Provide only the minimum information needed to explain the issue.', 'A public contact address is intentionally not invented. When the administrator supplies one, it can be placed here with spam protection.'], bullets: ['Broken page or link','Outdated factual statement','Accessibility problem','Copyright or brand concern','General editorial correction'] },
      { heading: 'What you should never send', paragraphs: ['Do not send a Shree Win password, OTP, withdrawal password, UPI PIN, banking PIN, card details, government identity number or account recovery code. ShreeWinAPK.net cannot use those details to operate or recover a platform account.', 'For account-specific access, payment or verification issues, use a support route you independently verify on the live platform.'] },
      { heading: 'Future contact form scope', paragraphs: ['If a contact form is added, it will request only name, email and message, together with spam protection. It will not ask for platform login credentials or payment information.', 'Until that verified channel is configured, no form is displayed and no email address is fabricated.'] },
    ], related: [{label:'Privacy policy',href:'/privacy-policy'},{label:'Disclaimer',href:'/disclaimer'},{label:'Login safety',href:'/shree-win-login'}],
  },
  'privacy-policy': {
    slug: 'privacy-policy', title: 'Privacy Policy | ShreeWinAPK.net', description: 'Read how ShreeWinAPK.net approaches privacy, credential safety, external links, analytics and future contact-form data.', eyebrow: 'Privacy', h1: 'Privacy Policy', intro: 'This policy explains the information boundaries of ShreeWinAPK.net. The website is designed not to collect Shree Win account or payment credentials.',
    sections: [
      { heading: 'Platform credentials are out of scope', paragraphs: ['Do not enter or send Shree Win usernames, passwords, OTPs, withdrawal passwords, UPI PINs, card data or banking PINs to this website. Login and Register links open an external platform in a new tab.', 'External sites have their own privacy practices. Review the destination address and its policy before providing personal information.'] },
      { heading: 'Basic technical information', paragraphs: ['A hosting provider may process standard request data such as IP address, browser type, device information, requested page and security logs to deliver and protect the website. The exact infrastructure may change with hosting configuration.', 'No advertising tracker or analytics provider is claimed in this policy unless one is actually configured. If analytics or consent-sensitive technology is added later, the policy should be updated first.'] },
      { heading: 'Contact data and retention', paragraphs: ['No contact form is currently active. A future form will be limited to name, email and message with spam protection. Data should be retained only as long as needed to respond, meet security requirements or comply with law.', 'Privacy requests require a verified contact channel, which will be added by the administrator rather than invented.'] },
    ], related: [{label:'Terms',href:'/terms'},{label:'Contact',href:'/contact'},{label:'Disclaimer',href:'/disclaimer'}],
  },
  terms: {
    slug: 'terms', title: 'Terms of Use | ShreeWinAPK.net', description: 'Read the terms for using ShreeWinAPK.net as an independent informational resource, including external links and risk disclosures.', eyebrow: 'Website terms', h1: 'Terms of Use', intro: 'By using ShreeWinAPK.net, you acknowledge that the site provides general information and does not operate the Shree Win platform or guarantee the accuracy of changing product details.',
    sections: [
      { heading: 'Informational use', paragraphs: ['Content is provided to explain observed interface elements, general Android installation safety and account-access processes. It is not financial, legal or technical-security advice for a specific person.', 'You remain responsible for checking current platform terms, local laws, age requirements and the suitability of any action.'] },
      { heading: 'External services', paragraphs: ['Login and Register actions lead to a separately operated website. ShreeWinAPK.net does not control external availability, accounts, games, promotions, payments or privacy practices.', 'Opening an external link does not create an official partnership, endorsement or guarantee. Verify the destination before providing information.'] },
      { heading: 'Accuracy and acceptable use', paragraphs: ['Game availability, screenshots, interface labels and promotion details may change. Reasonable efforts are made to separate confirmed information from unknown values, but no promise is made that every page will always reflect the latest platform state.', 'Do not misuse the website to impersonate another person, distribute malware, attempt unauthorised access or submit sensitive credentials.'] },
    ], related: [{label:'Disclaimer',href:'/disclaimer'},{label:'Privacy policy',href:'/privacy-policy'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  disclaimer: {
    slug: 'disclaimer', title: 'Independent Website Disclaimer | ShreeWinAPK.net', description: 'Understand the independent status of ShreeWinAPK.net, the limits of platform information and the absence of earning or outcome guarantees.', eyebrow: 'Important disclosure', h1: 'Independent Website Disclaimer', intro: 'ShreeWinAPK.net is an independent informational website and does not claim ownership of or official affiliation with the Shree Win platform.',
    sections: [
      { heading: 'Independent status', paragraphs: ['Brand names and screenshots are referenced for identification and informational explanation. ShreeWinAPK.net does not operate Shree Win accounts, games, promotions, deposits, withdrawals or support decisions.', 'Login and Register links point to the administrator-configured external destination. Visitors should independently verify that destination before taking action.'] },
      { heading: 'Changing information', paragraphs: ['Game availability, features, promotions and platform information can change. Supplied screenshots show an observed interface state and are not a guarantee that every element remains available.', 'APK version, file size, download URL and promotion values are omitted until verified.'] },
      { heading: 'No outcome or income guarantee', paragraphs: ['No content on this website guarantees a win, payout, earning, approval, bonus or result. Gaming involving money can cause financial loss.', 'Do not interpret educational content, interface descriptions or internal links as a recommendation to spend money. Understand local law, age rules and personal risk before using a third-party service.'] },
    ], related: [{label:'About this site',href:'/about'},{label:'Terms',href:'/terms'},{label:'Responsible gaming',href:'/responsible-gaming'}],
  },
  'responsible-gaming': {
    slug: 'responsible-gaming', title: 'Responsible Gaming Guide | ShreeWinAPK.net', description: 'Read practical responsible gaming guidance covering financial risk, limits, age and legal checks, borrowed money and chasing losses.', eyebrow: 'Safety first', h1: 'Responsible Gaming', intro: 'Gaming involving money carries financial risk. Outcomes are not guaranteed, and no pattern, signal, strategy or promotion removes the possibility of loss.',
    sections: [
      { heading: 'Set limits before participation', paragraphs: ['Choose a time limit and a spending limit before opening a paid game. Treat the limit as final, not as a target to extend after a loss. Track time and spending honestly.', 'Only use discretionary money that is not needed for housing, food, education, healthcare, debt or other obligations. Never use borrowed money.'], bullets: ['Set time and spending limits','Use only discretionary funds','Take regular breaks','Keep a record of spending','Stop when a limit is reached'] },
      { heading: 'Do not chase losses', paragraphs: ['Trying to recover a loss by increasing time or spending can make harm worse. A previous outcome does not guarantee that the next one will be different or favourable.', 'Avoid “fixed game,” “sure-shot prediction,” “100% winning trick” and guaranteed-profit claims. No third party can remove randomness or financial risk.'] },
      { heading: 'Eligibility and support', paragraphs: ['Users must meet applicable age requirements and understand local laws. Availability on a phone does not mean participation is legal in every location.', 'If gaming affects finances, sleep, work, relationships or mood, stop and seek support from a qualified local service. Consider account limits or self-exclusion tools when the platform provides them.'] },
    ], related: [{label:'Disclaimer',href:'/disclaimer'},{label:'Games overview',href:'/shree-win-games'},{label:'Promotion guide',href:'/shree-win-promotion'}],
  },
};
