export type GuideSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type GuideContent = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  intro: string;
  sections: GuideSection[];
  related: { label: string; href: string }[];
  cta?: 'login' | 'register' | 'visit';
};

export const guidePages: Record<string, GuideContent> = {
  'shree-win-apk': {
    slug: 'shree-win-apk', title: 'ShreeWin APK: App Features, Access & Android Guide', description: 'Learn what the ShreeWin APK is, what the mobile app shows, which details need checking and how to use an Android APK carefully.', eyebrow: 'ShreeWin app information', h1: 'ShreeWin APK and Mobile App Guide', intro: 'ShreeWin APK means the Android installation file for the ShreeWin app. This page explains the visible app features and the details you should check before you download or install any APK file.', cta: 'visit',
    sections: [
      { heading: 'What is the ShreeWin APK?', paragraphs: ['APK stands for Android Package Kit. It is the file type used to install an app on an Android phone when the app is downloaded outside the Play Store. People normally search for ShreeWin APK when they want the Android app or want to check its features before installing it.', 'An APK file should come from a source you trust. The file name or app logo alone cannot prove that a download is genuine. ShreeWinAPK.net does not host an APK because the current download URL, version, file size and file checksum have not been verified.'] },
      { heading: 'What you can see inside the app', paragraphs: ['The supplied ShreeWin screens show five main tabs: Lobby, Lottery, Popular, Mini Game and Casino. The Lottery section shows TRX WinGo and MotoRace. Other supplied information also names WinGo, K3, 5D and Aviator.', 'The bottom menu includes Home, Activity, Promotion and Account. Login and Register options are also visible. The exact order, artwork and game list can change when the app is updated.'], bullets: ['Lobby and category navigation', 'Lottery, Popular, Mini Game and Casino tabs', 'TRX WinGo and MotoRace entries', 'Home, Activity, Promotion and Account menu', 'Phone or email account access'] },
      { heading: 'Details to check before installation', paragraphs: ['Check the app name, source website, version, file size and permissions before you install it. Android may show a warning when you install an app from a browser. Read that warning instead of tapping through it quickly.', 'The current ShreeWin APK version, size, direct download source and checksum are [VERIFY BEFORE PUBLISHING]. A checksum is a code that helps you check whether a downloaded file has been changed.'], bullets: ['APK version: [VERIFY BEFORE PUBLISHING]', 'APK size: [VERIFY BEFORE PUBLISHING]', 'Direct APK source: [VERIFY BEFORE PUBLISHING]', 'File checksum: [VERIFY BEFORE PUBLISHING]'] },
      { heading: 'Account and phone safety', paragraphs: ['Install only the app you intended to download. Stop if the installer asks you to switch off phone security permanently, install another unknown app or give a permission that does not match the app function.', 'Never share your password, OTP, UPI PIN, bank PIN or withdrawal password. This website gives information only. It does not ask for ShreeWin login details and cannot open, recover or verify a platform account.'] },
    ], related: [{ label: 'APK download guide', href: '/shree-win-download' }, { label: 'Games overview', href: '/shree-win-games' }, { label: 'Login guide', href: '/shree-win-login' }],
  },

  'shree-win-download': {
    slug: 'shree-win-download', title: 'ShreeWin App Download: Android APK Installation Guide', description: 'Follow simple ShreeWin app download and Android installation steps, check APK permissions and fix common download problems safely.', eyebrow: 'Android download help', h1: 'ShreeWin App Download and Installation Guide', intro: 'To download the ShreeWin app, first check that the APK source is correct. This website does not provide an APK file because the current file URL and release details are not yet verified.', cta: 'visit',
    sections: [
      { heading: 'Before you download the ShreeWin APK', paragraphs: ['Read the website address carefully before you tap a download button. Avoid APK links received from unknown WhatsApp, Telegram, SMS or email accounts. A copied logo does not prove that a file belongs to ShreeWin.', 'Keep Google Play Protect and your phone security turned on. Do not download modified, cracked or “unlimited balance” files. Such files may contain malware or may try to steal account information.'], bullets: ['Check the complete website address', 'Avoid modified or cracked APK files', 'Keep Android security enabled', 'Check available phone storage', 'Use a stable mobile data or Wi-Fi connection'] },
      { heading: 'How to install an APK on Android', paragraphs: ['Download the APK only after you trust the source. Open the downloaded file from your browser or Downloads folder. Android may ask for permission to install apps from that browser; allow it only for this installation and remove the permission later if you do not need it.', 'Check the app name and requested permissions before you tap Install. After installation, open the app from your phone menu. Enter your login details only inside the correct app or website.'], bullets: ['Open the verified download source', 'Download the APK file', 'Review the Android warning', 'Allow installation only from the selected browser', 'Check permissions and tap Install', 'Open the installed app from your phone menu'] },
      { heading: 'How to update the app', paragraphs: ['Use the update option shown inside the app or return to the same verified source used for the first installation. Do not install an update sent by an unknown person. Check whether the new app name and permissions match the existing installation.', 'The latest ShreeWin version and release date are [VERIFY BEFORE PUBLISHING]. Do not remove your existing app until you know whether the update will keep your account access and local settings.'] },
      { heading: 'Fix download and installation problems', paragraphs: ['If the download stops, check your internet connection and free storage, then start it again from the same source. If Android says the file cannot be opened, the download may be incomplete or the file may not be a valid APK.', 'If installation is blocked, read the exact Android message. Do not switch off every security setting. If the app asks for unrelated permissions or shows a different name, cancel the installation and verify the file.'] },
      { heading: 'Download details still needing verification', paragraphs: ['Direct APK URL, latest version, file size, release date and checksum are [VERIFY BEFORE PUBLISHING]. Until these details are checked, the Visit Shree Win button opens the configured external page instead of offering an unverified file.'] },
    ], related: [{ label: 'What is Shree Win APK?', href: '/shree-win-apk' }, { label: 'Login guide', href: '/shree-win-login' }, { label: 'Privacy policy', href: '/privacy-policy' }],
  },

  'shree-win-login': {
    slug: 'shree-win-login', title: 'ShreeWin Login: Phone, Email & Password Help', description: 'Learn the ShreeWin login steps for phone or email, reset a forgotten password and fix OTP, password or account-access problems.', eyebrow: 'Account access help', h1: 'ShreeWin Login Guide', intro: 'To complete the ShreeWin login, open the login page and choose Phone Number or Email. Enter the details linked to your account, check them once and then tap Login.', cta: 'login',
    sections: [
      { heading: 'Details needed for ShreeWin login', paragraphs: ['The supplied login screen shows Phone Number and Email tabs. For phone login, you need the correct country code, registered mobile number and password. For email login, enter the email address connected to your account and your password.', 'Use the same login method used when the account was created. This website does not show a working login form and never asks you to enter your account details here.'] },
      { heading: 'ShreeWin login steps', paragraphs: ['Open the ShreeWin login page from the Login button. Choose Phone Number or Email, enter your registered details and check for typing mistakes. Complete any verification shown by the platform and continue to the account dashboard.', 'If you use a shared phone, do not select Remember Password. Always log out after use and remove any saved password from the browser.'], bullets: ['Open the login page', 'Choose phone or email', 'Enter your registered details', 'Check the country code and spelling', 'Complete verification if requested', 'Tap Login'] },
      { heading: 'Forgotten password and OTP problems', paragraphs: ['Tap Forgot Password on the login screen. The supplied reset screen shows phone recovery, a new password field, password confirmation and a verification code. Enter the code only on the platform page you opened yourself.', 'If an OTP does not arrive, check the mobile number and country code, wait for the resend timer and make sure your phone can receive SMS. OTP delivery method and retry limits are [VERIFY BEFORE PUBLISHING].'] },
      { heading: 'Incorrect password or locked account', paragraphs: ['Check whether Caps Lock, spaces or an old saved password caused the error. Use password recovery instead of trying many passwords. The exact account-lock rule is [VERIFY BEFORE PUBLISHING].', 'If recovery does not work, use the customer-support option shown inside the platform or its verified account page. Share your user ID and the error, but never share your password, OTP, UPI PIN or withdrawal password.'] },
      { heading: 'Keep your account access private', paragraphs: ['Use a different password from your email, bank and UPI apps. Do not give remote screen access to a person claiming they can fix your login. Check the web address before you enter any credential.', 'Customer-support channels and support hours are [VERIFY BEFORE PUBLISHING]. ShreeWinAPK.net cannot unlock, recover or verify a ShreeWin account.'] },
    ], related: [{ label: 'Registration guide', href: '/shree-win-register' }, { label: 'APK guide', href: '/shree-win-apk' }, { label: 'Contact information', href: '/contact' }],
  },

  'shree-win-register': {
    slug: 'shree-win-register', title: 'ShreeWin Register: Phone, Email & Invite Code Guide', description: 'Follow the ShreeWin registration steps using a phone number or email, create a password and understand invite-code and OTP checks.', eyebrow: 'New account help', h1: 'How to Register on ShreeWin', intro: 'The ShreeWin registration screen provides phone and email options. Choose one method, enter your own details, create a strong password and check every field before you tap Register.', cta: 'register',
    sections: [
      { heading: 'Phone and email registration options', paragraphs: ['The phone form shown in the supplied screen includes country code, mobile number, password, password confirmation and invitation code. The email form includes email, password, confirmation and invitation code.', 'Use a phone number or email address that you control. The exact verification method and whether every field is compulsory are [VERIFY BEFORE PUBLISHING].'] },
      { heading: 'Step-by-step ShreeWin registration', paragraphs: ['Open the registration page from the Register button. Choose phone or email, enter the requested details and create a password that you do not use on another account.', 'Read the Privacy Agreement and account terms shown by the platform. Complete any OTP or email verification and submit the form. Do not share the verification code with another person.'], bullets: ['Open the registration page', 'Choose phone or email', 'Enter details that belong to you', 'Create and confirm a strong password', 'Check the invitation code', 'Read the terms and complete verification'] },
      { heading: 'Use the ShreeWin invitation code', paragraphs: ['Register through the ShreeWin link provided on this website and check that the invitation code is visible before you submit. Eligible new users who register with this code can receive a ₹100 invite bonus under the current offer.', 'Bonus credit, VIP benefits and other game perks follow the terms shown on the live registration page. Check the eligibility and claim conditions before creating the account because the invitation relationship is recorded during registration.'] },
      { heading: 'Fix common registration errors', paragraphs: ['If the mobile number is rejected, check the country code and number length. If the email is rejected, remove spaces and check the spelling. Your password and confirmation must match exactly.', 'If an OTP is delayed, wait for the resend option and check network or SMS blocking. If the page says the account already exists, use the login or password-recovery page instead of creating repeated accounts.'] },
      { heading: 'Registration safety', paragraphs: ['Never pay a person only to create an account for you. Do not share your password, OTP, UPI PIN, banking PIN or identity document through an unverified chat. Use your own phone and review the destination address.', 'ShreeWinAPK.net does not collect registration details. Age and location rules apply, and you should check local law before opening an account.'] },
    ], related: [{ label: 'Login guide', href: '/shree-win-login' }, { label: 'Privacy policy', href: '/privacy-policy' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  'shree-win-games': {
    slug: 'shree-win-games', title: 'ShreeWin Games: WinGo, K3, 5D, Aviator & Lottery', description: 'Explore ShreeWin games and categories, including WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace, with clear screen and rule information.', eyebrow: 'ShreeWin game information', h1: 'ShreeWin Games and Categories', intro: 'The ShreeWin app brings its game listings together under Lobby, Lottery, Popular, Mini Game and Casino. This page explains the main games, where to find them and which screen details to check before you join a round.',
    sections: [
      { heading: 'Main game categories', paragraphs: ['Lobby is the main view where you can browse available content. Lottery, Popular, Mini Game and Casino organise the game cards into separate groups, making it easier to move between different types of play.', 'The available list and card order may change after an app update. Open the current category tab to see the games available on your account.'], bullets: ['Lobby', 'Lottery', 'Popular', 'Mini Game', 'Casino'] },
      { heading: 'WinGo colour and number game', paragraphs: ['WinGo is a colour and number game available in the ShreeWin app. Before you join a round, check the selected period, available choices, countdown and result history shown on the game screen.', 'Read the current rules so you understand how entries are placed and how results are displayed. The exact round periods, entry limits and settlement table are [VERIFY BEFORE PUBLISHING].'] },
      { heading: 'K3 and 5D games', paragraphs: ['K3 and 5D are number-style game entries named in the supplied ShreeWin information. Open the selected game and first check its period, number choices, entry panel and result section.', 'The complete K3 and 5D rules, available durations and entry amounts are [VERIFY BEFORE PUBLISHING]. Use the Help or Rules option inside each game for the current details.'] },
      { heading: 'Aviator', paragraphs: ['Aviator is listed as a crash-style game. Its round screen normally centres on timing and an on-screen value, but the exact ShreeWin controls and settlement rules must be checked inside the live game.', 'Round duration, entry options and result handling are [VERIFY BEFORE PUBLISHING]. Do not assume that a similarly named game on another app uses the same rules.'] },
      { heading: 'TRX WinGo and MotoRace', paragraphs: ['TRX WinGo and MotoRace appear in the Lottery section. Their cards can be opened from the category row on the ShreeWin homepage. Separate guides explain how to locate each game and what to check on its round screen.', 'Complete round durations, available choices and result rules are [VERIFY BEFORE PUBLISHING]. Always follow the instructions shown inside the current game.'] },
      { heading: 'What to check on every game screen', paragraphs: ['Check the selected game name, round period, countdown, available choices, entry amount and result history before you tap Confirm. Make sure the round is still open and review any rule that affects settlement.', 'Use a fixed time and spending limit for paid play. Users must be 18+ and should check the laws that apply in their state or location.'], bullets: ['Game name and selected period', 'Round countdown', 'Available choices', 'Entry amount', 'Result and transaction record', 'Current game rules'] },
    ], related: [{ label: 'Lottery guide', href: '/shree-win-lottery' }, { label: 'TRX WinGo guide', href: '/trx-wingo' }, { label: 'MotoRace guide', href: '/motorace' }],
  },

  'shree-win-lottery': {
    slug: 'shree-win-lottery', title: 'ShreeWin Lottery: TRX WinGo & MotoRace Guide', description: 'Learn how to open the ShreeWin Lottery section, find TRX WinGo and MotoRace, and check round, entry and result details.', eyebrow: 'Lottery game information', h1: 'ShreeWin Lottery Guide', intro: 'ShreeWin has a separate Lottery category in the main game menu. The supplied app screens show TRX WinGo and MotoRace in this section.',
    sections: [
      { heading: 'How to open the Lottery section', paragraphs: ['Open the ShreeWin homepage and look at the category row near the top. Tap Lottery to see the current lottery game cards. This section is separate from Popular, Mini Game and Casino.', 'The order and artwork can change after an app update. Use the live category page to see the current listing.'] },
      { heading: 'Games shown in Lottery', paragraphs: ['TRX WinGo and MotoRace are the two entries visible in the supplied Lottery screen. Tap the required card to open its game page and review the information shown for the active round.', 'Other game names should be added to this guide only after they are confirmed in the current ShreeWin interface.'], bullets: ['TRX WinGo', 'MotoRace'] },
      { heading: 'How to read a round screen', paragraphs: ['Check the game name and selected period first. Read the countdown, available entry choices and confirmation details before you submit. After the round closes, use the result or history area to check the displayed outcome.', 'Exact periods, entry limits, closing rules and settlement tables for the current Lottery games are [VERIFY BEFORE PUBLISHING]. Follow the in-game Help or Rules page.'] },
      { heading: 'Result and transaction checks', paragraphs: ['If a result or balance is not updated, first refresh the game page and check your Game History or Transaction record. Keep the round number and entry reference before you contact platform support.', 'For paid participation, set a clear amount and time limit. Do not share a password, OTP, UPI PIN or withdrawal password when asking about a game record.'] },
    ], related: [{ label: 'TRX WinGo', href: '/trx-wingo' }, { label: 'MotoRace', href: '/motorace' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  'trx-wingo': {
    slug: 'trx-wingo', title: 'ShreeWin TRX WinGo: Access, Round & Result Guide', description: 'Find TRX WinGo in the ShreeWin Lottery section and learn how to check the period, countdown, entry choices and result record.', eyebrow: 'TRX WinGo information', h1: 'ShreeWin TRX WinGo Guide', intro: 'TRX WinGo is available from the Lottery section shown in the supplied ShreeWin interface. Use this page to understand where the game appears and how to review its round screen.',
    sections: [
      { heading: 'How to find TRX WinGo', paragraphs: ['Open the ShreeWin homepage and tap Lottery in the main category row. Look for the TRX WinGo card and open it from inside the app. The supplied layout shows MotoRace in the same section.', 'If the card has moved, check the full Lottery list. Use the current ShreeWin interface instead of a similarly named third-party page.'] },
      { heading: 'Check the selected period and countdown', paragraphs: ['When the game opens, confirm which period or round is active. Check the countdown before selecting an option because an entry submitted after the closing point may not be accepted.', 'The exact period durations and late-entry rule are [VERIFY BEFORE PUBLISHING]. Read the Rules option shown inside the current game before you start.'] },
      { heading: 'Review entry choices before confirmation', paragraphs: ['Read every available choice and the amount shown in the entry panel. Check the selected option again before you tap Confirm. Keep the round number so you can match the entry with the displayed result later.', 'Current minimum and maximum entry amounts, choice types and settlement values are [VERIFY BEFORE PUBLISHING].'] },
      { heading: 'How results are shown', paragraphs: ['After a round ends, open the result or history area and match the period number with your entry record. If the result is not visible, refresh the page and check again after the platform completes the round.', 'For a result or balance issue, save the period number, transaction reference, date, time and a clear screenshot. Share these details through verified platform support without sharing a password, OTP or payment PIN.'] },
      { heading: 'Use clear play limits', paragraphs: ['Set the maximum time and amount you plan to use before opening a paid round. Stop when your limit is reached and do not use money needed for bills or household costs.', 'No result can be promised in advance. Users must be 18+ and should check the gaming rules that apply in their location.'] },
    ], related: [{ label: 'Lottery category', href: '/shree-win-lottery' }, { label: 'MotoRace guide', href: '/motorace' }, { label: 'Games overview', href: '/shree-win-games' }],
  },

  motorace: {
    slug: 'motorace', title: 'ShreeWin MotoRace: Access, Round & Result Guide', description: 'Learn where MotoRace appears in ShreeWin and how to check its current round, entry options, countdown and result record.', eyebrow: 'MotoRace information', h1: 'ShreeWin MotoRace Guide', intro: 'MotoRace is a motorcycle-themed game card shown in the ShreeWin Lottery section. This guide explains how to find the game and which round details to review.',
    sections: [
      { heading: 'How to open MotoRace', paragraphs: ['Open the ShreeWin homepage, tap Lottery and look for the MotoRace card. The supplied screen shows it near TRX WinGo. Tap the card to open the current MotoRace page.', 'Game card positions can change. If you cannot see it immediately, check the full Lottery list in the live app.'] },
      { heading: 'Read the active round details', paragraphs: ['Check the selected round or period and the countdown shown on the game screen. Review the available choices and make sure you understand the confirmation step before submitting an entry.', 'The current MotoRace durations, choice types, entry limits and closing rules are [VERIFY BEFORE PUBLISHING]. Use the in-game Help or Rules option for these details.'] },
      { heading: 'Check the result and history', paragraphs: ['When a round is complete, match its period number with the result shown in the game history. Also check your entry or transaction record so you are looking at the correct round.', 'If a record remains pending, refresh the page and wait for the platform to update it. Save the round number, date, time and screenshot before contacting verified support.'] },
      { heading: 'Account and play safety', paragraphs: ['Keep your password, OTP, UPI PIN and withdrawal password private. Platform support can review a round reference without asking for these secret details.', 'For paid rounds, choose your time and spending limits first. Users must be 18+ and should follow the laws that apply in their location.'] },
    ], related: [{ label: 'Lottery category', href: '/shree-win-lottery' }, { label: 'TRX WinGo guide', href: '/trx-wingo' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  'shree-win-withdrawal': {
    slug: 'shree-win-withdrawal', title: 'ShreeWin Withdrawal: UPI, Bank & USDT Help', description: 'Learn the ShreeWin withdrawal steps, add UPI or bank details, check stated limits and fix a pending or failed withdrawal safely.', eyebrow: 'Withdrawal help', h1: 'ShreeWin Withdrawal Guide', intro: 'To submit a ShreeWin withdrawal, open Wallet, choose Withdrawal, select an available method and enter the required amount. Check your receiving details carefully before you confirm.',
    sections: [
      { heading: 'Check withdrawal eligibility', paragraphs: ['Your account may need phone, identity, bank or payment verification before a withdrawal is accepted. A promotion may also have a turnover condition. Turnover means the valid game activity required under an offer before the related bonus can be withdrawn.', 'Exact eligibility, maximum limits, fees and verification rules are [VERIFY BEFORE PUBLISHING]. Read the current Withdrawal and Promotion terms inside your account.'] },
      { heading: 'Add a bank account or UPI ID', paragraphs: ['Open Account or Wallet and look for the bank-account or withdrawal settings. Enter the account-holder name, bank name, account number and IFSC code exactly as shown in your bank records. If UPI is available, enter your complete UPI ID and check the spelling.', 'The name may need to match the verified account details. Complete any OTP check only inside the platform. Never share your OTP, UPI PIN, bank PIN, card PIN or full banking login with support.'] },
      { heading: 'Withdrawal methods and minimum amounts', paragraphs: ['The current information lists UPI and bank transfer with a minimum request of ₹100. It lists USDT with a minimum request of ₹1,000. Check these limits on the live Withdrawal screen before submitting.', 'For USDT, check the wallet address and network character by character. A wrong address or network can cause permanent loss. Also check any network fee and the final amount you will receive.'], bullets: ['UPI — minimum ₹100', 'Bank transfer — minimum ₹100', 'USDT — minimum ₹1,000'] },
      { heading: 'How to submit a withdrawal', paragraphs: ['Choose the receiving account, enter an amount within the current limit and review all details. Read any turnover, fee or verification message before you tap Confirm. Save the request or transaction reference shown after submission.', 'Do not pay an advance fee to a person who says they can release the withdrawal. Never allow remote screen access to your phone for payment help.'], bullets: ['Open Wallet and tap Withdrawal', 'Choose UPI, bank or USDT if available', 'Select or add the receiving details', 'Enter and check the amount', 'Read conditions and tap Confirm', 'Save the transaction reference'] },
      { heading: 'Processing time and pending withdrawal', paragraphs: ['UPI and bank withdrawal requests are stated as normally processed within 30 minutes, while USDT is stated as instant. These are expected times, not a guarantee. Verification, turnover checks, bank delay, network delay or incorrect details can take longer.', 'If a request is pending, check Wallet or Transaction history. Wait for the stated processing window, then use the customer-support button inside Settings. Share your user ID, amount, date, time, method, status screenshot and transaction reference.'] },
      { heading: 'Failed withdrawal and safe support', paragraphs: ['Check whether the receiving details, minimum amount, account verification and turnover conditions are complete. Do not keep sending the same request when the first one is still pending.', 'Customer-support channels and response time are [VERIFY BEFORE PUBLISHING]. Never share your password, OTP, withdrawal password, UPI PIN, bank PIN or recovery code in a complaint.'] },
    ], related: [{ label: 'Account login guide', href: '/shree-win-login' }, { label: 'Promotion rules', href: '/shree-win-promotion' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  'shree-win-agent': {
    slug: 'shree-win-agent', title: 'ShreeWin Agent: Invite, Team Levels & Commission Guide', description: 'Understand ShreeWin agent invitations, the six-level team structure, qualifying records, referral disclosure and commission conditions.', eyebrow: 'Agent and referral information', h1: 'ShreeWin Agent and Agency Guide', intro: 'The ShreeWin Agency section uses an invitation-based team structure with six levels. This page explains how the invite link, team records and commission conditions work.',
    sections: [
      { heading: 'How the invitation link works', paragraphs: ['An agent shares the invitation link or code generated for the registration flow. The new user opens that link and checks that the invitation code is visible before submitting the form. The relationship is recorded during registration.', 'Eligible new users who register through the link on this website can receive a ₹100 invite bonus under the current offer. Bonus credit, VIP benefits and other game perks follow the terms shown on the live registration page.'], bullets: ['Open the shared Register link', 'Check the invitation code field', 'Read the current invite offer', 'Complete registration with your own details', 'Keep the password and OTP private'] },
      { heading: 'Six-level team structure', paragraphs: ['A person invited directly by you is level 1. If that person invites somebody else, the new account can be level 2 for you and level 1 for the direct inviter. The same connection continues through the six levels shown on the Agency page.', 'A team position does not automatically create a commission. The account must meet the current qualifying rules, and only activity recorded by the platform is included.'] },
      { heading: 'Team records and commission calculation', paragraphs: ['The Agency rules refer to team number, team activity, team deposits, agency level and commission records. Different game types can use different rates, so check the current rate table instead of applying one percentage to every member.', 'Commission rate, qualifying activity, settlement time and withdrawal conditions are [VERIFY BEFORE PUBLISHING]. Agent commission should not be presented as fixed employment, guaranteed salary or guaranteed income.'], bullets: ['Team number', 'Qualifying activity', 'Team deposit record', 'Agency or rebate level', 'Game-specific rate', 'Commission collection record'] },
      { heading: 'Give invited users clear information', paragraphs: ['Tell the invited person that the link connects their account to your agent team and that a platform commission may apply when the current conditions are met. Registration, deposit and game choices remain their own decision.', 'Explain the ₹100 invite offer and ask the user to check the amount and conditions shown on the live registration page. Do not promise an extra amount that is not displayed in the current offer.'] },
      { heading: 'Safe and responsible agent work', paragraphs: ['Never operate another person’s account or ask for their password, OTP, UPI PIN or withdrawal password. Do not impersonate customer support or ask someone to send funds to a personal payment ID.', 'Do not pressure a person to deposit, borrow money or chase a loss. Agent status does not remove age checks, local-law checks or responsible-gaming limits.'] },
    ], related: [{ label: 'Registration guide', href: '/shree-win-register' }, { label: 'Promotion guide', href: '/shree-win-promotion' }, { label: 'Withdrawal guide', href: '/shree-win-withdrawal' }],
  },

  'shree-win-promotion': {
    slug: 'shree-win-promotion', title: 'ShreeWin Promotion: Bonus Rules & Activity Guide', description: 'Learn where ShreeWin promotions appear, how to check eligibility, first-deposit tiers, turnover rules and claim problems.', eyebrow: 'Promotion and activity help', h1: 'ShreeWin Promotion and Activity Guide', intro: 'The ShreeWin app has separate Activity and Promotion areas. Open the current offer and read its complete rules before you deposit or claim a reward.',
    sections: [
      { heading: 'Where to find promotions and activities', paragraphs: ['Use the bottom menu to open Activity or Promotion. Activity shows platform tasks and reward-related entries, while Promotion shows available campaigns. The exact cards and their order can change.', 'A campaign may be limited to selected accounts or actions. Open the offer details and check the date, account requirement, qualifying action and claim method.'] },
      { heading: 'First-deposit offer shown in the app', paragraphs: ['The supplied first-deposit screen shows four one-time tiers: ₹300 with a displayed ₹48 bonus, ₹500 with ₹108, ₹1,000 with ₹188 and ₹5,000 with ₹488. The screen says each account can receive this activity once.', 'Check that the offer is still visible in your account before payment. A bonus follows the current promotion rules and does not guarantee any game result.'], bullets: ['Deposit ₹300 — displayed bonus ₹48', 'Deposit ₹500 — displayed bonus ₹108', 'Deposit ₹1,000 — displayed bonus ₹188', 'Deposit ₹5,000 — displayed bonus ₹488'] },
      { heading: 'Check eligibility and turnover rules', paragraphs: ['Read who can join, the campaign period, minimum qualifying action, reward amount, claim button and account restrictions. Turnover means the valid game activity required before some bonus amounts can be withdrawn.', 'The supplied rules state that the bonus portion has a one-times valid-bet or coding-turnover condition. The exact eligible games, calculation method and translated wording are [VERIFY BEFORE PUBLISHING].'] },
      { heading: 'How to claim a promotion', paragraphs: ['Open the offer from Activity or Promotion and follow the steps shown there. Complete only the listed qualifying action, then use the claim button if one is provided. Save a screenshot of the terms and completed status.', 'Do not send funds to a personal UPI ID because someone promises an extra bonus. Use only the payment details shown in the platform deposit flow.'] },
      { heading: 'Promotion not received', paragraphs: ['Check whether the offer is active, whether your account is eligible and whether the qualifying transaction is complete. Also check if the reward needs to be claimed manually instead of being added automatically.', 'If the issue remains, use verified platform support. Share the offer name, date, amount, transaction reference and screenshots. Never share your password, OTP, UPI PIN or withdrawal password.'] },
    ], related: [{ label: 'Registration guide', href: '/shree-win-register' }, { label: 'Disclaimer', href: '/disclaimer' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  blog: {
    slug: 'blog', title: 'ShreeWin Guides: App, Login, Games & Account Help', description: 'Browse focused ShreeWin guides for the APK, Android download, login, registration, games, Lottery, promotions and withdrawals.', eyebrow: 'ShreeWin information hub', h1: 'ShreeWin Guides and Help', intro: 'Choose the guide that matches your question. Each page focuses on one topic so you can find the required steps without reading unrelated information.',
    sections: [
      { heading: 'App and download guides', paragraphs: ['The APK guide explains what an Android APK is and which ShreeWin app features are visible. The download guide covers source checks, Android installation, permissions, updates and common file errors.', 'Start with these pages if you are looking for the Android app. No APK file is offered until its source and release details are verified.'], bullets: ['ShreeWin APK and mobile app guide', 'ShreeWin Android download and installation guide'] },
      { heading: 'Account-access guides', paragraphs: ['The login page covers phone and email access, forgotten passwords, OTP delay and incorrect-password problems. The registration page covers new account fields, verification, invitation codes and registration errors.', 'These guides never ask you to submit a password or OTP. Login and Register buttons lead to the configured external platform page.'], bullets: ['ShreeWin login help', 'ShreeWin registration help'] },
      { heading: 'Game and Lottery guides', paragraphs: ['The games page covers the available category and game names. The Lottery, TRX WinGo and MotoRace pages explain where each entry appears and how to read its round screen.', 'Use these guides to check periods, choices, countdowns, result history and the details that must be confirmed in the current game.'] },
      { heading: 'Promotion, withdrawal and agent guides', paragraphs: ['The promotion guide explains the displayed first-deposit tiers, eligibility checks and turnover terms. The withdrawal guide covers UPI, bank and USDT requests, receiving details and pending-request help.', 'The agent page explains invitation tracking, the ₹100 invite offer and the six-level team structure. Commission always follows current qualifying conditions.'] },
      { heading: 'How information is reviewed', paragraphs: ['We separate supplied screens and confirmed page details from items that still need checking. App versions, file sizes, player totals and complete game rules are not guessed.', 'A last-checked date should be added only after a page has been reviewed against current information. Old pages should not receive a new date only to appear fresh.'] },
    ], related: [{ label: 'APK guide', href: '/shree-win-apk' }, { label: 'Games directory', href: '/shree-win-games' }, { label: 'Promotion guide', href: '/shree-win-promotion' }],
  },

  about: {
    slug: 'about', title: 'About ShreeWinAPK.net | Independent ShreeWin Guides', description: 'Learn what ShreeWinAPK.net provides, how its information is checked and what the website does not do for ShreeWin users.', eyebrow: 'About this website', h1: 'About ShreeWinAPK.net', intro: 'ShreeWinAPK.net is an independent information website. It is not the ShreeWin platform operator, does not claim to be the official website and does not claim authorised affiliation.',
    sections: [
      { heading: 'Why this website exists', paragraphs: ['This website explains the ShreeWin app, Android APK, account access, visible games, promotions, withdrawals and agent rules in clear language. The aim is to help Indian mobile users understand each process and the details they should check.', 'Information comes from supplied interface screens, confirmed site details and general safety guidance. Unknown product details are marked for verification instead of being guessed.'] },
      { heading: 'What we check before publishing', paragraphs: ['We check whether a claim is visible in the supplied material or supported by current information. We do not create fake ratings, player numbers, APK versions, file sizes, support hours or winning percentages.', 'Game screens and rules can change. Important amounts, account conditions and app files should be checked before publication and before a user takes action.'] },
      { heading: 'What this website does not do', paragraphs: ['ShreeWinAPK.net does not operate games, create platform accounts, process deposits, approve withdrawals or decide promotion eligibility. It also does not provide a fixed result or guaranteed earning method.', 'We do not collect ShreeWin usernames, passwords, OTPs, withdrawal passwords, UPI PINs, bank PINs or card details. Account and payment issues must be handled through a support channel verified inside the platform.'] },
      { heading: 'External Login and Register buttons', paragraphs: ['The Login and Register buttons open a separately operated external page. A link does not mean ShreeWinAPK.net owns or controls that service. Check the destination address and current terms before you enter personal information.', 'Users must meet applicable age requirements, understand local laws and consider the possibility of financial loss.'] },
    ], related: [{ label: 'Disclaimer', href: '/disclaimer' }, { label: 'Privacy policy', href: '/privacy-policy' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  contact: {
    slug: 'contact', title: 'Contact ShreeWinAPK.net | Editorial & Safety Help', description: 'Learn how to report a website issue to ShreeWinAPK.net, what details to provide and which sensitive information you must never share.', eyebrow: 'Contact and reporting help', h1: 'Contact ShreeWinAPK.net', intro: 'Use this page for website corrections, broken links, accessibility problems or factual updates supported by a current source. A verified public email address or contact form is not currently available.',
    sections: [
      { heading: 'What you can contact us about', paragraphs: ['You may report a broken page, wrong link label, spelling mistake, outdated screenshot description, accessibility issue or factual statement supported by a current source. Include the page URL and the exact line that needs review.', 'Public email address, contact form and normal response time are [VERIFY BEFORE PUBLISHING].'], bullets: ['Broken page or internal link', 'Spelling or content correction', 'Outdated supported information', 'Accessibility problem', 'Copyright or brand concern'] },
      { heading: 'Platform account and payment problems', paragraphs: ['ShreeWinAPK.net cannot reset a platform password, unlock an account, trace a deposit or approve a withdrawal. For those issues, use the support option you verify inside the live ShreeWin platform.', 'Include your user ID, issue type, date, amount and transaction reference when relevant. Hide sensitive details in screenshots before sending them.'] },
      { heading: 'Information you must never share', paragraphs: ['Never send a password, OTP, withdrawal password, UPI PIN, bank PIN, card PIN, complete card number, account recovery code or remote-access code. Support should not need these details to read a complaint.', 'Do not send an identity document to an email address or chat account that you have not verified. Do not pay a person who asks for a fee to unlock support or release a payment.'] },
      { heading: 'How to escalate an unresolved complaint', paragraphs: ['Keep the original complaint reference, screenshots and transaction record. Reply through the same verified support route and ask for escalation. State the problem and requested resolution clearly.', 'The platform escalation process and expected response time are [VERIFY BEFORE PUBLISHING]. If the matter involves a bank, UPI provider or crypto wallet, follow that provider’s official dispute process when applicable.'] },
    ], related: [{ label: 'Privacy policy', href: '/privacy-policy' }, { label: 'Disclaimer', href: '/disclaimer' }, { label: 'Login safety', href: '/shree-win-login' }],
  },

  'privacy-policy': {
    slug: 'privacy-policy', title: 'Privacy Policy | ShreeWinAPK.net', description: 'Read what information ShreeWinAPK.net may process, what account details it does not collect and how external links affect your privacy.', eyebrow: 'Website privacy information', h1: 'Privacy Policy', intro: 'This Privacy Policy explains how ShreeWinAPK.net handles website information. It does not cover the separate ShreeWin platform opened through external Login or Register links.',
    sections: [
      { heading: 'Information this website does not request', paragraphs: ['Do not enter or send a ShreeWin password, OTP, withdrawal password, UPI PIN, bank PIN, card credential or account recovery code to this website. ShreeWinAPK.net does not provide a platform login or registration form.', 'The website also does not process a deposit or withdrawal. Information entered on an external service is controlled by that service and its own privacy terms.'] },
      { heading: 'Technical information used to provide the website', paragraphs: ['The hosting service may process standard technical data such as IP address, browser type, device type, requested page, date, time and security logs. This information can be used to deliver pages, prevent abuse and investigate technical problems.', 'The exact hosting-log retention period and processing locations are [VERIFY BEFORE PUBLISHING]. This policy should be checked against the active hosting setup before legal publication.'] },
      { heading: 'Cookies and analytics', paragraphs: ['No analytics or advertising provider should be named unless it is actually installed. Current cookie, analytics and consent settings are [VERIFY BEFORE PUBLISHING].', 'If analytics, advertising or a consent tool is added later, this policy must be updated before the new technology is used. Visitors should be told what data is collected and why.'] },
      { heading: 'Contact messages and retention', paragraphs: ['No public contact form is currently active. If one is added, it should ask only for name, email and message and should include spam protection. The form must not request platform credentials or payment PINs.', 'The retention period, privacy-contact address and deletion-request process are [VERIFY BEFORE PUBLISHING]. Keep contact data only for as long as it is needed for the stated purpose or required by law.'] },
      { heading: 'External links and legal review', paragraphs: ['Login and Register buttons open a separately operated website. Check its address and privacy policy before you submit personal information. ShreeWinAPK.net does not control how an external service uses data.', 'This policy is general website information and is not legal advice. It needs review by a qualified legal professional before being treated as a final legal document.'] },
    ], related: [{ label: 'Terms', href: '/terms' }, { label: 'Contact', href: '/contact' }, { label: 'Disclaimer', href: '/disclaimer' }],
  },

  terms: {
    slug: 'terms', title: 'Terms of Use | ShreeWinAPK.net', description: 'Read the terms for using ShreeWinAPK.net, including its independent status, external links, content limits and responsible-use conditions.', eyebrow: 'Website use terms', h1: 'Terms of Use', intro: 'These Terms apply to your use of ShreeWinAPK.net as an independent information website. They do not replace the separate terms of the external ShreeWin platform.',
    sections: [
      { heading: 'Informational purpose', paragraphs: ['The website explains supplied interface screens, Android installation steps, account processes, visible game names and general safety points. It does not operate ShreeWin games or accounts and does not provide personal financial, legal or security advice.', 'You are responsible for checking current platform rules, age requirements, local laws and financial risk before using an external service.'] },
      { heading: 'Accuracy and changing information', paragraphs: ['We try to separate confirmed information from details that still need verification. App versions, file URLs, game rules, promotions, payment methods and limits can change after a page is published.', 'No promise is made that every product detail is always current. Check important information on the live platform before you make an account or payment decision.'] },
      { heading: 'External links and services', paragraphs: ['Login and Register buttons lead to a separately operated website. ShreeWinAPK.net does not control its availability, accounts, games, promotions, payments, support decisions or privacy practices.', 'Opening an external link does not create an ownership claim, official partnership or guarantee. Read the external service terms before you enter information.'] },
      { heading: 'Acceptable website use', paragraphs: ['Do not use this website to impersonate another person, spread malware, attempt unauthorised access, scrape personal data or submit another user’s sensitive information. Do not misuse content to promote a fixed game or guaranteed income claim.', 'Website content may be updated or removed when it is incorrect, unsafe or no longer useful. Any formal copyright and content-licence terms are [VERIFY BEFORE PUBLISHING].'] },
      { heading: 'Legal review needed', paragraphs: ['Governing law, dispute process, limitation of liability, contact details and effective date are [VERIFY BEFORE PUBLISHING]. These terms preserve the existing independent-information meaning but are not final legal advice.', 'A qualified legal professional should review this page before it is treated as the final Terms of Use.'] },
    ], related: [{ label: 'Disclaimer', href: '/disclaimer' }, { label: 'Privacy policy', href: '/privacy-policy' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  disclaimer: {
    slug: 'disclaimer', title: 'Independent Website Disclaimer | ShreeWinAPK.net', description: 'Read the independent-site, external-link, information-accuracy and gaming-risk disclaimer for ShreeWinAPK.net.', eyebrow: 'Important website disclosure', h1: 'Independent Website Disclaimer', intro: 'ShreeWinAPK.net is an independent information website. It does not claim to own, operate or officially represent the ShreeWin platform.',
    sections: [
      { heading: 'Independent status', paragraphs: ['ShreeWin names, interface images and game names are used to identify and explain the platform covered by the guides. ShreeWinAPK.net does not operate accounts, games, promotions, deposits, withdrawals or customer-support decisions.', 'Login and Register buttons open the external destination configured for this website. Visitors should check that destination and its current terms before taking action.'] },
      { heading: 'Information may change', paragraphs: ['Screenshots and supplied facts show the information available when the page was prepared. Game listings, interface labels, payment options, limits, promotion terms and support routes may later change.', 'Unverified APK version, file size, source, game mechanics and support timings are not presented as confirmed facts. Items marked [VERIFY BEFORE PUBLISHING] need a current source check.'] },
      { heading: 'No winning or income guarantee', paragraphs: ['Nothing on this website guarantees a win, payout, bonus, account approval, commission, salary or income. A guide, previous result or promotional offer cannot remove the possibility of financial loss.', 'Do not treat website content as a request to deposit or as a method to recover losses. Set limits and never use borrowed money for gaming.'] },
      { heading: 'Age, location and legal responsibility', paragraphs: ['Users must be 18+ and must check the laws that apply in their state or location. A website or app being accessible on a phone does not prove that paid participation is allowed everywhere.', 'This disclaimer provides general information and is not legal or financial advice. Applicable law, liability wording and publication details need professional legal review before final use.'] },
    ], related: [{ label: 'About this site', href: '/about' }, { label: 'Terms', href: '/terms' }, { label: 'Responsible gaming', href: '/responsible-gaming' }],
  },

  'responsible-gaming': {
    slug: 'responsible-gaming', title: 'Responsible Gaming: Limits, Risk & 18+ Guidance', description: 'Read clear responsible-gaming guidance about 18+ access, financial loss, time and spending limits, breaks and chasing losses.', eyebrow: 'Play within clear limits', h1: 'Responsible Gaming Guide', intro: 'Gaming with paid entries can cause financial loss. No game, bonus or strategy can guarantee a win. This website is intended only for users aged 18 and above.',
    sections: [
      { heading: 'Only for users aged 18+', paragraphs: ['Do not create or use a paid gaming account if you are under 18. Age requirements and gaming laws can differ by state and location. Check the rules that apply where you live.', 'Do not use another person’s identity or payment account to avoid an age or location check. Account availability does not prove that participation is legal in every place.'] },
      { heading: 'Set a spending limit', paragraphs: ['Decide the maximum amount you can afford to lose before you start. Use only money left after rent, food, education, healthcare, bills, savings and debt payments. Treat the limit as final.', 'Never borrow money or use household funds for gaming. Keep a simple record of deposits, withdrawals and total spending so you can see the real result.'], bullets: ['Use only an amount you can afford to lose', 'Set a daily or weekly spending limit', 'Keep household money separate', 'Never borrow to play', 'Review your transaction record'] },
      { heading: 'Set a time limit and take breaks', paragraphs: ['Choose a fixed time to stop before you open a game. Use a phone alarm if needed. Take regular breaks and do not continue late at night because you feel one more round will change the result.', 'Stop for the day if gaming affects sleep, work, study, relationships or mood. A break is more useful than making quick decisions while angry or worried.'] },
      { heading: 'Never chase a loss', paragraphs: ['Chasing a loss means spending more because you want to recover an earlier loss. It can increase harm quickly. A previous result does not make the next result more likely to help you.', 'Ignore “fixed game”, “sure-shot trick”, “100% winning strategy” and guaranteed-profit claims. Do not pay for prediction groups, bots or account-control services.'] },
      { heading: 'Use account controls when available', paragraphs: ['Look for deposit limits, time reminders, cooling-off, account closure or self-exclusion inside Account or Settings. The specific ShreeWin control options are [VERIFY BEFORE PUBLISHING].', 'If you want to stop, contact a verified support channel and ask what restriction or closure options are available. Keep the request reference and do not share your password or OTP.'] },
      { heading: 'When to seek help', paragraphs: ['Stop and speak to someone you trust if gaming causes debt, stress, secrecy, arguments or repeated failed attempts to stop. Consider help from a qualified mental-health, financial-counselling or gambling-support service in your location.', 'India-specific support contacts and any platform self-exclusion process are [VERIFY BEFORE PUBLISHING]. If there is an immediate risk to your safety, contact local emergency support.'] },
    ], related: [{ label: 'Disclaimer', href: '/disclaimer' }, { label: 'Games overview', href: '/shree-win-games' }, { label: 'Promotion guide', href: '/shree-win-promotion' }],
  },
};
