export type GuideSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type GuideContent = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  intro: string;
  sections: GuideSection[];
  related: { label: string; href: string }[];
  cta?: 'login' | 'register' | 'visit';
};

export const guidePages: Record<string, GuideContent> = {
  'shree-win-apk': {
    slug: 'shree-win-apk', title: 'ShreeWin APK: App Features, Access & Android Guide', description: 'Learn what the ShreeWin APK is, what the mobile app shows, which details need checking and how to use an Android APK carefully.', eyebrow: 'ShreeWin app information', h1: 'ShreeWin APK and Mobile App Guide', intro: 'ShreeWin APK is the Android installation file for the ShreeWin app. Learn what the app includes and what you should check before downloading or installing it.', cta: 'visit',
    sections: [
      { heading: 'What is the ShreeWin APK?', paragraphs: ['APK stands for Android Package Kit. It is the file used to install an app on an Android phone without the Play Store. People search for ShreeWin APK when they want to install the Android app or check its features first.', 'Download the APK only from the ShreeWin download page. ShreeWinAPK.net does not host the app file, so tap Visit ShreeWin to check the latest download option.'] },
      { heading: 'What you can see inside the app', paragraphs: ['ShreeWin has five main tabs: Lobby, Lottery, Popular, Mini Game and Casino. Open Lottery to find TRX WinGo and MotoRace. The game list also includes WinGo, K3, 5D and Aviator.', 'Use the bottom menu to open Home, Activity, Promotion or Account. Login and Register are available from the account screens. The order and artwork may change after an app update.'], bullets: ['Lobby and category navigation', 'Lottery, Popular, Mini Game and Casino tabs', 'TRX WinGo and MotoRace entries', 'Home, Activity, Promotion and Account menu', 'Phone or email account access'] },
      { heading: 'Mobile web access and the Android app', paragraphs: ['ShreeWin can be opened from a mobile browser, while the APK installs the app on an Android phone. Browser access does not need an installation file. The APK creates an app icon and may ask for Android permissions during setup.', 'Use the option that fits your phone. If you only want to review the account page or available categories, mobile web access may be enough. If you install the APK, keep the original download page saved so you can return for a future update.'] },
      { heading: 'Details to check before installation', paragraphs: ['Check the app name, download website, version, file size and permissions before you install it. Android may show a warning when you install an app from a browser. Read that warning before you continue.', 'Match the version and file size with the details shown on the download page. If a checksum is available, use it to check that the downloaded file has not been changed.'], bullets: ['App name and logo', 'Version and release date', 'File size', 'Download website', 'App permissions'] },
      { heading: 'Account and phone safety', paragraphs: ['Check the app name before installation. Cancel the process if it asks you to switch off phone security, install another unknown app or allow a permission that the app does not need.', 'Never share your password, OTP, UPI PIN, bank PIN or withdrawal password. This website does not ask for ShreeWin login details and cannot open or recover your account.'] },
    ], related: [{ label: 'APK download guide', href: '/shree-win-download/' }, { label: 'Games overview', href: '/shree-win-games/' }, { label: 'Login guide', href: '/shree-win-login/' }],
  },

  'shree-win-download': {
    slug: 'shree-win-download', title: 'ShreeWin App Download: Android APK Installation Guide', description: 'Follow simple ShreeWin app download and Android installation steps, check APK permissions and fix common download problems safely.', eyebrow: 'Android download help', h1: 'ShreeWin App Download and Installation Guide', intro: 'Open the ShreeWin download page and check the website address before you download the APK. Follow these steps to install the app on an Android phone.', cta: 'visit',
    sections: [
      { heading: 'Before you download the ShreeWin APK', paragraphs: ['Read the website address carefully before you tap a download button. Avoid APK links received from unknown WhatsApp, Telegram, SMS or email accounts. A copied logo does not prove that a file belongs to ShreeWin.', 'Keep Google Play Protect and your phone security turned on. Do not download modified, cracked or “unlimited balance” files. Such files may contain malware or may try to steal account information.'], bullets: ['Check the complete website address', 'Avoid modified or cracked APK files', 'Keep Android security enabled', 'Check available phone storage', 'Use a stable mobile data or Wi-Fi connection'] },
      { heading: 'How to install an APK on Android', paragraphs: ['Download the APK from the ShreeWin page you opened yourself. Open the file from your browser or Downloads folder. Android may ask for permission to install apps from that browser. Allow it for the installation and turn it off later if you do not need it.', 'Check the app name and permissions before you tap Install. After installation, open the app from your phone menu. Enter your login details only inside the ShreeWin app or login page.'], bullets: ['Open the ShreeWin download page', 'Download the APK file', 'Read the Android warning', 'Allow installation from the selected browser', 'Check permissions and tap Install', 'Open the app from your phone menu'] },
      { heading: 'How to update the app', paragraphs: ['Use the update option shown inside ShreeWin or return to the same download page used for the first installation. Do not install an update sent by an unknown person. Check that the app name and permissions match the existing installation.', 'Compare the version and release date shown on the download page with the app already installed on your phone. Keep your login details ready before replacing an older version.'] },
      { heading: 'Fix download and installation problems', paragraphs: ['If the download stops, check your internet connection and free storage, then start it again from the same source. If Android says the file cannot be opened, the download may be incomplete or the file may not be a valid APK.', 'If installation is blocked, read the exact Android message. Do not switch off every security setting. If the app asks for unrelated permissions or shows a different name, cancel the installation and verify the file.'] },
      { heading: 'Check the file before installation', paragraphs: ['Check the APK version, file size, release date and download website before installation. The Visit Shree Win button takes you to the ShreeWin page, where you can check the latest download option.'] },
    ], related: [{ label: 'What is Shree Win APK?', href: '/shree-win-apk/' }, { label: 'Login guide', href: '/shree-win-login/' }, { label: 'Privacy policy', href: '/privacy-policy/' }],
  },

  'shree-win-login': {
    slug: 'shree-win-login', title: 'ShreeWin Login: Phone, Email & Password Help', description: 'Learn the ShreeWin login steps for phone or email, reset a forgotten password and fix OTP, password or account-access problems.', eyebrow: 'Account access help', h1: 'ShreeWin Login Guide', intro: 'To complete the ShreeWin login, open the login page and choose Phone Number or Email. Enter the details linked to your account, check them once and then tap Login.', cta: 'login',
    sections: [
      { heading: 'Details needed for ShreeWin login', paragraphs: ['You can log in with your registered phone number or email address. For phone login, select the correct country code and enter your mobile number and password. For email login, enter the email address linked to your account and your password.', 'Use the same method you selected during registration. ShreeWinAPK.net does not ask you to enter your login details on this page.'] },
      { heading: 'ShreeWin login steps', paragraphs: ['Tap Login on this website. The ShreeWin login page has Phone Number and Email tabs. Choose the method linked to your account, enter your details, check for typing mistakes and tap Login.', 'If you use a shared phone, do not select Remember Password. Log out after use and remove any saved password from the browser.'], bullets: ['Open the login page', 'Choose Phone Number or Email', 'Enter your registered details', 'Check the country code and spelling', 'Complete the OTP step if asked', 'Tap Login'] },
      { heading: 'Forgotten password and OTP problems', paragraphs: ['Tap Forgot Password and choose phone reset. Enter your registered mobile number, create a new password, confirm it and enter the verification code sent to you. Type the code only on the ShreeWin reset page.', 'If the OTP does not arrive, check the mobile number and country code, wait for the resend button and make sure your phone can receive SMS. Do not request many codes at the same time.'] },
      { heading: 'Incorrect password or locked account', paragraphs: ['Check for capital letters, extra spaces or an old saved password. Use Forgot Password instead of trying many passwords again and again.', 'If recovery does not work, open the customer-support button in Settings. Share your user ID and the error message, but never share your password, OTP, UPI PIN or withdrawal password.'] },
      { heading: 'Login page opens but the account does not load', paragraphs: ['If the Login button works but the next screen stays blank, first change between mobile data and Wi-Fi and reload the page once. Close old ShreeWin tabs so that you do not continue through an expired session.', 'If the problem continues, note the time, browser name and exact message on the screen. Customer Support can use these details to separate a password problem from a page-loading or account-status problem.'] },
      { heading: 'Keep your account access private', paragraphs: ['Use a different password from your email, bank and UPI apps. Do not give remote screen access to a person claiming they can fix your login. Check the web address before you enter any credential.', 'For account help, use the customer-support button in Settings. ShreeWinAPK.net cannot unlock or recover a ShreeWin account.'] },
    ], related: [{ label: 'Registration guide', href: '/shree-win-register/' }, { label: 'APK guide', href: '/shree-win-apk/' }, { label: 'Contact information', href: '/contact/' }],
  },

  'shree-win-register': {
    slug: 'shree-win-register', title: 'ShreeWin Register: Phone, Email & Invite Code Guide', description: 'Follow the ShreeWin registration steps using a phone number or email, create a password and understand invite-code and OTP checks.', eyebrow: 'New account help', h1: 'How to Register on ShreeWin', intro: 'The ShreeWin registration screen provides phone and email options. Choose one method, enter your own details, create a strong password and check every field before you tap Register.', cta: 'register',
    sections: [
      { heading: 'Phone and email registration options', paragraphs: ['For phone registration, select the country code and enter your mobile number, password, password confirmation and invitation code. For email registration, enter your email address, password, password confirmation and invitation code.', 'Use a phone number or email address that belongs to you. Complete the OTP or email check shown during registration.'] },
      { heading: 'Step-by-step ShreeWin registration', paragraphs: ['Tap Register on this website. Choose phone or email, enter your details and create a password that you do not use on another account.', 'Read the Privacy Agreement, check the invitation code and complete the OTP or email step. Do not share the code with another person.'], bullets: ['Open the registration page', 'Choose phone or email', 'Enter your own details', 'Create and confirm a strong password', 'Check the invitation code', 'Complete the OTP or email step'] },
      { heading: 'Use the ShreeWin invitation code', paragraphs: ['Tap Register on this website and check that the VIP invitation code is visible in the form. Eligible new users who register with this code can receive a ₹100 invite bonus.', 'The registration page shows the offer rules and any extra VIP perks. Read them before you submit because the invite code is linked to your account during registration.'] },
      { heading: 'Fix common registration errors', paragraphs: ['If the mobile number is rejected, check the country code and number length. If the email is rejected, remove spaces and check the spelling. Your password and confirmation must match exactly.', 'If an OTP is delayed, wait for the resend option and check network or SMS blocking. If the page says the account already exists, use the login or password-recovery page instead of creating repeated accounts.'] },
      { heading: 'Review the form before you submit', paragraphs: ['Read the phone number or email, password confirmation and invitation-code fields one final time. A typing mistake in the account detail can make password recovery difficult later.', 'Keep a private note of the login method you selected, but never save the password in a public screenshot or chat. After registration, use the same phone or email option on the Login page.'] },
      { heading: 'Registration safety', paragraphs: ['Never pay a stranger to create an account for you. Do not share your password, OTP, UPI PIN, banking PIN or identity document in a chat. Use your own phone and check the website address.', 'ShreeWinAPK.net does not collect registration details. You must be 18+ and should check the laws that apply where you live.'] },
    ], related: [{ label: 'Login guide', href: '/shree-win-login/' }, { label: 'Privacy policy', href: '/privacy-policy/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  'shree-win-games': {
    slug: 'shree-win-games', title: 'ShreeWin Games: WinGo, K3, 5D, Aviator & Lottery', description: 'Explore ShreeWin games and categories, including WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace, with clear screen and rule information.', eyebrow: 'ShreeWin game information', h1: 'ShreeWin Games and Categories', intro: 'Browse ShreeWin games through Lobby, Lottery, Popular, Mini Game and Casino. Find WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace, and learn what to check on each game screen.',
    sections: [
      { heading: 'Main game categories', paragraphs: ['Lobby is the main view where you can browse available content. Lottery, Popular, Mini Game and Casino organise the game cards into separate groups, making it easier to move between different types of play.', 'The available list and card order may change after an app update. Open the current category tab to see the games available on your account.'], bullets: ['Lobby', 'Lottery', 'Popular', 'Mini Game', 'Casino'] },
      { heading: 'WinGo colour and number game', paragraphs: ['WinGo is a colour and number game available in the ShreeWin app. Before you join a round, check the selected period, available choices, countdown and result history shown on the game screen.', 'Tap Rules to see the available periods, entry limits and result table. Check your selection and amount before you confirm.'] },
      { heading: 'K3 and 5D games', paragraphs: ['K3 and 5D are number-style games available in ShreeWin. Open the game you want and check its period, number choices, entry panel and result section.', 'Tap Help or Rules to see the available round times, entry amounts and complete game rules. Read them before you confirm an entry.'] },
      { heading: 'Aviator', paragraphs: ['Aviator is a crash-style game available in the game list. Open it to view the active round, entry buttons and on-screen value.', 'Read the Help or Rules section for the round time, available entries and result process. Rules on another app may be different, so use the information shown inside ShreeWin.'] },
      { heading: 'TRX WinGo and MotoRace', paragraphs: ['TRX WinGo and MotoRace appear in the Lottery section. Open their cards from the category row on the ShreeWin homepage. The separate guides explain how to find each game and read its round screen.', 'Check the selected period, available choices, entry amount and result rules inside the game before you continue.'] },
      { heading: 'Common game-screen terms', paragraphs: ['Period or round identifies one game cycle. Countdown shows how much time remains before that cycle closes. Result History lists completed periods, while Transaction or Game History shows the record connected with your account.', 'Use the period number to match a result with the correct entry. The same game name can have different periods or entry options, so read the labels on the active screen instead of relying on an older screenshot.'], bullets: ['Period or round number', 'Countdown and closing time', 'Selected choice', 'Entry amount', 'Result History', 'Account transaction record'] },
      { heading: 'What to check on every game screen', paragraphs: ['Check the selected game name, round period, countdown, available choices, entry amount and result history before you tap Confirm. Make sure the round is still open and review any rule that affects settlement.', 'Use a fixed time and spending limit for paid play. Users must be 18+ and should check the laws that apply in their state or location.'], bullets: ['Game name and selected period', 'Round countdown', 'Available choices', 'Entry amount', 'Result and transaction record', 'Current game rules'] },
    ], related: [{ label: 'Lottery guide', href: '/shree-win-lottery/' }, { label: 'TRX WinGo guide', href: '/trx-wingo/' }, { label: 'MotoRace guide', href: '/motorace/' }],
  },

  'shree-win-lottery': {
    slug: 'shree-win-lottery', title: 'ShreeWin Lottery: TRX WinGo & MotoRace Guide', description: 'Learn how to open the ShreeWin Lottery section, find TRX WinGo and MotoRace, and check round, entry and result details.', eyebrow: 'Lottery game information', h1: 'ShreeWin Lottery Guide', intro: 'Open Lottery from the main ShreeWin game menu to find TRX WinGo and MotoRace. Each game has its own round screen, choices and result history.',
    sections: [
      { heading: 'How to open the Lottery section', paragraphs: ['Open the ShreeWin homepage and look at the category row near the top. Tap Lottery to see the current lottery game cards. This section is separate from Popular, Mini Game and Casino.', 'The order and artwork can change after an app update. Use the live category page to see the current listing.'] },
      { heading: 'Games available in Lottery', paragraphs: ['The Lottery section includes TRX WinGo and MotoRace. Tap the game card you want to open and check the active round details before selecting an entry.', 'Use the full Lottery list to check whether more games have been added to your account.'], bullets: ['TRX WinGo', 'MotoRace'] },
      { heading: 'How to read a round screen', paragraphs: ['Check the game name and selected period first. Read the countdown, available choices and confirmation details before you submit. After the round closes, use Result or History to check the outcome.', 'Tap Help or Rules to see the available periods, entry limits, closing rules and result table for that game.'] },
      { heading: 'Keep Lottery records organised', paragraphs: ['Save the period number and account transaction reference together when you need to review an entry. A screenshot of only the result may not show which account record or period you are asking about.', 'For support, send the game name, period, date, time and transaction reference in one message. This gives the support team the useful details without exposing your password, OTP or payment PIN.'] },
      { heading: 'Result and transaction checks', paragraphs: ['If a result or balance is not updated, refresh the game page and check Game History or Transaction. Keep the round number and entry reference before you contact Customer Support.', 'Set an amount and time limit before you play. Do not share your password, OTP, UPI PIN or withdrawal password when asking about a game record.'] },
    ], related: [{ label: 'TRX WinGo', href: '/trx-wingo/' }, { label: 'MotoRace', href: '/motorace/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  'trx-wingo': {
    slug: 'trx-wingo', title: 'ShreeWin TRX WinGo: Access, Round & Result Guide', description: 'Find TRX WinGo in the ShreeWin Lottery section and learn how to check the period, countdown, entry choices and result record.', eyebrow: 'TRX WinGo information', h1: 'ShreeWin TRX WinGo Guide', intro: 'Open the Lottery section to find TRX WinGo. Check the active period, countdown, available choices and result history before you join a round.',
    sections: [
      { heading: 'How to find TRX WinGo', paragraphs: ['Open the ShreeWin homepage and tap Lottery in the main category row. Look for the TRX WinGo card and open it. MotoRace appears in the same section.', 'If the card position has changed, check the full Lottery list. Open the game from ShreeWin instead of a similarly named third-party page.'] },
      { heading: 'Check the selected period and countdown', paragraphs: ['When the game opens, confirm which period or round is active. Check the countdown before selecting an option because an entry submitted after the closing point may not be accepted.', 'Tap Rules to see every available period and how late entries are handled. Read these details before you start.'] },
      { heading: 'Review entry choices before confirmation', paragraphs: ['Read every available choice and the amount shown in the entry panel. Check the selected option again before you tap Confirm. Keep the round number so you can match the entry with the displayed result later.', 'The game screen shows the available entry range, choice types and result values. Check them each time because they may differ by period.'] },
      { heading: 'How results are shown', paragraphs: ['After a round ends, open Result or History and match the period number with your entry record. If the result is not visible, refresh the page and check again after the round is updated.', 'For a result or balance issue, save the period number, transaction reference, date, time and a clear screenshot. Send these details through the support button in Settings without sharing a password, OTP or payment PIN.'] },
      { heading: 'Use the rules shown inside TRX WinGo', paragraphs: ['TRX WinGo has its own Rules or Help section. Use that screen for the current periods, choices, settlement details and result process. Rules copied from another WinGo page may not match the version open in your account.', 'The name TRX WinGo does not replace the live rule table. Read the selected period and confirmation summary each time before you submit an entry.'] },
      { heading: 'Use clear play limits', paragraphs: ['Set the maximum time and amount you plan to use before opening a paid round. Stop when your limit is reached and do not use money needed for bills or household costs.', 'No result can be promised in advance. Users must be 18+ and should check the gaming rules that apply in their location.'] },
    ], related: [{ label: 'Lottery category', href: '/shree-win-lottery/' }, { label: 'MotoRace guide', href: '/motorace/' }, { label: 'Games overview', href: '/shree-win-games/' }],
  },

  motorace: {
    slug: 'motorace', title: 'ShreeWin MotoRace: Access, Round & Result Guide', description: 'Learn where MotoRace appears in ShreeWin and how to check its current round, entry options, countdown and result record.', eyebrow: 'MotoRace information', h1: 'ShreeWin MotoRace Guide', intro: 'Find MotoRace in the ShreeWin Lottery section. Open the game to check the active period, countdown, available choices and result history.',
    sections: [
      { heading: 'How to open MotoRace', paragraphs: ['Open the ShreeWin homepage, tap Lottery and look for the MotoRace card near TRX WinGo. Tap the card to open the game page.', 'If the card position has changed, check the full Lottery list in the app.'] },
      { heading: 'Read the active round details', paragraphs: ['Check the selected round or period and the countdown shown on the game screen. Review the available choices and understand the confirmation step before submitting an entry.', 'Tap Help or Rules to see the MotoRace periods, choice types, entry limits and closing rules.'] },
      { heading: 'MotoRace screen checklist', paragraphs: ['Start with the game name and active period, then read the countdown and every choice displayed for that round. The confirmation panel should show the choice and entry amount you selected.', 'After the period closes, use Result or Game History to match the period number. Do not use an earlier result as the rule for a new round; the current Rules screen is the correct reference.'], bullets: ['MotoRace game name', 'Active period', 'Countdown', 'Selected choice', 'Entry amount', 'Result record'] },
      { heading: 'Check the result and history', paragraphs: ['When a round is complete, match its period number with the result shown in Game History. Also check your entry or transaction record so you are looking at the correct round.', 'If a record remains pending, refresh the page and wait for an update. Save the round number, date, time and screenshot before using the support button in Settings.'] },
      { heading: 'Account and play safety', paragraphs: ['Keep your password, OTP, UPI PIN and withdrawal password private. Customer Support can check a round using its reference number without these secret details.', 'Choose your time and amount limits before joining a paid round. You must be 18+ and follow the gaming rules in your area.'] },
    ], related: [{ label: 'Lottery category', href: '/shree-win-lottery/' }, { label: 'TRX WinGo guide', href: '/trx-wingo/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  'shree-win-withdrawal': {
    slug: 'shree-win-withdrawal', title: 'ShreeWin Withdrawal: UPI, Bank & USDT Help', description: 'Learn the ShreeWin withdrawal steps, add UPI or bank details, check stated limits and fix a pending or failed withdrawal safely.', eyebrow: 'Withdrawal help', h1: 'ShreeWin Withdrawal Guide', intro: 'To submit a ShreeWin withdrawal, open Wallet, choose Withdrawal, select an available method and enter the required amount. Check your receiving details carefully before you confirm.',
    sections: [
      { heading: 'Check withdrawal requirements', paragraphs: ['Your account may need phone, identity, bank or payment verification before you can withdraw. A promotion may also have a turnover condition. Turnover is the valid game activity needed before a bonus can be withdrawn.', 'Open Withdrawal and Promotion to check the account rules, maximum limit and any fee shown for your selected method.'] },
      { heading: 'Add a bank account or UPI ID', paragraphs: ['Open Account or Wallet and look for bank-account or withdrawal settings. Enter the account-holder name, bank name, account number and IFSC code exactly as shown in your bank records. For UPI, enter your complete UPI ID and check the spelling.', 'The name should match the details registered on your account. Complete the OTP check inside ShreeWin. Never share your OTP, UPI PIN, bank PIN, card PIN or banking password with support.'] },
      { heading: 'Withdrawal methods and minimum amounts', paragraphs: ['UPI and bank withdrawals start from ₹100. USDT withdrawals start from ₹1,000. The Withdrawal screen shows the limit available for your account when you select a method.', 'For USDT, check the wallet address and network character by character. A wrong address or network can cause permanent loss. Also check the network fee and final amount before you confirm.'], bullets: ['UPI — minimum ₹100', 'Bank transfer — minimum ₹100', 'USDT — minimum ₹1,000'] },
      { heading: 'How to submit a withdrawal', paragraphs: ['Choose the receiving account, enter an amount within the current limit and review all details. Read any turnover, fee or verification message before you tap Confirm. Save the request or transaction reference shown after submission.', 'Do not pay an advance fee to a person who says they can release the withdrawal. Never allow remote screen access to your phone for payment help.'], bullets: ['Open Wallet and tap Withdrawal', 'Choose UPI, bank or USDT if available', 'Select or add the receiving details', 'Enter and check the amount', 'Read conditions and tap Confirm', 'Save the transaction reference'] },
      { heading: 'Processing time and pending withdrawal', paragraphs: ['UPI and bank withdrawals are normally processed within 30 minutes. USDT withdrawals are processed instantly in normal conditions. Account checks, turnover rules, bank delays, network traffic or incorrect details can take extra time.', 'If a request is pending, check Wallet or Transaction. Wait for the normal processing time, then open Customer Support in Settings. Share your user ID, amount, date, time, method, status screenshot and transaction reference.'] },
      { heading: 'Failed withdrawal and support', paragraphs: ['Check your receiving details, minimum amount, account verification and turnover conditions. Do not keep sending the same request when the first one is still pending.', 'Open the customer-support button in Settings and send the transaction details. Never share your password, OTP, withdrawal password, UPI PIN, bank PIN or recovery code.'] },
    ], related: [{ label: 'Account login guide', href: '/shree-win-login/' }, { label: 'Promotion rules', href: '/shree-win-promotion/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  'shree-win-agent': {
    slug: 'shree-win-agent', title: 'ShreeWin Agent: Invite, Team Levels & Commission Guide', description: 'Understand ShreeWin agent invitations, the six-level team structure, team records and commission conditions.', eyebrow: 'Agent and referral information', h1: 'ShreeWin Agent and Agency Guide', intro: 'ShreeWin Agent uses an invitation link and a six-level team system. Open Agency to check your team members, activity, level and commission record.',
    sections: [
      { heading: 'How the invitation link works', paragraphs: ['An agent shares the invitation link or code generated for the registration flow. The new user opens that link and checks that the invitation code is visible before submitting the form. The relationship is recorded during registration.', 'Eligible new users who register through the link on this website can receive a ₹100 invite bonus under the current offer. Bonus credit, VIP benefits and other game perks follow the terms shown on the live registration page.'], bullets: ['Open the shared Register link', 'Check the invitation code field', 'Read the current invite offer', 'Complete registration with your own details', 'Keep the password and OTP private'] },
      { heading: 'Six-level team structure', paragraphs: ['A person invited directly by you is level 1. If that person invites somebody else, the new account can be level 2 for you and level 1 for the direct inviter. This team structure continues through six levels.', 'Commission depends on the rules shown in Agency. Open your Agency page to check which team activity is included.'] },
      { heading: 'Team records and commission calculation', paragraphs: ['The Agency page shows team number, team activity, team deposits, agency level and commission records. Different game types can use different rates, so always open the rate table before checking a team record.', 'The commission page shows the activity needed, rate, collection time and withdrawal conditions. Agent commission depends on these rules and is not a fixed salary.'], bullets: ['Team number', 'Team activity', 'Team deposit record', 'Agency or rebate level', 'Game-specific rate', 'Commission collection record'] },
      { heading: 'Share your invite link correctly', paragraphs: ['Tell the new user that your link connects their account to your agent team. They can check the invite code in the registration form before submitting it.', 'Explain the ₹100 invite bonus and ask the user to read the offer terms on the registration page. Registration, deposit and game choices remain the user’s own decision.'] },
      { heading: 'Safe and responsible agent work', paragraphs: ['Never operate another person’s account or ask for their password, OTP, UPI PIN or withdrawal password. Do not impersonate customer support or ask someone to send funds to a personal payment ID.', 'Do not pressure a person to deposit, borrow money or chase a loss. Agent status does not remove age checks, local-law checks or responsible-gaming limits.'] },
    ], related: [{ label: 'Registration guide', href: '/shree-win-register/' }, { label: 'Promotion guide', href: '/shree-win-promotion/' }, { label: 'Withdrawal guide', href: '/shree-win-withdrawal/' }],
  },

  'shree-win-promotion': {
    slug: 'shree-win-promotion', title: 'ShreeWin Promotion: Bonus Rules & Activity Guide', description: 'Learn where ShreeWin promotions appear, how to check eligibility, first-deposit tiers, turnover rules and claim problems.', eyebrow: 'Promotion and activity help', h1: 'ShreeWin Promotion and Activity Guide', intro: 'The ShreeWin app has separate Activity and Promotion areas. Open the current offer and read its complete rules before you deposit or claim a reward.',
    sections: [
      { heading: 'Where to find promotions and activities', paragraphs: ['Use the bottom menu to open Activity or Promotion. Activity shows tasks and reward options. Promotion shows the offers available for your account.', 'Open an offer to check its date, account requirement, required action and claim button.'] },
      { heading: 'What appears in the Activity area', paragraphs: ['The Activity screen includes Activity Award, Super Jackpot, First Gift and Invite Wheel shortcuts. It also shows Gifts and Attendance Bonus cards. Open a card to read the eligibility, required action and collection steps for that activity.', 'These names describe separate activity areas, not one combined reward. A gift code, attendance reward, invite activity and first-deposit promotion can follow different account rules.'] , bullets: ['Activity Award', 'Super Jackpot', 'First Gift', 'Invite Wheel', 'Gifts', 'Attendance Bonus'] },
      { heading: 'First-deposit offer', paragraphs: ['The First Deposit Bonus page shows four one-time tiers: deposit ₹300 to receive ₹48, ₹500 to receive ₹108, ₹1,000 to receive ₹188, or ₹5,000 to receive ₹488. Each account can use this activity once.', 'Open the offer in your account before payment and read every condition shown there. Bonus amounts follow the promotion rules.'], bullets: ['Deposit ₹300 — bonus ₹48', 'Deposit ₹500 — bonus ₹108', 'Deposit ₹1,000 — bonus ₹188', 'Deposit ₹5,000 — bonus ₹488'] },
      { heading: 'Check the turnover rules', paragraphs: ['Read who can join, the campaign dates, required deposit, reward amount, claim button and account limits. Turnover is the valid game activity needed before some bonus amounts can be withdrawn.', 'The bonus has a one-time valid-bet or coding-turnover rule. Open the offer details to see which games count and how the requirement is calculated.'] },
      { heading: 'How to claim a promotion', paragraphs: ['Open the offer from Activity or Promotion and follow its steps. Complete the required action and tap Claim if that button is available. Save a screenshot of the offer rules and completed status.', 'For a deposit offer, use only the payment details shown after you tap Deposit in ShreeWin.'] },
      { heading: 'Promotion not received', paragraphs: ['Check whether the offer is active, whether your account meets its rules and whether the required transaction is complete. Also check if you need to tap Claim instead of waiting for the reward to be added automatically.', 'If the issue remains, open customer support in Settings. Share the offer name, date, amount, transaction reference and screenshots. Never share your password, OTP, UPI PIN or withdrawal password.'] },
    ], related: [{ label: 'Registration guide', href: '/shree-win-register/' }, { label: 'Disclaimer', href: '/disclaimer/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  blog: {
    slug: 'blog', title: 'ShreeWin Guides: App, Login, Games & Account Help', description: 'Browse focused ShreeWin guides for the APK, Android download, login, registration, games, Lottery, promotions and withdrawals.', eyebrow: 'ShreeWin information hub', h1: 'ShreeWin Guides and Help', intro: 'Choose the guide that matches your question. Each page focuses on one topic so you can find the required steps without reading unrelated information.',
    sections: [
      { heading: 'App and download guides', paragraphs: ['The APK guide explains what an Android APK is and what you can find in the ShreeWin app. The download guide covers Android installation, permissions, updates and common download errors.', 'Start with these pages if you want the Android app. The Visit ShreeWin button takes you to the current download page.'], bullets: ['ShreeWin APK and mobile app guide', 'ShreeWin Android download and installation guide'] },
      { heading: 'Account-access guides', paragraphs: ['The login page covers phone and email access, forgotten passwords, OTP delay and incorrect-password problems. The registration page covers new account fields, OTP checks, invitation codes and common errors.', 'ShreeWinAPK.net never asks you to submit a password or OTP. Login and Register buttons take you to the ShreeWin account page.'], bullets: ['ShreeWin login help', 'ShreeWin registration help'] },
      { heading: 'Game and Lottery guides', paragraphs: ['The games page covers the available categories and game names. The Lottery, TRX WinGo and MotoRace pages show where each game appears and how to read its round screen.', 'Check the selected period, choices, countdown and result history before you confirm an entry.'] },
      { heading: 'Promotion, withdrawal and agent guides', paragraphs: ['The promotion guide explains the displayed first-deposit tiers, eligibility checks and turnover terms. The withdrawal guide covers UPI, bank and USDT requests, receiving details and pending-request help.', 'The agent page explains invitation tracking, the ₹100 invite offer and the six-level team structure. Commission always follows current qualifying conditions.'] },
      { heading: 'Clear and useful information', paragraphs: ['Every guide focuses on the steps and screen details a user needs. We do not add guessed app versions, file sizes, player totals or game rules.', 'Pages are updated when new details are checked. Each guide keeps one clear topic so you can find the answer quickly.'] },
    ], related: [{ label: 'APK guide', href: '/shree-win-apk/' }, { label: 'Games directory', href: '/shree-win-games/' }, { label: 'Promotion guide', href: '/shree-win-promotion/' }],
  },

  about: {
    slug: 'about', title: 'About ShreeWinAPK.net | ShreeWin Guides', description: 'Learn what ShreeWinAPK.net provides and how our guides help ShreeWin users.', eyebrow: 'About this website', h1: 'About ShreeWinAPK.net', intro: 'ShreeWinAPK.net provides ShreeWin guides and account access links. It does not run ShreeWin games, accounts, deposits or withdrawals.',
    sections: [
      { heading: 'Why this website exists', paragraphs: ['This website explains the ShreeWin app, Android APK, account access, games, promotions, withdrawals and agent rules in clear language. The aim is to help Indian mobile users understand every step.', 'You can use the focused guides to find the right screen, follow a process and fix common problems without reading unrelated content.'] },
      { heading: 'How we keep information useful', paragraphs: ['We write from the features and screens available in ShreeWin. We do not add fake ratings, player numbers, APK versions, file sizes, support hours or winning percentages.', 'When a feature or rule changes, the related guide can be updated without copying the same paragraph across the website.'] },
      { heading: 'How guides are reviewed', paragraphs: ['Each guide is organised around the screen a user needs: account access, app installation, games, Wallet, Promotion or Agency. We compare headings, button names, fields and visible rules with the ShreeWin interface before publishing a product detail.', 'A review date appears on guide pages so readers can see when the information was last checked. If a version number, file size or payment rule is not available, we leave it out instead of guessing.'] },
      { heading: 'Corrections and updates', paragraphs: ['A platform screen can change after an app or promotion update. When a reader reports a different button, rule or screenshot, we review the relevant page and correct the specific section.', 'The Contact page explains how to report a broken link, outdated image or content error. Reports should include the guide URL and the exact detail that needs review.'] },
      { heading: 'What this website does not do', paragraphs: ['ShreeWinAPK.net does not run games, create ShreeWin accounts, process deposits or approve withdrawals. It also does not control game results or promotion claims.', 'We do not collect ShreeWin usernames, passwords, OTPs, withdrawal passwords, UPI PINs, bank PINs or card details. For account or payment help, open Customer Support in ShreeWin Settings.'] },
      { heading: 'Login and Register buttons', paragraphs: ['The Login and Register buttons take you to the ShreeWin account page. Check the website address and read the account terms before you enter personal information.', 'ShreeWinAPK.net provides guides and account links. Users must be 18+ and should follow the laws that apply in their location.'] },
    ], related: [{ label: 'Disclaimer', href: '/disclaimer/' }, { label: 'Privacy policy', href: '/privacy-policy/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  contact: {
    slug: 'contact', title: 'Contact ShreeWinAPK.net | Website & Account Help', description: 'Learn how to report a website issue, what details to send for account support and which private information you must never share.', eyebrow: 'Contact and support help', h1: 'Contact ShreeWinAPK.net', intro: 'Use this page to report a broken link, content problem or accessibility issue. For a ShreeWin account or payment problem, open the customer-support button in Settings.',
    sections: [
      { heading: 'Website issues you can report', paragraphs: ['You can report a broken page, wrong link, spelling mistake, outdated screenshot, accessibility issue or copyright concern. Include the page URL and explain what needs to be fixed.', 'A public email address and contact form are not available on this website yet.'], bullets: ['Broken page or internal link', 'Spelling or content correction', 'Outdated information', 'Accessibility problem', 'Copyright or brand concern'] },
      { heading: 'ShreeWin account and payment problems', paragraphs: ['ShreeWinAPK.net cannot reset your password, unlock your account, trace a deposit or approve a withdrawal. Open Customer Support in ShreeWin Settings for these problems.', 'Share your user ID, issue type, date, amount and transaction reference when needed. Hide private details in screenshots before you send them.'] },
      { heading: 'Information you must never share', paragraphs: ['Never send a password, OTP, withdrawal password, UPI PIN, bank PIN, card PIN, complete card number, account recovery code or remote-access code. Support should not need these details to read a complaint.', 'Do not send an identity document to an email address or chat account that you have not verified. Do not pay a person who asks for a fee to unlock support or release a payment.'] },
      { heading: 'If your complaint is not solved', paragraphs: ['Keep the complaint number, screenshots and transaction record. Reply through the same support option and ask for the matter to be reviewed again. Explain the problem and the help you need in one clear message.', 'For a bank, UPI or crypto-wallet issue, also use the complaint process provided by that payment service.'] },
    ], related: [{ label: 'Privacy policy', href: '/privacy-policy/' }, { label: 'Disclaimer', href: '/disclaimer/' }, { label: 'Login safety', href: '/shree-win-login/' }],
  },

  'privacy-policy': {
    slug: 'privacy-policy', title: 'Privacy Policy | ShreeWinAPK.net', description: 'Read what website data ShreeWinAPK.net may use and which account details we never collect.', eyebrow: 'Website privacy', h1: 'Privacy Policy', intro: 'This page explains how ShreeWinAPK.net handles website data. ShreeWin has its own privacy policy, which applies after you tap Login or Register.',
    sections: [
      { heading: 'Information this website does not request', paragraphs: ['Do not send your ShreeWin password, OTP, withdrawal password, UPI PIN, bank PIN, card details or recovery code to this website. ShreeWinAPK.net does not have a login or registration form.', 'This website also does not process deposits or withdrawals. Details entered after you leave this website follow the privacy rules of the site you open.'] },
      { heading: 'Basic website data', paragraphs: ['The hosting service may receive your IP address, browser type, device type, requested page, date and time when it sends a page to your phone. Security logs may also be used to block abuse and fix technical problems.', 'The hosting provider keeps this data under its own service and security policies.'] },
      { heading: 'Cookies and analytics', paragraphs: ['This policy will name an analytics or advertising service only when the website uses it. If a new cookie or tracking service is added, this page must explain what it collects and why.', 'You can control many cookies through your browser settings. Blocking some required cookies may affect how a website works.'] },
      { heading: 'Contact messages', paragraphs: ['No public contact form is active. If one is added later, it will ask only for your name, email and message and will include spam protection.', 'The form will not ask for a ShreeWin password, OTP, withdrawal password or payment PIN. Contact messages should be kept only as long as needed to answer the request or follow the law.'] },
      { heading: 'Login and Register links', paragraphs: ['Login and Register buttons take you to ShreeWin, which has its own privacy policy. Check the website address and read that policy before you submit personal information.', 'This policy gives general website information and is not legal advice. A legal professional should review it before final publication.'] },
    ], related: [{ label: 'Terms', href: '/terms/' }, { label: 'Contact', href: '/contact/' }, { label: 'Disclaimer', href: '/disclaimer/' }],
  },

  terms: {
    slug: 'terms', title: 'Terms of Use | ShreeWinAPK.net', description: 'Read the basic rules for using ShreeWinAPK.net, its guides and its Login and Register links.', eyebrow: 'Website terms', h1: 'Terms of Use', intro: 'These Terms apply when you use ShreeWinAPK.net. ShreeWin has separate account, game, payment and privacy terms.',
    sections: [
      { heading: 'How you may use the website', paragraphs: ['The website explains ShreeWin screens, Android installation, account steps, game names and safety points. It does not run ShreeWin games or accounts and does not give personal financial, legal or security advice.', 'You are responsible for checking the account rules, age limits, local laws and financial risk before you use ShreeWin.'] },
      { heading: 'Information can change', paragraphs: ['App versions, file links, game rules, promotions, payment methods and limits may change after a guide is written.', 'Check important account, payment and game details inside ShreeWin before you continue.'] },
      { heading: 'Login and Register links', paragraphs: ['Login and Register buttons take you to ShreeWin. ShreeWinAPK.net does not control its accounts, games, promotions, payments, support decisions or privacy rules.', 'Read the ShreeWin terms before you enter information or use an account feature.'] },
      { heading: 'Fair use of the website', paragraphs: ['Do not pretend to be another person, spread harmful files, try to enter a restricted area or send another user’s private information. Do not reuse our content to promote a fixed game or guaranteed income claim.', 'Website content may be corrected or removed when it is wrong, unsafe or no longer useful.'] },
      { heading: 'Legal notice', paragraphs: ['These Terms explain the basic rules for using ShreeWinAPK.net. They do not replace advice from a lawyer or the separate terms shown by ShreeWin.', 'A legal professional should review the governing-law, dispute and liability wording before this page is treated as a final legal document.'] },
    ], related: [{ label: 'Disclaimer', href: '/disclaimer/' }, { label: 'Privacy policy', href: '/privacy-policy/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  disclaimer: {
    slug: 'disclaimer', title: 'Website Disclaimer | ShreeWinAPK.net', description: 'Read what ShreeWinAPK.net provides, what it does not control and the risks users should understand.', eyebrow: 'Important information', h1: 'Website Disclaimer', intro: 'ShreeWinAPK.net provides ShreeWin guides and access links. It does not run ShreeWin games, accounts, payments, promotions or customer support.',
    sections: [
      { heading: 'About this website', paragraphs: ['We use the ShreeWin name, app images and game names to explain how ShreeWin works. ShreeWinAPK.net does not operate accounts, games, promotions, deposits, withdrawals or customer support.', 'The Login and Register buttons open ShreeWin. Check the website address and read its account terms before you continue.'] },
      { heading: 'Information may change', paragraphs: ['Screenshots show how ShreeWin looked when each guide was prepared. Game names, menu labels, payment options, limits, promotion terms and support buttons may change.', 'Check the app version, APK size, download link and game rules on the current ShreeWin page before you act.'] },
      { heading: 'No winning or income guarantee', paragraphs: ['Nothing on this website guarantees a win, payout, bonus, account approval, commission, salary or income. A guide, previous result or promotional offer cannot remove the possibility of financial loss.', 'Do not treat website content as a request to deposit or as a method to recover losses. Set limits and never use borrowed money for gaming.'] },
      { heading: 'Age, location and legal responsibility', paragraphs: ['Users must be 18+ and must check the laws that apply in their state or location. A website or app being accessible on a phone does not prove that paid participation is allowed everywhere.', 'This disclaimer provides general information and is not legal or financial advice. Applicable law, liability wording and publication details need professional legal review before final use.'] },
    ], related: [{ label: 'About this site', href: '/about/' }, { label: 'Terms', href: '/terms/' }, { label: 'Responsible gaming', href: '/responsible-gaming/' }],
  },

  'responsible-gaming': {
    slug: 'responsible-gaming', title: 'Responsible Gaming: Limits, Risk & 18+ Guidance', description: 'Read clear responsible-gaming guidance about 18+ access, financial loss, time and spending limits, breaks and chasing losses.', eyebrow: 'Play within clear limits', h1: 'Responsible Gaming Guide', intro: 'Gaming with paid entries can cause financial loss. No game, bonus or strategy can guarantee a win. This website is intended only for users aged 18 and above.',
    sections: [
      { heading: 'Only for users aged 18+', paragraphs: ['Do not create or use a paid gaming account if you are under 18. Age requirements and gaming laws can differ by state and location. Check the rules that apply where you live.', 'Do not use another person’s identity or payment account to avoid an age or location check. Account availability does not prove that participation is legal in every place.'] },
      { heading: 'Set a spending limit', paragraphs: ['Decide the maximum amount you can afford to lose before you start. Use only money left after rent, food, education, healthcare, bills, savings and debt payments. Treat the limit as final.', 'Never borrow money or use household funds for gaming. Keep a simple record of deposits, withdrawals and total spending so you can see the real result.'], bullets: ['Use only an amount you can afford to lose', 'Set a daily or weekly spending limit', 'Keep household money separate', 'Never borrow to play', 'Review your transaction record'] },
      { heading: 'Set a time limit and take breaks', paragraphs: ['Choose a fixed time to stop before you open a game. Use a phone alarm if needed. Take regular breaks and do not continue late at night because you feel one more round will change the result.', 'Stop for the day if gaming affects sleep, work, study, relationships or mood. A break is more useful than making quick decisions while angry or worried.'] },
      { heading: 'Never chase a loss', paragraphs: ['Chasing a loss means spending more because you want to recover an earlier loss. It can increase harm quickly. A previous result does not make the next result more likely to help you.', 'Ignore “fixed game”, “sure-shot trick”, “100% winning strategy” and guaranteed-profit claims. Do not pay for prediction groups, bots or account-control services.'] },
      { heading: 'Use account controls when available', paragraphs: ['Open Account or Settings and look for deposit limits, time reminders, a cooling-off option, account closure or self-exclusion. Use any control that helps you take a break or stop.', 'You can also open customer support and ask which account-limit or closure options are available. Keep the request number and do not share your password or OTP.'] },
      { heading: 'When to seek help', paragraphs: ['Stop and speak to someone you trust if gaming causes debt, stress, secrecy, arguments or repeated failed attempts to stop. You can also contact a qualified mental-health, financial-counselling or gaming-support service in your area.', 'If there is an immediate risk to your safety, contact local emergency help.'] },
    ], related: [{ label: 'Disclaimer', href: '/disclaimer/' }, { label: 'Games overview', href: '/shree-win-games/' }, { label: 'Promotion guide', href: '/shree-win-promotion/' }],
  },
};
