/* eslint-disable @next/next/no-img-element */
import { PageShell } from './components/SiteChrome';
import { CTAButton, DailyGiftCodeStatus, FAQAccordion, FeatureCard, GameCard, Hero, ReferralEventTable, ResponsibleGamingNotice, SafetyNotice, ScreenshotGallery, SectionHeading } from './components/Marketing';
import { siteConfig } from './site-config';

const faqs = [
  ['What is ShreeWin Game?', 'ShreeWin Game is an interactive mobile gaming platform with Lottery, Popular, Mini Game, Slots and Casino sections. Available games include WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace. Each game has its own rules, round details and controls.'],
  ['Which is the correct ShreeWin website?', 'Use the Login or Register button on ShreeWinAPK.net to open the ShreeWin account page. Check the website address in your browser before you enter your mobile number, email, password, OTP or payment details.'],
  ['How do I register on ShreeWin?', 'Tap Register, choose phone or email registration, enter the details requested on the platform and create a strong password. Check the ShreeWin invitation code before you submit the form. Read the privacy terms, complete any OTP step shown by the platform and keep the code and password private.'],
  ['How do I complete ShreeWin login?', 'Tap Login and choose the same phone number or email that you used during registration. Enter your password and check the details before you continue. If you forget the password, use the recovery option shown on the platform. Never send your OTP or password to another person.'],
  ['Is there a ShreeWin app?', 'Yes. ShreeWin has a mobile app for Android users. The app includes the game lobby, Activity, Promotion, Account and Wallet sections. Check the latest version, file size and download button on the ShreeWin download page before installation.'],
  ['How do I download the ShreeWin APK?', 'Open the ShreeWin app download page through a link you trust. Check the domain and file name before downloading. Android may ask for permission to install an APK, which means an Android installation file. Review app permissions, keep Play Protect enabled and avoid modded or cracked files.'],
  ['Is ShreeWin available on the Play Store?', 'A public ShreeWin listing on Google Play is not confirmed yet. If you see a Play Store button on the ShreeWin download page, open it and check the app name, developer name and logo before you install the app.'],
  ['What is the ShreeWin invite code?', 'A ShreeWin invite code connects your new account with the agent who shared the registration link. Open the form through our Register button and make sure the VIP invite code is visible before you submit. Eligible users who register with the code can receive the ₹100 invite bonus under the current offer terms.'],
  ['How do I use a ShreeWin gift code?', 'Open the app and go to Settings. Look for the Gift Code or Redeem Code option, enter the active code and check it once before you submit. A code may have an expiry date, account condition or one-time limit. Never pay an unknown person only to receive a code.'],
  ['Which ShreeWin games are available?', 'ShreeWin includes WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace. The main categories are Lobby, Lottery, Popular, Mini Game, Slots and Casino. Open Rules before joining so you can check the round time, available choices and result process.'],
  ['How do I deposit funds?', 'Open Wallet and tap Deposit or Recharge. Available methods include QR code, UPI, Paytm, Google Pay, PhonePe and USDT. Enter the amount, check the receiving details and save the transaction reference. Always use the payment details shown inside your account.'],
  ['How do I withdraw funds?', 'Open Wallet, tap Withdrawal and select UPI, bank transfer or USDT. Add or select your receiving account, enter the amount and check every detail before you submit. The minimum is ₹100 for UPI, ₹110 for bank transfer and ₹1,000 for USDT.'],
  ['What is the ShreeWin minimum withdrawal?', 'The minimum withdrawal is ₹100 through UPI, ₹110 through bank transfer and ₹1,000 through USDT. Open Wallet and choose your payment method to see the limits and any account conditions before you submit the request.'],
  ['How long does a ShreeWin withdrawal take?', 'UPI and bank withdrawal requests are normally processed within 30 minutes. USDT withdrawals are processed instantly in normal conditions. Verification, payment-network traffic, incorrect receiving details or account checks can take extra time.'],
  ['What should I do when a withdrawal is pending?', 'First, wait for the expected processing period and check the transaction status in Wallet. Confirm that your bank, UPI ID or USDT network is correct. If it remains pending, use the customer-support button in Settings and share only your user ID, amount, time and transaction reference—never your password, OTP or PIN.'],
  ['Is ShreeWin real or fake?', 'ShreeWin is an active gaming platform with account, games, Wallet, Activity and Promotion sections. Use the Login and Register buttons on this website to open the correct access page. Check every payment detail inside your account and keep your password, OTP and payment PIN private.'],
  ['Is ShreeWin safe?', 'ShreeWin provides password-based account access and in-app payment options. You should still use a unique password, keep OTPs and PINs private, check payment details and set a spending limit. ShreeWinAPK.net never asks you to enter your ShreeWin password, OTP or banking PIN.'],
  ['How do I contact ShreeWin customer support?', 'Open Settings in ShreeWin and tap Customer Support. Support is available 24/7 for login, wallet and transaction problems. Include your user ID, issue type, amount, time and transaction reference so the team can check the problem. Never share your password, OTP, UPI PIN or banking PIN.'],
  ['What is the ShreeWin Grand Referral Event 2026?', 'It is an Agency milestone event for eligible agents. The event tracks verified direct active invites and lists leaderboard rewards for qualifying positions. Open Promotion Center to check your recorded count, event availability and current rules.'],
  ['How does an invite qualify for the referral event?', 'The event defines an active invite as a unique direct subordinate registered through the invitation link who completes at least one deposit of ₹500 or more and places eligible activity on WinGo or TRX lottery games. Check Promotion Center for recorded progress.'],
  ['How do I claim a ShreeWin referral milestone reward?', 'Open Promotion Center and select the Grand Referral Event. When a milestone is unlocked, open it and tap Receive, then check the Wallet record. The event lists a 1.0x wagering requirement before eligible withdrawal.'],
  ['Is ShreeWin restricted to users aged 18+?', 'Yes. ShreeWin is only for users aged 18 or above. You must also check whether this type of gaming is allowed in your state or location. Do not borrow funds to play, do not chase losses and stop if gaming affects your finances, work, sleep or family.'],
] as const;

const features = [
  ['⬇', 'ShreeWin APK', 'Android download checks, app installation and latest-version guidance.', '/shree-win-download/'],
  ['↗', 'Login & Register', 'Phone or email access, password reset and invitation-code help.', '/shree-win-login/'],
  ['⑧', 'Games & Lottery', 'WinGo, K3, 5D, Aviator, TRX WinGo, MotoRace and game categories.', '/shree-win-games/'],
  ['₹', 'Deposit & Recharge', 'Wallet, QR code, UPI, Paytm, GPay, PhonePe and USDT steps.', '/shree-win-deposit/'],
  ['⇩', 'Withdrawals', 'UPI, bank transfer, USDT, minimum limits and pending requests.', '/shree-win-withdrawal/'],
  ['🎁', 'Bonus & Gift Code', 'First-deposit offers, redeem-code location and rule checks.', '/shree-win-gift-code/'],
  ['♛', 'Referral & Agent', 'Invite codes, six agency levels and commission-record basics.', '/shree-win-agent/'],
  ['?', 'Safety & Support', 'APK checks, fake-link warnings, account recovery and support steps.', '/shree-win-apk-safety/'],
] as const;

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })),
};

export default function Home() {
  return <PageShell><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <Hero />

    <section className="glance-section container" aria-labelledby="glance-title">
      <div className="glance-heading"><span>Quick facts</span><h2 id="glance-title">ShreeWin at a Glance</h2><p>Important information for Indian mobile users.</p></div>
      <dl className="glance-grid"><div><dt>Account access</dt><dd>Phone or email</dd></div><div><dt>Android access</dt><dd>APK / mobile app</dd></div><div><dt>Known games</dt><dd>WinGo, K3, 5D, Aviator &amp; more</dd></div><div><dt>Deposit methods</dt><dd>QR, UPI, Paytm, GPay, PhonePe, USDT</dd></div><div><dt>UPI minimum</dt><dd>₹100 withdrawal</dd></div><div><dt>Bank minimum</dt><dd>₹110 withdrawal</dd></div><div><dt>USDT minimum</dt><dd>₹1,000 withdrawal</dd></div><div><dt>Support location</dt><dd>Settings section</dd></div><div><dt>Age requirement</dt><dd>18+ only</dd></div></dl>
    </section>

    <nav className="topic-links container" aria-label="Popular ShreeWin guides"><a href="/shree-win-apk/">App overview</a><a href="/shree-win-download/">APK download</a><a href="/shree-win-login/">ShreeWin login</a><a href="/shree-win-register/">ShreeWin register</a><a href="/shree-win-games/">All games</a><a href="/shree-win-lottery/">WinGo &amp; Lottery</a><a href="/shree-win-deposit/">Deposit guide</a><a href="/shree-win-withdrawal/">Withdrawal guide</a><a href="/shree-win-gift-code/">Gift Code</a><a href="/shree-win-agent/">Agent guide</a><a href="/shree-win-grand-referral-event/">Referral event 2026</a><a href="/shree-win-account-recovery/">Account recovery</a><a href="/shree-win-apk-safety/">APK safety</a><a href="/shree-win-faq/">FAQ</a></nav>

    <section className="content-section light" id="shree-win-apk"><div className="container editorial-grid"><SectionHeading eyebrow="Complete platform guide" title="What is ShreeWin Game?" copy="A complete look at the app, games, wallet, account and promotion features." /><div className="long-copy">
      <p><strong>ShreeWin Game is an interactive mobile gaming app with different game formats, promotions and reward features.</strong> The platform asks users to understand rules, watch the active period, review available choices and confirm each decision carefully. These skill and attention elements help you use the interface correctly, but they do not guarantee a particular game result.</p>
      <p>The game menu includes <a href="/shree-win-games/">Lobby, Lottery, Popular, Mini Game, Slots and Casino</a>. Available games include <strong>WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace</strong>. Each guide explains where to find the game and what to check before you confirm an entry.</p>
      <p>You can create an account through the <a href="/shree-win-register/">ShreeWin register</a> page and return through the <a href="/shree-win-login/">ShreeWin login</a> page. Both phone and email options are available. The registration form also includes a ShreeWin invite code field.</p>
      <p>The Account and Wallet sections include Deposit, Withdrawal and Transaction. Payment options include QR code, UPI, Paytm, Google Pay, PhonePe and USDT. UPI withdrawals start from ₹100, bank withdrawals start from ₹110 and USDT withdrawals start from ₹1,000.</p>
      <p>ShreeWinAPK.net explains the app, games, account and wallet steps in clear language. The Login and Register buttons take you to ShreeWin. This website does not collect your phone number, email, password, OTP, withdrawal password, UPI PIN or banking PIN.</p>
    </div></div></section>

    <section className="content-section navy"><div className="container"><SectionHeading eyebrow="Everything in one place" title="What information do we provide?" copy="Open the exact guide you need. You do not have to search through one long page." centered/><div className="feature-grid">{features.map(([icon, title, copy, href]) => <FeatureCard key={title} icon={icon} title={title} href={href}>{copy}</FeatureCard>)}</div></div></section>

    <section className="content-section app-inside"><div className="container split-layout"><div className="walkthrough-phone"><img src="/preview-home.webp" width="720" height="1732" alt="ShreeWin Game mobile homepage with game categories" loading="lazy" /></div><div><SectionHeading eyebrow="Mobile interface" title="Inside the ShreeWin App" copy="The app keeps the main actions close to your thumb. Here is what you will see on the homepage."/><div className="walkthrough-list">
      <article><b>01</b><div><h3>Login and Register</h3><p>Existing users can open ShreeWin login. New users can register with a phone number or email address. Both buttons take you directly to the ShreeWin account page.</p></div></article>
      <article><b>02</b><div><h3>Lobby and game tabs</h3><p>Use Lobby, Lottery, Popular, Mini Game, Slots and Casino to browse the available games. <a href="/shree-win-games/">Read the games guide</a> for the complete game map.</p></div></article>
      <article><b>03</b><div><h3>Activity and Promotion</h3><p>Activity shows reward-related areas. Promotion contains current offers and rules. Always read eligibility and turnover conditions before you deposit for a bonus.</p></div></article>
      <article><b>04</b><div><h3>Wallet and Transactions</h3><p>Wallet contains Deposit, Withdrawal and Transaction options. Use Transaction to check a reference, then open the <a href="/shree-win-deposit/">deposit guide</a> or <a href="/shree-win-withdrawal/">withdrawal guide</a> for complete steps.</p></div></article>
      <article><b>05</b><div><h3>Settings, Gift Code and Support</h3><p>Open Settings to find Gift Code and Customer Support. Read the <a href="/shree-win-gift-code/">Gift Code guide</a> or <a href="/shree-win-account-settings/">Account Settings guide</a> for focused help.</p></div></article>
    </div></div></div></section>

    <section className="content-section light" id="app-download"><div className="container download-grid"><div><SectionHeading eyebrow="Android app" title="ShreeWin App Download and APK Guide" copy="Follow these steps to download and install the ShreeWin app on Android."/><ol className="numbered-steps dark-steps"><li><b>1</b><div><h3>Open ShreeWin</h3><p>Tap Visit ShreeWin and check the website address before you download the app.</p></div></li><li><b>2</b><div><h3>Choose Android download</h3><p>Tap the ShreeWin app download or APK button on the download page.</p></div></li><li><b>3</b><div><h3>Check the APK</h3><p>APK is the installation file for Android. Check its name and requested permissions.</p></div></li><li><b>4</b><div><h3>Install the app</h3><p>Read the Android message, allow the download source and tap Install.</p></div></li><li><b>5</b><div><h3>Check for updates</h3><p>Use the update option inside the app or return to the same download page.</p></div></li><li><b>6</b><div><h3>Login to your account</h3><p>Open ShreeWin and enter the phone number or email linked to your account.</p></div></li></ol><CTAButton kind="login" className="button-wide">Visit ShreeWin ↗</CTAButton></div><SafetyNotice title="APK safety checks"><ul><li>Check the website address.</li><li>Do not download from an unknown message.</li><li>Keep Play Protect enabled.</li><li>Review every permission.</li><li>Never share your OTP or password.</li></ul><p>If ShreeWin gives you a Google Play link, check the app name, logo and developer details on Google Play before installing.</p></SafetyNotice></div></section>

    <section className="content-section soft" id="account-access"><div className="container"><SectionHeading eyebrow="Account setup" title="ShreeWin Login, Registration and Invite Code" copy="Login with your existing account or create a new account in a few steps."/><p className="section-intro-note">ShreeWin signup, register and registration all mean creating a new account. ShreeWin login is for an account that already exists.</p><div className="games-grid"><GameCard label="Existing account" title="ShreeWin Login" copy="Choose Phone Number or Email, enter your password and tap Login. Use Forgot Password if you cannot sign in." href="/shree-win-login/" icon="↗"/><GameCard label="New account" title="ShreeWin Register" copy="Choose phone or email registration, create a password, check the invitation code and complete the required verification." href="/shree-win-register/" icon="+"/></div><div className="account-note"><h3>ShreeWin VIP invitation code</h3><p>Open the ShreeWin form through our Register button and make sure the VIP invitation code is visible before you submit. Eligible new users who register with the code can receive the ₹100 invite bonus and other perks under the offer terms shown on the registration page.</p><CTAButton kind="register">Open ShreeWin Registration ↗</CTAButton></div></div></section>

    <section className="content-section light" id="games"><div className="container"><SectionHeading eyebrow="Game information" title="Popular ShreeWin Games and Categories" copy="Understand the rules, timing, choices and result process for each game format."/><p className="section-intro-note">ShreeWin includes interactive game formats that require you to read the screen, understand the rules and review each selection. WinGo is a colour and number game with an active round, countdown, available choices and result history. K3, 5D, Aviator, TRX WinGo and MotoRace use their own controls and result rules, so do not treat every game as the same type of skill or decision challenge.</p><div className="games-grid"><GameCard label="Colour & number" title="WinGo" copy="Use attention and rule knowledge to check the active period, countdown, available choices, entry amount and result history before confirming." href="/shree-win-lottery/" icon="⑧"/><GameCard label="Number game" title="K3" copy="Open Rules and carefully review the round time, number choices, entry options and result process before making a decision." href="/shree-win-games/" icon="⚄"/><GameCard label="Number game" title="5D" copy="Check the active period, available number choices and result table. Review your selection carefully before you confirm it." href="/shree-win-games/" icon="⑤"/><GameCard label="Crash-style game" title="Aviator" copy="Read the Help section and understand the active round, controls, entry buttons and on-screen value before taking any action." href="/shree-win-games/" icon="✈"/><GameCard label="Lottery format" title="TRX WinGo" copy="Learn where to find TRX WinGo and how to read its round screen, choices, confirmation details and result record." href="/trx-wingo/" icon="◎"/><GameCard label="Lottery format" title="MotoRace" copy="Open Rules to understand MotoRace periods, available choices, confirmation steps and result history before participating." href="/motorace/" icon="🏍"/></div></div></section>

    <section className="content-section navy" id="deposit-guide"><div className="container download-grid"><div><SectionHeading eyebrow="Wallet guide" title="How to Deposit or Recharge on ShreeWin" copy="The Wallet menu keeps Deposit, Withdrawal and Transaction in one place."/><ol className="numbered-steps"><li><b>1</b><div><h3>Open Wallet</h3><p>Login to your account and tap Wallet.</p></div></li><li><b>2</b><div><h3>Tap Deposit or Recharge</h3><p>Choose Deposit or Recharge from the Wallet menu.</p></div></li><li><b>3</b><div><h3>Select a payment method</h3><p>Choose a method displayed in your account.</p></div></li><li><b>4</b><div><h3>Enter the amount</h3><p>Enter the amount and check any payment or offer condition.</p></div></li><li><b>5</b><div><h3>Check the receiving details</h3><p>Match the UPI ID, QR code or wallet details shown in your account.</p></div></li><li><b>6</b><div><h3>Save the reference</h3><p>Keep the UTR, transaction ID, time and screenshot until your balance is updated.</p></div></li></ol><a className="button button-outline" href="/shree-win-deposit/">Read Complete Deposit Guide →</a></div><SafetyNotice title="Funds debited but balance not updated?"><p>Open Wallet and check Transaction first. Wait for the payment network to update. If the balance still does not appear, use Customer Support in Settings.</p><p>Share your user ID, amount, date, time, payment method and reference. Never share your password, OTP, UPI PIN, card PIN or remote screen access.</p></SafetyNotice></div></section>

    <section className="content-section light" id="add-bank-account"><div className="container editorial-grid"><SectionHeading eyebrow="Receiving account" title="How to Add a Bank Account or UPI ID" copy="Enter each detail carefully. A small mistake can delay or fail a withdrawal."/><div className="long-copy"><p>Open Wallet, choose Withdrawal and tap <strong>Add Bank Account</strong>. Enter the account-holder name, bank name, account number and IFSC code. IFSC is the code for your bank branch. Check the account number twice before you save it.</p><p>For UPI, enter the UPI ID shown in your own payment app. The account name should match your ShreeWin details. Complete the OTP step if it appears, and enter the OTP only on the ShreeWin screen.</p><p>Do not share your full banking details on Telegram, WhatsApp or an unknown support chat. ShreeWinAPK.net does not need your bank number, UPI PIN, OTP or withdrawal password. Check the receiving account again before your next <a href="/shree-win-withdrawal/">ShreeWin withdrawal</a>.</p></div></div></section>

    <section className="content-section finance-section" id="withdrawal-guide"><div className="container"><SectionHeading eyebrow="Withdrawal guide" title="ShreeWin Withdrawal: UPI, Bank and USDT" copy="Check your receiving details and the available limit before every request."/><div className="money-grid"><article className="money-card featured"><span>UPI</span><h3>Minimum ₹{siteConfig.withdrawals.upiMinimumInr}</h3><p>Choose UPI in Wallet, add or select your UPI ID, enter the amount and check the account name. UPI requests are normally processed within 30 minutes. Verification or payment-network checks can take extra time.</p><a href="/shree-win-withdrawal/">Read full withdrawal guide →</a></article><article className="money-card"><span>Bank transfer</span><h3>Minimum ₹{siteConfig.withdrawals.bankMinimumInr}</h3><p>Add the correct account-holder name, bank, account number and IFSC. Bank requests are normally processed within 30 minutes. Incorrect details or an account check can delay the request.</p><a href="#add-bank-account">How to add a bank account →</a></article><article className="money-card"><span>USDT</span><h3>Minimum ₹{siteConfig.withdrawals.usdtMinimumInr.toLocaleString('en-IN')}</h3><p>USDT requests are processed instantly in normal conditions. Check the supported network, wallet address, conversion and fee before you submit because a crypto transfer cannot be reversed.</p><a href="/shree-win-withdrawal/">Check USDT safety steps →</a></article></div><div className="claim-note"><strong>Before you submit:</strong> Open Wallet to check the available limit, account verification, turnover condition and fee for your selected withdrawal method.</div></div></section>

    <section className="content-section soft" id="bonus-referral"><div className="container"><SectionHeading eyebrow="Offers and referrals" title="ShreeWin Bonus, Gift Code and Agent Work" copy="Find the offer, code and agent details you need in one place."/><div className="money-grid light-cards"><article className="money-card"><span>First-deposit offer</span><h3>Welcome bonus tiers</h3><div className="tier-list">{siteConfig.firstDepositTiers.map(tier => <div key={tier.depositInr}><b>₹{tier.depositInr.toLocaleString('en-IN')} deposit</b><strong>₹{tier.bonusInr} bonus</strong></div>)}</div><p>The first-deposit bonus is available once for each eligible account. Open Promotion to check the deposit tier, claim method and turnover terms before you recharge.</p><a href="/shree-win-promotion/">Read the promotion rules →</a></article><article className="money-card"><span>Gift and redeem code</span><h3>Use Gift Code in Settings</h3><p>Open Settings and tap Gift Code or Redeem Code. Enter the active code exactly and tap Confirm. Check its expiry, account eligibility and one-time use condition.</p><a href="/shree-win-gift-code/">Read the Gift Code guide →</a></article><article className="money-card"><span>Refer and earn</span><h3>Invitation and agency system</h3><p>The ShreeWin referral program uses an invitation link or code. Open Agency to check the six team levels, team activity, commission rate and collection record.</p><a href="/shree-win-agent/">Read the ShreeWin agent guide →</a></article></div></div></section>

    <section className="content-section light referral-event-section" id="grand-referral-event"><div className="container"><SectionHeading eyebrow="Agency milestone event" title={siteConfig.grandReferralEvent.name} copy="Reach verified direct active-invite milestones and check the listed leaderboard rewards inside Promotion Center."/><div className="event-summary-grid"><article><span>Active invite</span><strong>₹{siteConfig.grandReferralEvent.activeInviteDepositInr}+ deposit</strong><p>A unique direct subordinate must also complete eligible WinGo or TRX lottery activity.</p></article><article><span>Claim location</span><strong>Promotion Center</strong><p>Open an unlocked milestone, tap Receive and check the Wallet credit record.</p></article><article><span>Reward condition</span><strong>{siteConfig.grandReferralEvent.wageringRequirement} wagering</strong><p>Complete the event condition before requesting an eligible withdrawal.</p></article></div><ReferralEventTable/><div className="event-actions"><a className="button button-outline" href="/shree-win-grand-referral-event/">Read Complete Event Rules →</a><a className="button button-text" href="/shree-win-agent/">Understand Agent Levels →</a><CTAButton kind="register">Register with Invite Link ↗</CTAButton></div><p className="section-intro-note event-terms-note">Leaderboard rewards require verified qualification. Open the live event to confirm availability, dates, product or cash options, claim window and withdrawal rules for your account.</p></div></section>

    <section className="content-section light" id="support-and-safety"><div className="container editorial-grid"><SectionHeading eyebrow="Trust and support" title="ShreeWin Account Safety and Support" copy="Use the correct link, protect your account details and contact support from Settings."/><div className="intent-grid"><article><h3>ShreeWin access link</h3><p>Use the Login and Register buttons on ShreeWinAPK.net to open ShreeWin. Check the website address before entering your account details.</p></article><article><h3>Secure account access</h3><p>Use a unique password. Keep your OTP, withdrawal password and payment PIN private. This website does not collect any ShreeWin login or banking details.</p></article><article><h3>24/7 customer support</h3><p>Open Settings and tap Customer Support for login, wallet or transaction help. Keep your user ID and transaction reference ready.</p></article><article><h3>Wallet safety</h3><p>Check the receiving details before every deposit or withdrawal. Use only the amount you have set aside for gaming.</p></article><article><h3>18+ access</h3><p>ShreeWin is only for adults aged 18 or above. Check the gaming rules that apply in your Indian state or location.</p></article><article><h3>Responsible play</h3><p>Set a time and amount limit before you start. Never borrow funds for gaming or continue only to recover an earlier loss.</p></article></div></div></section>

    <section className="content-section navy" id="screenshots"><div className="container"><SectionHeading eyebrow="App walkthrough" title="Explore the ShreeWin Game App" copy="Learn where to find games, Activity, promotions, Agency, Account, Gift Code, Deposit and Withdrawal options."/><DailyGiftCodeStatus/><ScreenshotGallery /></div></section>

    <section className="content-section faq-section" id="faq"><div className="container faq-layout"><SectionHeading eyebrow="Direct answers" title="ShreeWin Game FAQ" copy="Short answers for login, registration, APK, games, deposits, withdrawals, invite codes, support and safety."/><FAQAccordion items={faqs}/></div></section>

    <div className="container responsible-wrap"><ResponsibleGamingNotice /></div>

    <section className="final-cta"><div className="container"><img src={siteConfig.logo} width="270" height="90" alt="ShreeWin Game" loading="lazy"/><span>Open ShreeWin</span><h2>Ready to Get Started?</h2><p>Choose Register to create an account or Login to open your existing account. Never share your password, OTP or payment PIN.</p><div><CTAButton kind="register">Register on ShreeWin ↗</CTAButton><CTAButton kind="login">ShreeWin Login ↗</CTAButton></div><small>ShreeWinAPK.net provides ShreeWin guides and account access links.</small></div></section>
  </main></PageShell>;
}
