/* eslint-disable @next/next/no-img-element */
import { PageShell } from './components/SiteChrome';
import { CTAButton, FAQAccordion, FeatureCard, GameCard, Hero, ResponsibleGamingNotice, SafetyNotice, ScreenshotGallery, SectionHeading } from './components/Marketing';
import { siteConfig } from './site-config';

const faqs = [
  ['What is ShreeWin Game?', 'ShreeWin Game is a mobile gaming platform with Lottery, Popular, Mini Game and Casino sections. The supplied app screens also show WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace. You can use this website to understand the app, account, wallet, promotion and agent features before you open the platform.'],
  ['Which is the correct ShreeWin website?', 'ShreeWinAPK.net is an independent guide and is not the owner of ShreeWin Game. Our Login and Register buttons open the access link supplied by the site administrator. Always check the address shown in your browser before you enter a phone number, email, password, OTP or payment detail.'],
  ['How do I register on ShreeWin?', 'Tap Register, choose phone or email registration, enter the details requested on the platform and create a strong password. Check the ShreeWin invitation code before you submit the form. Read the privacy terms, complete any OTP step shown by the platform and keep the code and password private.'],
  ['How do I complete ShreeWin login?', 'Tap Login and choose the same phone number or email that you used during registration. Enter your password and check the details before you continue. If you forget the password, use the recovery option shown on the platform. Never send your OTP or password to another person.'],
  ['Is there a ShreeWin app?', 'Yes. The supplied information shows a mobile ShreeWin app and an Android APK flow. The interface is designed for a phone and includes the game lobby, Activity, Promotion, Account and wallet-related options. App version, size and direct download file should be checked on the current platform before installation.'],
  ['How do I download the ShreeWin APK?', 'Open the ShreeWin app download page through a link you trust. Check the domain and file name before downloading. Android may ask for permission to install an APK, which means an Android installation file. Review app permissions, keep Play Protect enabled and avoid modded or cracked files.'],
  ['Is ShreeWin available on the Play Store?', 'We have not independently confirmed a matching public Play Store listing. If the live ShreeWin page gives you a Play Store button, open only that button and check the app name, developer name, logo and reviews on Google Play. Do not install a different app only because its name looks similar.'],
  ['What is the ShreeWin invite code?', 'A ShreeWin invite code links a new registration to the person or agent who shared it. The registration screen has an invitation-code field. The administrator says the supplied Register link may include a VIP code, but any special game perk must be checked on the live registration screen before you submit.'],
  ['How do I use a ShreeWin gift code?', 'Open the app and go to Settings. Look for the Gift Code or Redeem Code option, enter the active code and check it once before you submit. A code may have an expiry date, account condition or one-time limit. Never pay an unknown person only to receive a code.'],
  ['Which ShreeWin games are available?', 'The supplied screens and information show WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace. The main menu also has Lobby, Lottery, Popular, Mini Game and Casino categories. Game names, rules and availability can change, so read the live rule page before you choose any paid game.'],
  ['How do I deposit money?', 'Open Wallet and tap Deposit or Recharge. The supplied payment information includes QR code, UPI, Paytm, Google Pay, PhonePe and USDT. Enter the amount, check the receiving details and save the transaction reference. Never transfer money to a personal payment ID that you cannot verify inside the platform.'],
  ['How do I withdraw money?', 'Open Wallet, tap Withdrawal and select UPI, bank transfer or USDT. Add or select your receiving account, enter an allowed amount and check every detail before you submit. The supplied minimum is ₹100 for UPI or bank transfer and ₹1,000 for USDT. Live limits may change.'],
  ['What is the ShreeWin minimum withdrawal?', 'The current information supplied by the administrator lists ₹100 as the minimum ShreeWin UPI withdrawal and bank-transfer withdrawal. The supplied minimum for USDT is ₹1,000. Check the withdrawal screen before every request because account eligibility, bonus turnover, verification, fees and platform limits may change.'],
  ['How long does a ShreeWin withdrawal take?', 'The administrator says UPI and bank requests are normally processed within 30 minutes, while USDT is described as instant. This is an expected time, not a guarantee. Bank checks, network traffic, wrong details, account review or bonus conditions can make a request take longer.'],
  ['What should I do when a withdrawal is pending?', 'First, wait for the expected processing period and check the transaction status in Wallet. Confirm that your bank, UPI ID or USDT network is correct. If it remains pending, use the customer-support button in Settings and share only your user ID, amount, time and transaction reference—never your password, OTP or PIN.'],
  ['Is ShreeWin real or fake?', 'The supplied screenshots show a working ShreeWin interface with account, game, wallet, activity and promotion areas. However, this independent website cannot promise that every payment, game result or third-party claim is genuine. Use the supplied access link carefully, check the current terms and do not treat “100% real” as a guarantee.'],
  ['Is ShreeWin safe?', 'No gaming or payment platform should be called totally safe without independent checks. Protect yourself by using the correct link, creating a unique password, keeping OTPs and PINs private, checking payment details and setting spending limits. ShreeWinAPK.net never asks you to enter platform login or banking credentials.'],
  ['How do I contact ShreeWin customer support?', 'The supplied app information says a customer-support button is available in Settings and describes support as 24/7. Response time may still vary. When you report a problem, include your user ID, issue type, amount, time and transaction reference. Never share your password, OTP, UPI PIN or banking PIN.'],
  ['Is ShreeWin restricted to users aged 18+?', 'Yes. This website treats ShreeWin as an 18+ real-money gaming platform. You must also check whether this type of gaming is allowed in your state or location. Do not use borrowed money, do not chase losses and stop if gaming starts affecting your finances, work, sleep or family.'],
] as const;

const features = [
  ['⬇', 'ShreeWin APK', 'Android download checks, app installation and latest-version guidance.', '/shree-win-download'],
  ['↗', 'Login & Register', 'Phone or email access, password reset and invitation-code help.', '/shree-win-login'],
  ['⑧', 'Games & Lottery', 'WinGo, K3, 5D, Aviator, TRX WinGo, MotoRace and game categories.', '/shree-win-games'],
  ['₹', 'Deposit & Recharge', 'Wallet, QR code, UPI, Paytm, GPay, PhonePe and USDT steps.', '#deposit-guide'],
  ['⇩', 'Withdrawals', 'UPI, bank transfer, USDT, minimum limits and pending requests.', '/shree-win-withdrawal'],
  ['🎁', 'Bonus & Gift Code', 'First-deposit offers, redeem-code location and rule checks.', '/shree-win-promotion'],
  ['♛', 'Referral & Agent', 'Invite codes, six agency levels and commission-record basics.', '/shree-win-agent'],
  ['?', 'Safety & Support', 'Account protection, 18+ guidance and support complaint steps.', '#support-and-safety'],
] as const;

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })),
};

export default function Home() {
  return <PageShell><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <Hero />

    <section className="glance-section container" aria-labelledby="glance-title">
      <div className="glance-heading"><span>Quick facts</span><h2 id="glance-title">ShreeWin at a Glance</h2><p>Important information for Indian mobile users.</p></div>
      <dl className="glance-grid"><div><dt>Account access</dt><dd>Phone or email</dd></div><div><dt>Android access</dt><dd>APK / mobile app</dd></div><div><dt>Known games</dt><dd>WinGo, K3, 5D, Aviator &amp; more</dd></div><div><dt>Deposit methods</dt><dd>QR, UPI, Paytm, GPay, PhonePe, USDT</dd></div><div><dt>UPI / Bank minimum</dt><dd>₹100 withdrawal</dd></div><div><dt>USDT minimum</dt><dd>₹1,000 withdrawal</dd></div><div><dt>Support location</dt><dd>Settings section</dd></div><div><dt>Age requirement</dt><dd>18+ only</dd></div></dl>
    </section>

    <nav className="topic-links container" aria-label="Popular ShreeWin guides"><a href="/shree-win-apk">App overview</a><a href="/shree-win-download">APK download</a><a href="/shree-win-login">ShreeWin login</a><a href="/shree-win-register">ShreeWin register</a><a href="/shree-win-games">All games</a><a href="/shree-win-lottery">WinGo &amp; Lottery</a><a href="#deposit-guide">Deposit guide</a><a href="/shree-win-withdrawal">Withdrawal guide</a><a href="/shree-win-promotion">Bonus &amp; gift code</a><a href="/shree-win-agent">Agent guide</a></nav>

    <section className="content-section light" id="shree-win-apk"><div className="container editorial-grid"><SectionHeading eyebrow="Complete platform guide" title="What is ShreeWin Game?" copy="A simple explanation of the app, games, wallet, account and promotion features." /><div className="long-copy">
      <p><strong>ShreeWin Game is a mobile platform with real-money gaming features.</strong> Its main screen gives you quick access to account buttons, game categories, promotions, wallet options and profile settings. The design is made for a phone, so you can find the important buttons without opening many pages.</p>
      <p>The main game menu includes <a href="/shree-win-games">Lobby, Lottery, Popular, Mini Game and Casino</a>. The supplied information also shows <strong>WinGo, K3, 5D, Aviator, TRX WinGo and MotoRace</strong>. These are random or prediction-style games. Do not treat them as skill-based income or a sure way to make money.</p>
      <p>You can create an account through the <a href="/shree-win-register">ShreeWin register</a> page and return through the <a href="/shree-win-login">ShreeWin login</a> page. Phone and email options are shown in the supplied screens. The registration form also has a field for a ShreeWin invite code or invitation code.</p>
      <p>The Account and Wallet areas cover deposits, withdrawals and transaction records. The supplied payment methods include QR code, UPI, Paytm, Google Pay, PhonePe and USDT. UPI and bank withdrawals start from ₹100 according to the supplied information. The stated USDT minimum is ₹1,000.</p>
      <p>ShreeWinAPK.net explains these features in simple language. It is an independent information website, not the owner or operator of ShreeWin. We provide administrator-supplied Login and Register links, but we do not collect your phone number, email, password, OTP, withdrawal password, UPI PIN or banking PIN.</p>
    </div></div></section>

    <section className="content-section navy"><div className="container"><SectionHeading eyebrow="Everything in one place" title="What information do we provide?" copy="Open the exact guide you need. You do not have to search through one long page." centered/><div className="feature-grid">{features.map(([icon, title, copy, href]) => <FeatureCard key={title} icon={icon} title={title} href={href}>{copy}</FeatureCard>)}</div></div></section>

    <section className="content-section app-inside"><div className="container split-layout"><div className="walkthrough-phone"><img src="/preview-home.webp" width="720" height="1732" alt="ShreeWin Game mobile homepage with game categories" loading="lazy" /></div><div><SectionHeading eyebrow="Mobile interface" title="Inside the ShreeWin App" copy="The app keeps the main actions close to your thumb. Here is what you will see on the homepage."/><div className="walkthrough-list">
      <article><b>01</b><div><h3>Login and Register</h3><p>Existing users can open ShreeWin login. New users can open ShreeWin registration by phone or email. Both actions leave this guide website and open the supplied platform link.</p></div></article>
      <article><b>02</b><div><h3>Lobby and game tabs</h3><p>Lobby, Lottery, Popular, Mini Game and Casino help you move between game types. <a href="/shree-win-games">Read the games guide</a> before opening any paid game.</p></div></article>
      <article><b>03</b><div><h3>Activity and Promotion</h3><p>Activity shows reward-related areas. Promotion contains current offers and rules. Always read eligibility and turnover conditions before you deposit for a bonus.</p></div></article>
      <article><b>04</b><div><h3>Wallet and Transactions</h3><p>Wallet contains Deposit, Withdrawal and Transaction options. Use Transaction to save or check the reference for a recharge or withdrawal request.</p></div></article>
      <article><b>05</b><div><h3>Settings, Gift Code and Support</h3><p>The supplied information places Gift Code and customer support inside Settings. Use these in-app buttons instead of trusting codes or support numbers shared by unknown people.</p></div></article>
    </div></div></div></section>

    <section className="content-section light" id="app-download"><div className="container download-grid"><div><SectionHeading eyebrow="Android app" title="ShreeWin App Download and APK Guide" copy="Follow these checks when you want the ShreeWin app for Android."/><ol className="numbered-steps dark-steps"><li><b>1</b><div><h3>Open a trusted link</h3><p>Use the supplied Visit ShreeWin button. Check the domain before you download anything.</p></div></li><li><b>2</b><div><h3>Find the Android option</h3><p>Tap the ShreeWin app download or APK option only when it is shown on the platform.</p></div></li><li><b>3</b><div><h3>Check the file</h3><p>APK means Android installation file. Check its name, source and requested permissions.</p></div></li><li><b>4</b><div><h3>Install carefully</h3><p>Keep Android security enabled. Do not use a modded, cracked or “unlimited” APK.</p></div></li><li><b>5</b><div><h3>Check the latest version</h3><p>Version number and file size can change. Check them on the live download screen.</p></div></li><li><b>6</b><div><h3>Open and sign in</h3><p>Use your login details only inside the intended ShreeWin Game app or website.</p></div></li></ol><CTAButton kind="login" className="button-wide">Visit ShreeWin ↗</CTAButton></div><SafetyNotice title="APK safety checks"><ul><li>Check the website address.</li><li>Do not download from an unknown message.</li><li>Keep Play Protect enabled.</li><li>Review every permission.</li><li>Never share your OTP or password.</li></ul><p>We have not independently confirmed a matching public Play Store listing. If the platform gives a Google Play link, check the developer and app details before installing.</p></SafetyNotice></div></section>

    <section className="content-section soft" id="account-access"><div className="container"><SectionHeading eyebrow="Account setup" title="ShreeWin Login, Registration and Invite Code" copy="Use the correct account path and protect your personal details."/><p className="section-intro-note">ShreeWin signup, ShreeWin register and ShreeWin registration all mean creating a new account. ShreeWin login is for an account that already exists.</p><div className="games-grid"><GameCard label="Existing account" title="ShreeWin Login" copy="Choose phone or email, enter your own password and use the platform recovery option if you cannot sign in. Never send an OTP to support in chat." href="/shree-win-login" icon="↗"/><GameCard label="New account" title="ShreeWin Register" copy="Choose phone or email registration, create a unique password, check the invitation code and read the terms before you submit." href="/shree-win-register" icon="+"/></div><div className="account-note"><h3>About the VIP invitation code</h3><p>The registration screen has a ShreeWin invitation code field. The site administrator says the Register link may include a unique VIP invite code. Check that the code is visible before you submit. Any bonus, VIP level or extra game perk can change and must be confirmed on the live registration page.</p><CTAButton kind="register">Open ShreeWin Registration ↗</CTAButton></div></div></section>

    <section className="content-section light" id="games"><div className="container"><SectionHeading eyebrow="Game information" title="Popular ShreeWin Games and Categories" copy="Learn what each game name means before you open it. Random results cannot be guaranteed."/><p className="section-intro-note">People often search for ShreeWin WinGo, ShreeWin colour prediction or the WinGo colour game. These phrases point to the same type of colour and number game shown in the app. A colour or number result is random; it is not a skill-based earning method.</p><div className="games-grid"><GameCard label="Colour & number" title="WinGo" copy="WinGo is shown as a colour and number game. Read the round rules and result options inside the live game. No pattern or signal can promise a win." href="/shree-win-lottery" icon="⑧"/><GameCard label="Number game" title="K3" copy="K3 appears in the supplied Lottery screen. Check the current numbers, round time and rules in the app before you choose any option." href="/shree-win-games" icon="⚄"/><GameCard label="Number game" title="5D" copy="5D is another supplied Lottery entry. Its name does not tell you the full rules, so open the information panel inside the game first." href="/shree-win-games" icon="⑤"/><GameCard label="Crash-style game" title="Aviator" copy="Aviator is shown in the supplied game information. A rising multiplier can stop at any time. Never call it a fixed or skill-based earning game." href="/shree-win-games" icon="✈"/><GameCard label="Lottery" title="TRX WinGo" copy="TRX WinGo appears in the Lottery category. Our guide explains where to find it and which claims you should avoid." href="/trx-wingo" icon="◎"/><GameCard label="Lottery" title="MotoRace" copy="MotoRace uses motorcycle artwork and appears with the Lottery games. Check the live rules instead of assuming how a round works." href="/motorace" icon="🏍"/></div></div></section>

    <section className="content-section navy" id="deposit-guide"><div className="container download-grid"><div><SectionHeading eyebrow="Wallet guide" title="How to Deposit or Recharge on ShreeWin" copy="The Wallet menu keeps Deposit, Withdrawal and Transaction in one place."/><ol className="numbered-steps"><li><b>1</b><div><h3>Open Wallet</h3><p>Login to your own account and tap Wallet from the account area.</p></div></li><li><b>2</b><div><h3>Tap Deposit or Recharge</h3><p>Choose the button shown in your current app version.</p></div></li><li><b>3</b><div><h3>Select a payment method</h3><p>The supplied options include QR, UPI, Paytm, GPay, PhonePe and USDT.</p></div></li><li><b>4</b><div><h3>Enter the amount</h3><p>Check any minimum, maximum and offer condition before you continue.</p></div></li><li><b>5</b><div><h3>Verify the receiving details</h3><p>Match the live payment details. Do not send money to an unverified personal ID.</p></div></li><li><b>6</b><div><h3>Save the reference</h3><p>Keep the UTR, transaction ID, time and screenshot until your balance is updated.</p></div></li></ol></div><SafetyNotice title="Money debited but balance not updated?"><p>Open Wallet and check Transaction first. Wait for the payment network to update. If the balance still does not appear, use the customer-support button in Settings.</p><p>Share your user ID, amount, date, time, payment method and UTR or transaction reference. Never share your password, OTP, UPI PIN, card PIN or remote screen access.</p></SafetyNotice></div></section>

    <section className="content-section light" id="add-bank-account"><div className="container editorial-grid"><SectionHeading eyebrow="Receiving account" title="How to Add a Bank Account or UPI ID" copy="Enter each detail carefully. A small mistake can delay or fail a withdrawal."/><div className="long-copy"><p>Open the Wallet or withdrawal account section and tap <strong>Add Bank Account</strong>. Enter the account-holder name, bank name, account number and IFSC code. IFSC is the code that identifies your bank branch. Check the account number twice before you save it.</p><p>If UPI is supported, add the UPI ID shown in your own payment app. The name may need to match your verified ShreeWin account details. The platform may send an OTP to confirm the change. Enter that OTP only on the correct platform screen.</p><p>Do not share your full banking information in Telegram, WhatsApp or an unknown support chat. ShreeWinAPK.net does not need your bank number, UPI PIN, OTP or withdrawal password. If you change a receiving account, review it again before the next <a href="/shree-win-withdrawal">ShreeWin withdrawal</a>.</p></div></div></section>

    <section className="content-section finance-section" id="withdrawal-guide"><div className="container"><SectionHeading eyebrow="Real-money withdrawals" title="ShreeWin Withdrawal: UPI, Bank and USDT" copy="Check your eligibility, receiving details and current limit before every request."/><div className="money-grid"><article className="money-card featured"><span>UPI</span><h3>Minimum ₹{siteConfig.withdrawals.upiMinimumInr}</h3><p>Choose UPI in Wallet, select or add your UPI ID, enter an allowed amount and check the name. The administrator says processing is normally within 30 minutes. Actual time can be longer when verification or payment-network checks are required.</p><a href="/shree-win-withdrawal">Read full withdrawal guide →</a></article><article className="money-card"><span>Bank transfer</span><h3>Minimum ₹{siteConfig.withdrawals.bankMinimumInr}</h3><p>Add the correct account-holder name, bank, account number and IFSC. The supplied expected processing time is within 30 minutes. A wrong account detail, account review or bonus condition can delay or fail the request.</p><a href="#add-bank-account">How to add a bank account →</a></article><article className="money-card"><span>USDT</span><h3>Minimum ₹{siteConfig.withdrawals.usdtMinimumInr.toLocaleString('en-IN')}</h3><p>The administrator describes USDT processing as instant. Check the supported network, wallet address, conversion and fee before you submit. Crypto transfers can be irreversible and network conditions can cause delay.</p><a href="/shree-win-withdrawal">Check USDT safety steps →</a></article></div><div className="claim-note"><strong>Processing-time note:</strong> “Within 30 minutes” and “instant” are platform details supplied by the administrator. They are not guaranteed times. Current limits, verification, turnover, fees and support rules should be checked in Wallet.</div></div></section>

    <section className="content-section soft" id="bonus-referral"><div className="container"><SectionHeading eyebrow="Offers and referrals" title="ShreeWin Bonus, Gift Code and Agent Work" copy="Check the benefit and the rules together. A bonus or referral is never guaranteed income."/><div className="money-grid light-cards"><article className="money-card"><span>First-deposit offer</span><h3>Displayed welcome bonus tiers</h3><div className="tier-list">{siteConfig.firstDepositTiers.map(tier => <div key={tier.depositInr}><b>₹{tier.depositInr.toLocaleString('en-IN')} deposit</b><strong>₹{tier.bonusInr} shown</strong></div>)}</div><p>The supplied screen shows a one-time ShreeWin welcome bonus. Check current eligibility, claim method and valid-bet or turnover terms before you recharge.</p><a href="/shree-win-promotion">Read the promotion rules →</a></article><article className="money-card"><span>Gift and redeem code</span><h3>Use the Settings option</h3><p>Open Settings and tap Gift Code or Redeem Code. Enter the code exactly as shared and check its expiry, user eligibility and one-time limit. Do not pay an unknown person for a ShreeWin gift code.</p><a href="/shree-win-promotion">Learn about gift codes →</a></article><article className="money-card"><span>Refer and earn</span><h3>Invitation and agency system</h3><p>The ShreeWin referral program uses an invitation link or code. The supplied Agency page explains six team levels, team activity and commission records. ShreeWin daily salary or commission is not fixed or guaranteed; check the live rate table.</p><a href="/shree-win-agent">Read the ShreeWin agent guide →</a></article></div></div></section>

    <section className="content-section light" id="support-and-safety"><div className="container editorial-grid"><SectionHeading eyebrow="Trust and support" title="Is ShreeWin Real, Safe and Supported?" copy="Use facts and checks, not only words such as “100% real” or “totally safe”."/><div className="intent-grid"><article><h3>Correct link</h3><p>Our Login and Register buttons use the administrator-supplied ShreeWin official link. ShreeWinAPK.net is still an independent guide, not the ShreeWin Game official website or platform owner.</p></article><article><h3>Secure account access</h3><p>Use a unique password. Keep your OTP, withdrawal password and financial PIN private. We do not collect any ShreeWin login or banking detail.</p></article><article><h3>Customer support</h3><p>The supplied information says the support button is in Settings and describes ShreeWin customer support as 24/7. Response time can vary, so keep your transaction reference ready.</p></article><article><h3>Real-money risk</h3><p>Supported deposit and withdrawal buttons do not guarantee a profit or game result. Real-money gaming can cause loss. Use only money you can afford to lose.</p></article><article><h3>18+ and local rules</h3><p>Only adults aged 18 or above should use the platform. You must also check the rules that apply in your Indian state or location.</p></article><article><h3>No winning promise</h3><p>Ignore “sure-shot trick”, “fixed game”, “100% winning strategy” and “recover your losses” claims. Random outcomes cannot be guaranteed.</p></article></div></div></section>

    <section className="content-section navy" id="screenshots"><div className="container"><SectionHeading eyebrow="App screens" title="ShreeWin Game App Preview" copy="These supplied screenshots show the homepage, account access, registration, Lottery and Activity areas."/><ScreenshotGallery /></div></section>

    <section className="content-section faq-section" id="faq"><div className="container faq-layout"><SectionHeading eyebrow="Simple answers" title="ShreeWin Game FAQ" copy="Short answers for login, registration, APK, games, deposits, withdrawals, invite codes, support and safety."/><FAQAccordion items={faqs}/></div></section>

    <div className="container responsible-wrap"><ResponsibleGamingNotice /></div>

    <section className="final-cta"><div className="container"><img src={siteConfig.logo} width="270" height="90" alt="ShreeWin Game" loading="lazy"/><span>External ShreeWin access</span><h2>Ready to Open ShreeWin?</h2><p>Use the supplied Login or Register button. Check the website address and never share your password, OTP or payment PIN.</p><div><CTAButton kind="register">Register on ShreeWin ↗</CTAButton><CTAButton kind="login">ShreeWin Login ↗</CTAButton></div><small>ShreeWinAPK.net is an independent information website. It does not operate games, accounts, payments or support.</small></div></section>
  </main></PageShell>;
}
