/* eslint-disable @next/next/no-img-element */
import { PageShell } from './components/SiteChrome';
import { ArticleCard, CTAButton, FAQAccordion, FeatureCard, GameCard, Hero, InfoTable, ResponsibleGamingNotice, SafetyNotice, ScreenshotGallery, SectionHeading } from './components/Marketing';
import { siteConfig } from './site-config';

const faqs = [
  ['What information does ShreeWinAPK.net provide?', 'The site explains the Shree Win APK, Android access, phone and email registration, login, password reset, Lobby, Lottery, Popular, Mini Game and Casino categories, TRX WinGo, MotoRace, promotions, withdrawal methods, Activity, Account and the six-level agency system.'],
  ['What is Shree Win?', 'Shree Win is a mobile-focused gaming platform with Lobby, Lottery, Popular, Mini Game and Casino categories, account access, Activity, Promotion and Account areas.'],
  ['What is Shree Win APK?', 'APK is the Android application package format used to install an app outside an app store. Shree Win APK refers to the Android installation file when it is made available by the platform. Always verify the source and file before installing.'],
  ['Does Shree Win have TRX WinGo?', 'Yes. TRX WinGo has been observed in the Lottery section of the current Shree Win interface. Availability and presentation can change, so check the live platform for the latest information.'],
  ['Does Shree Win have MotoRace?', 'Yes. MotoRace has been observed in the Lottery section of the current Shree Win interface. This website explains where it appears without claiming a result or winning method.'],
  ['What categories are available?', 'Lobby, Lottery, Popular, Mini Game and Casino are visible in the current interface. The bottom navigation also includes Home, Activity, Promotion and Account.'],
  ['How can I login?', 'Open the Shree Win access page, enter the credentials attached to your account, verify the information and continue to the account dashboard. ShreeWinAPK.net does not collect usernames, passwords or OTPs.'],
  ['How can I register?', 'Visit the registration page, provide the account information requested by the platform, create your credentials, complete any required verification and then log in after the account has been created.'],
  ['Can Shree Win be used on mobile?', 'The observed Shree Win interface is designed for mobile use and provides a compact category menu, game cards and bottom navigation.'],
  ['Where can I find promotions?', 'The current interface contains a dedicated Promotion section. Read the active platform terms because offers, eligibility and availability may change.'],
  ['What are the Shree Win withdrawal options?', 'According to the current information supplied by the site administrator, UPI and bank-transfer withdrawals start from ₹100, while USDT withdrawals start from ₹1,000. Confirm the amount, destination details, network and current limits inside the platform before submitting.'],
  ['How does Shree Win agent work?', 'The supplied Agency screens describe a six-level invitation structure. An inviter shares the platform invitation link or code, and correctly linked team activity is used in the platform’s agency calculations. Commission eligibility, rates and settlement remain subject to the live agency rules.'],
  ['Is ShreeWinAPK.net the official Shree Win website?', 'ShreeWinAPK.net is an independent informational website created to provide guides and information related to the Shree Win platform. Users should independently verify platform information before using third-party services.'],
] as const;

const features = [
  ['⑧','Lottery Games','Explore the dedicated lottery category and understand where its currently visible entries appear.','/shree-win-lottery'],
  ['◎','TRX WinGo','A featured lottery entry visible inside the current Shree Win Lottery section.','/trx-wingo'],
  ['🏍','MotoRace','A motorcycle-themed game entry shown alongside TRX WinGo in the Lottery section.','/motorace'],
  ['◆','Mini Games','Quick game options organised under a separate category in the main navigation.','/shree-win-games'],
  ['♠','Casino','A casino-style category accessible from the Shree Win homepage category row.','/shree-win-games'],
  ['✦','Promotions','A dedicated section for platform offers and campaigns, subject to current terms.','/shree-win-promotion'],
  ['◫','Activity','An area accessible from the bottom navigation for platform-related activities.','/shree-win-promotion'],
  ['●','Account','The profile and account-options area in the app’s bottom navigation.','/shree-win-login'],
  ['₹','Withdrawals','Understand the supplied UPI, bank transfer and USDT minimum-withdrawal information.','/shree-win-withdrawal'],
  ['♛','Agent Work','Learn how invitation codes, six subordinate levels and agency records are organised.','/shree-win-agent'],
] as const;

const guides = [
  ['Shree Win APK Download Guide','A careful Android installation walkthrough.','/shree-win-download'],
  ['Shree Win Login Guide','Understand account access without sharing credentials.','/shree-win-login'],
  ['Shree Win Registration Guide','Review the registration flow and verification basics.','/shree-win-register'],
  ['Shree Win Games Explained','A factual map of the visible game categories.','/shree-win-games'],
  ['Shree Win TRX WinGo Guide','Learn where TRX WinGo appears in the interface.','/trx-wingo'],
  ['Shree Win MotoRace Guide','Explore the known MotoRace entry and navigation path.','/motorace'],
  ['Shree Win Lottery Guide','Understand the dedicated Lottery category.','/shree-win-lottery'],
  ['Shree Win Promotions Guide','Find the Promotion area and read terms carefully.','/shree-win-promotion'],
  ['Shree Win Withdrawal Guide','UPI, bank transfer and USDT minimums explained.','/shree-win-withdrawal'],
  ['Shree Win Agent Work Guide','Understand invitations, six levels and agency records.','/shree-win-agent'],
  ['Shree Win Account Guide','Account access, password safety and privacy basics.','/shree-win-login'],
  ['Shree Win Mobile App Guide','An overview of the mobile-first Shree Win interface.','/shree-win-apk'],
] as const;

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })),
};

export default function Home() {
  return <PageShell><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <Hero />

    <section className="glance-section container" aria-labelledby="glance-title">
      <div className="glance-heading"><span>Complete overview</span><h2 id="glance-title">Shree Win at a Glance</h2><p>The important app, game, wallet and agency information in one scan.</p></div>
      <dl className="glance-grid"><div><dt>Access</dt><dd>Android APK &amp; Mobile Web</dd></div><div><dt>Account</dt><dd>Phone / Email Login &amp; Register</dd></div><div><dt>Categories</dt><dd>Lobby, Lottery, Popular, Mini Game, Casino</dd></div><div><dt>Lottery entries</dt><dd>TRX WinGo &amp; MotoRace</dd></div><div><dt>UPI / Bank minimum</dt><dd>₹100 withdrawal</dd></div><div><dt>USDT minimum</dt><dd>₹1,000 withdrawal</dd></div><div><dt>Platform areas</dt><dd>Home, Activity, Promotion, Account</dd></div><div><dt>Agency system</dt><dd>Six invitation levels</dd></div></dl>
    </section>

    <nav className="topic-links container" aria-label="Popular Shree Win information">
      <a href="/shree-win-apk">APK overview</a><a href="/shree-win-games">All game categories</a><a href="/shree-win-lottery">Lottery</a><a href="/trx-wingo">TRX WinGo</a><a href="/motorace">MotoRace</a><a href="/shree-win-promotion">Deposit promotions</a><a href="/shree-win-withdrawal">Withdrawal methods</a><a href="/shree-win-agent">Agent work</a><a href="/shree-win-login">Login help</a><a href="/shree-win-register">Registration help</a>
    </nav>

    <section className="content-section light" id="shree-win-apk">
      <div className="container editorial-grid">
        <SectionHeading eyebrow="Start here" title="What is Shree Win APK?" copy="A complete introduction to the app, the games and categories it shows, account access, withdrawals, promotions and agency tools." />
        <div className="long-copy">
          <p><strong>Shree Win is built around a mobile gaming lobby.</strong> The app brings account access, game categories, activity pages, promotions and account controls into a compact interface designed for a phone. “Shree Win APK” is the Android package used to install that mobile experience when the platform makes a verified file available. It is not a separate game and it should never be confused with a modified or cracked download.</p>
          <p>The homepage is easy to understand once you know the structure. <a href="/shree-win-games">Lobby, Lottery, Popular, Mini Game and Casino</a> form the main category row. The supplied Lottery view shows <a href="/trx-wingo">TRX WinGo</a> and <a href="/motorace">MotoRace</a>. The lower navigation keeps Home, Activity, Promotion and Account within reach, while the top area gives new and returning users direct access to <a href="/shree-win-register">registration</a> and <a href="/shree-win-login">login</a>.</p>
          <p>Our coverage goes beyond the lobby. The <a href="/shree-win-promotion">promotion guide</a> explains the supplied first-deposit tiers and the rules users should read before claiming an offer. The <a href="/shree-win-withdrawal">withdrawal guide</a> covers the administrator-supplied minimums: ₹100 through UPI or bank transfer and ₹1,000 through USDT. The <a href="/shree-win-agent">agent-work guide</a> explains invitation links, codes, team relationships, six subordinate levels, commission records and the difference between personal activity and team activity.</p>
          <p>For Android users, our <a href="/shree-win-download">APK download guide</a> covers the complete installation check: confirm the domain, inspect the file, review permissions and keep Android protection enabled. ShreeWinAPK.net does not host an unverified APK and never asks for a Shree Win password, OTP, withdrawal password, UPI PIN or banking PIN.</p>
          <p>Every page is written to answer a real question directly. We clearly separate confirmed interface details from changing operational terms. That means no fake ratings, inflated download totals, invented payout times, guaranteed winning methods or income promises. Use this site to understand how Shree Win is organised, then verify current amounts, eligibility and rules inside the live platform before taking action.</p>
        </div>
      </div>
    </section>

    <section className="content-section navy"><div className="container"><SectionHeading eyebrow="Complete information directory" title="Explore every important Shree Win area" copy="Move directly from the homepage to detailed game, promotion, withdrawal, account and agency guides." centered/><div className="feature-grid">{features.map(([icon,title,copy,href]) => <FeatureCard key={title} icon={icon} title={title} href={href}>{copy}</FeatureCard>)}</div></div></section>

    <section className="content-section app-inside"><div className="container split-layout"><div className="walkthrough-phone"><img src="/preview-home.webp" width="720" height="1732" alt="Shree Win mobile app homepage with navigation and game categories" loading="lazy" /></div><div><SectionHeading eyebrow="App walkthrough" title="Inside the Shree Win App" copy="The mobile homepage is a working map: account actions at the top, categories in the centre and activity, promotion and account controls at the bottom."/><div className="walkthrough-list"><article><b>01</b><div><h3>Login, registration and recovery</h3><p>Shree Win supports phone and email account views. The supplied screens also show a phone-based password-reset flow with a verification code. Read our <a href="/shree-win-login">login</a> and <a href="/shree-win-register">registration</a> guides before entering information on the external platform.</p></div></article><article><b>02</b><div><h3>Lobby and five category tabs</h3><p>Lobby is the broad starting point. Lottery, Popular, Mini Game and Casino let users move into a specific type of content without searching through the full homepage.</p></div></article><article><b>03</b><div><h3>TRX WinGo and MotoRace</h3><p>The supplied Lottery screen clearly shows <a href="/trx-wingo">TRX WinGo</a> and <a href="/motorace">MotoRace</a>. Our individual pages explain where they appear and which live rules should be checked.</p></div></article><article><b>04</b><div><h3>Activity and Promotion</h3><p>The Activity screen includes reward-related areas, while Promotion is the route for campaigns and agency information. The <a href="/shree-win-promotion">promotion guide</a> separates offer amounts from the conditions attached to them.</p></div></article><article><b>05</b><div><h3>Account, withdrawal and agent records</h3><p>Account is the route for profile and wallet-related controls. Our <a href="/shree-win-withdrawal">withdrawal</a> and <a href="/shree-win-agent">agent-work</a> pages explain the supplied minimums and agency structure in plain language.</p></div></article></div></div></div></section>

    <section className="content-section light" id="games"><div className="container"><SectionHeading eyebrow="Known game entries" title="Games Available on Shree Win" copy="The supplied interface confirms TRX WinGo and MotoRace, along with broader Lottery, Mini Game and Casino categories."/><div className="games-grid"><GameCard label="Lottery" title="TRX WinGo" copy="A dedicated entry currently visible in the Lottery section. The guide explains its placement and safe research approach without offering predictions." href="/trx-wingo" icon="◎"/><GameCard label="Lottery" title="MotoRace" copy="A motorcycle-themed entry shown in the same Lottery area. Availability and rules should be verified inside the current platform." href="/motorace" icon="🏍"/><GameCard label="Category" title="Lottery" copy="A dedicated category that currently contains the two confirmed entries above." href="/shree-win-lottery" icon="⑧"/><GameCard label="Categories" title="Mini Games" copy="Quick gaming options are organised under Mini Game, while Casino appears as its own category." href="/shree-win-games" icon="◆"/></div></div></section>

    <section className="highlight-band trx"><div className="container highlight-grid"><div><span>Featured entry</span><h2>TRX WinGo in the Lottery section</h2><p>TRX WinGo is currently visible as one of the featured entries in Shree Win’s Lottery category. Our dedicated page explains how to locate the category, what information to review before opening a game and why no third-party prediction can guarantee an outcome.</p><a className="button button-gold" href="/trx-wingo">Learn About TRX WinGo</a></div><div className="highlight-art" aria-hidden="true"><span>TRX</span><b>WinGo</b><i>◎</i></div></div></section>

    <section className="highlight-band moto"><div className="container highlight-grid reverse"><div className="highlight-art" aria-hidden="true"><span>SHREE WIN</span><b>MotoRace</b><i>🏍</i></div><div><span>Featured entry</span><h2>MotoRace in the Lottery section</h2><p>MotoRace is the other currently confirmed entry in the supplied Lottery interface. The name and motorcycle artwork identify the listing, but the visible information does not establish game mechanics, payout values or winning methods. Check the live rules before participating.</p><a className="button button-outline" href="/motorace">Learn About MotoRace</a></div></div></section>

    <section className="content-section navy" id="download"><div className="container download-grid"><div><SectionHeading eyebrow="Android installation" title="Shree Win APK Download Guide" copy="A cautious, generic process for reviewing and installing an Android APK when the platform provides one."/><ol className="numbered-steps"><li><b>1</b><div><h3>Access the download source</h3><p>Start only from a domain you intended to visit. Check spelling before selecting a file.</p></div></li><li><b>2</b><div><h3>Download the APK if provided</h3><p>This website does not host a file. Use the platform source only when an APK is actually offered.</p></div></li><li><b>3</b><div><h3>Review Android’s installation request</h3><p>Android may ask for permission to install from the browser or file manager. Read the warning instead of dismissing it automatically.</p></div></li><li><b>4</b><div><h3>Inspect the file and permissions</h3><p>Confirm the expected name and review the permissions requested during installation.</p></div></li><li><b>5</b><div><h3>Complete installation carefully</h3><p>Keep device security features enabled and remove an unexpected or modified file.</p></div></li><li><b>6</b><div><h3>Open the app and login</h3><p>Use your credentials only inside the intended platform. Never send a password or OTP to another person.</p></div></li></ol><CTAButton kind="login" className="button-wide">Visit Shree Win ↗</CTAButton></div><SafetyNotice><ul><li>Download only from a source you trust.</li><li>Check the domain before downloading.</li><li>Avoid modified or cracked APK files.</li><li>Review permissions before installation.</li><li>Keep Android security features enabled.</li><li>Do not share passwords or OTPs.</li></ul><p>APK version and file size are intentionally left unspecified until they are verified by the administrator.</p></SafetyNotice></div></section>

    <section className="content-section light" id="login"><div className="container guide-split"><div><SectionHeading eyebrow="Account access" title="How to Login to Shree Win" copy="Use the platform’s account page. ShreeWinAPK.net never asks you to type a username, password, OTP or financial PIN."/><ol className="clean-steps"><li><span>01</span><p>Open the Shree Win login page.</p></li><li><span>02</span><p>Enter the credentials connected to your account.</p></li><li><span>03</span><p>Verify the information before continuing.</p></li><li><span>04</span><p>Continue to the account dashboard.</p></li></ol><CTAButton kind="login">Shree Win Login ↗</CTAButton><a className="inline-link" href="/shree-win-login">Read the complete login guide →</a></div><figure className="guide-image"><img src="/preview-login.webp" width="720" height="1240" alt="Shree Win login interface with phone number and email tabs" loading="lazy"/><figcaption>Observed login interface. Credentials are entered only on the external platform.</figcaption></figure></div></section>

    <section className="content-section soft" id="register"><div className="container guide-split reverse"><figure className="guide-image"><img src="/preview-register-phone.webp" width="720" height="1378" alt="Shree Win phone registration interface" loading="lazy"/><figcaption>Observed phone registration interface. Required fields can change.</figcaption></figure><div><SectionHeading eyebrow="New account" title="How to Register on Shree Win" copy="Review the platform’s requirements, protect your information and never rely on an unverified bonus claim."/><ol className="clean-steps"><li><span>01</span><p>Visit the Shree Win registration page.</p></li><li><span>02</span><p>Enter the account information requested by the platform.</p></li><li><span>03</span><p>Set account credentials that you do not reuse elsewhere.</p></li><li><span>04</span><p>Complete any verification required by the platform.</p></li><li><span>05</span><p>Login after successful registration.</p></li></ol><CTAButton kind="register">Register on Shree Win ↗</CTAButton><a className="inline-link" href="/shree-win-register">Read the complete registration guide →</a></div></div></section>

    <section className="content-section finance-section" id="payments-and-agent"><div className="container"><SectionHeading eyebrow="Wallet, offers & agency" title="Deposit, Withdrawal and Agent Information" copy="The supplied platform material covers all three areas. These summaries give you the useful numbers and the correct page for the complete rules."/><div className="money-grid">
      <article className="money-card"><span>Promotion</span><h3>First-deposit tiers shown in the supplied interface</h3><div className="tier-list">{siteConfig.firstDepositTiers.map(tier => <div key={tier.depositInr}><b>Deposit ₹{tier.depositInr.toLocaleString('en-IN')}</b><strong>Bonus ₹{tier.bonusInr.toLocaleString('en-IN')}</strong></div>)}</div><p>Each account can receive the first-deposit activity once according to the supplied rule screen. Eligibility, claim method and turnover conditions must be checked in the current platform.</p><a href="/shree-win-promotion">Read promotion rules →</a></article>
      <article className="money-card featured"><span>Withdrawals</span><h3>UPI, bank transfer and USDT</h3><div className="withdraw-numbers"><div><strong>₹100</strong><small>UPI minimum</small></div><div><strong>₹100</strong><small>Bank-transfer minimum</small></div><div><strong>₹1,000</strong><small>USDT minimum</small></div></div><p>These minimums come from the information supplied by the site administrator. Before submitting, confirm the live minimum, destination details, USDT network and any account conditions.</p><a href="/shree-win-withdrawal">Open withdrawal guide →</a></article>
      <article className="money-card"><span>Agency</span><h3>How Shree Win agent work is organised</h3><ul><li>Share the invitation link or invitation code shown in the platform.</li><li>A correctly linked invitee becomes part of the inviter’s team structure.</li><li>The supplied Agency page explains six subordinate levels.</li><li>Team number, team activity and deposit-related records are used in agency calculations.</li><li>Rates and settlement must be read from the live agency page.</li></ul><a href="/shree-win-agent">Understand agent work →</a></article>
    </div></div></section>

    <section className="content-section navy" id="screenshots"><div className="container"><SectionHeading eyebrow="Observed interface" title="Shree Win App Preview" copy="Compressed WebP previews from the currently supplied mobile interface. Labels describe only what is visible in each screen."/><ScreenshotGallery /></div></section>

    <section className="content-section light"><div className="container overview-grid"><div><SectionHeading eyebrow="Feature check" title="Shree Win Platform Overview" copy="Checkmarks indicate areas observed in the current interface; they are not quality ratings or guarantees."/><p className="muted-copy">The table is deliberately simple. It does not assign a score, claim official verification or compare Shree Win with another platform. If a feature moves or disappears in a later release, the live interface should be treated as current.</p></div><InfoTable /></div></section>

    <section className="content-section intent-section"><div className="container editorial-grid"><SectionHeading eyebrow="Find the exact answer" title="Why Users Search for Shree Win APK" copy="A Shree Win search is rarely about only one download. Visitors also need account, game, promotion, withdrawal and agency information before they continue."/><div className="intent-grid"><article><h3>Finding the Android app</h3><p>The <a href="/shree-win-download">download guide</a> explains how to check a source, review an APK and install it without turning off essential Android protection.</p></article><article><h3>Understanding the mobile lobby</h3><p>The <a href="/shree-win-apk">APK overview</a> maps the interface from the category row to the Home, Activity, Promotion and Account navigation.</p></article><article><h3>Registering by phone or email</h3><p>The <a href="/shree-win-register">registration guide</a> explains both supplied account views, password confirmation, invitation-code placement and privacy checks.</p></article><article><h3>Logging in or resetting a password</h3><p>The <a href="/shree-win-login">login guide</a> covers phone and email access, remember-password controls and the verification-code recovery flow.</p></article><article><h3>Comparing game categories</h3><p>The <a href="/shree-win-games">games directory</a> explains Lobby, Lottery, Popular, Mini Game and Casino without mixing category labels with guarantees.</p></article><article><h3>Finding TRX WinGo and MotoRace</h3><p><a href="/trx-wingo">TRX WinGo</a> and <a href="/motorace">MotoRace</a> both appear in Lottery. Their pages show the direct navigation path and the live details to review.</p></article><article><h3>Checking offers and activity rules</h3><p>The <a href="/shree-win-promotion">promotion guide</a> records the supplied first-deposit tiers and explains one-time eligibility and turnover wording.</p></article><article><h3>Checking withdrawal minimums</h3><p>The <a href="/shree-win-withdrawal">withdrawal guide</a> covers the supplied ₹100 UPI/bank minimum and ₹1,000 USDT minimum, plus destination and network checks.</p></article><article><h3>Learning how agent work is structured</h3><p>The <a href="/shree-win-agent">agent guide</a> explains invitation links, codes, six team levels, activity records and commission-rule checks.</p></article></div></div></section>

    <section className="content-section light"><div className="container"><SectionHeading eyebrow="Content hub" title="Latest Shree Win Guides" copy="A scalable guide library covering app access, visible games, account journeys and safety."/><div className="article-grid">{guides.map(([title,copy,href], index) => <ArticleCard key={title} title={title} copy={copy} href={href} number={index + 1}/>)}</div></div></section>

    <section className="content-section faq-section" id="faq"><div className="container faq-layout"><SectionHeading eyebrow="Clear answers" title="Shree Win APK FAQ" copy="Answers are limited to supplied or directly observed platform information. Operational details should be verified on the live platform."/><FAQAccordion items={faqs}/></div></section>

    <div className="container responsible-wrap"><ResponsibleGamingNotice /></div>

    <section className="final-cta"><div className="container"><img src={siteConfig.logo} width="270" height="90" alt="Shree Win" loading="lazy"/><span>External platform access</span><h2>Explore Shree Win</h2><p>You now have the app, games, account, promotion, withdrawal and agency information needed to review the platform with confidence.</p><div><CTAButton kind="register">Register ↗</CTAButton><CTAButton kind="login">Login ↗</CTAButton></div><small>ShreeWinAPK.net is an independent information website and does not collect platform credentials.</small></div></section>
  </main></PageShell>;
}
