import type { Metadata } from 'next';
import { PageShell } from '../components/SiteChrome';
import { FaqBlock, InfoHero } from '../components/InfoBlocks';
import { RegisterExperience } from '../components/AccountExperience';
export const metadata:Metadata={title:'Shree Win Register | Create a Shree Win Game Account',description:'Create a Shree Win account with an active mobile number, complete verification, set a strong password and review eligibility and account terms.',alternates:{canonical:'/register'}};
const faqs:[string,string][]=[
 ['What do I need to register for Shree Win?','Use an active mobile number you control, create a strong unique password and complete the verification requested on the registration screen.'],
 ['Is an invitation code required?','Use an invitation code only when the live registration screen provides the field and the applicable terms allow it. Confirm the code before submission.'],
 ['Can I create more than one account?','Follow the current account terms. Duplicate accounts can affect verification, activity eligibility and account access.'],
 ['Who can register?','Shree Win is intended only for adults who meet the age and location requirements shown in the applicable terms.'],
 ['Is registration free?','Any current registration cost or requirement must be displayed before submission. Do not rely on third-party claims.'],
];
export default function RegisterPage(){return <PageShell active="account"><main><InfoHero eyebrow="SHREE WIN REGISTER" title="Create your account" accent="with the right details." copy="Register with a mobile number you control, secure the account with a strong password and review the current eligibility terms." current="Register" icon="✦" primary={{label:'Open registration',href:'#details'}}/>
 <section className="content-section account-experience-section" id="details"><RegisterExperience/><div className="account-copy"><span className="kicker dark"><i/>CREATE YOUR ACCOUNT</span><h2>Registration fields that stay clear on every screen.</h2><p>The Shree Win form keeps mobile number, password confirmation, optional invite code and privacy acceptance together in one focused journey.</p><ol><li><b>01</b><p><strong>Use your own mobile number</strong>It should be active and able to receive verification.</p></li><li><b>02</b><p><strong>Create a unique password</strong>Do not reuse a banking, email or social-media password.</p></li><li><b>03</b><p><strong>Check the invite code</strong>Use it only when you recognise the inviter and understand the promotion terms.</p></li><li><b>04</b><p><strong>Accept after reading</strong>Review eligibility, account terms and the Privacy Notice before submission.</p></li></ol><div className="product-notice"><b>Registration connection</b><p>The form is ready for the verified Shree Win account service. No registration data is transmitted until that connection is supplied.</p></div></div></section>
 <section className="dark-info-section"><div><span>INVITATION CODE</span><h2>Use a code only when you recognise the inviter.</h2><p>An invitation code can connect the new account to a promotion relationship. Check the value before submission because it may not be editable later.</p></div><ol><li><b>01</b><span><strong>Receive the code</strong>Use the personal link or code supplied by the inviter.</span></li><li><b>02</b><span><strong>Check the field</strong>Confirm the registration page shows the code accurately.</span></li><li><b>03</b><span><strong>Read promotion terms</strong>Invitation benefits are subject to current eligibility.</span></li></ol></section>
 <FaqBlock title="Shree Win registration FAQ" items={faqs}/><section className="page-cta purple"><span>ALREADY REGISTERED?</span><h2>Return to your Shree Win account.</h2><a className="primary-button" href="/login">Go to Login →</a></section></main></PageShell>}
