import type { Metadata } from 'next';
import { PageShell } from '../components/SiteChrome';
import { FaqBlock, InfoHero, ProductNotice } from '../components/InfoBlocks';
export const metadata:Metadata={title:'Shree Win Register | Create a Shree Win Game Account',description:'Create a Shree Win account with an active mobile number, complete verification, set a strong password and review eligibility and account terms.',alternates:{canonical:'/register'}};
const faqs:[string,string][]=[
 ['What do I need to register for Shree Win?','Use an active mobile number you control, create a strong unique password and complete the verification requested on the registration screen.'],
 ['Is an invitation code required?','Use an invitation code only when the live registration screen provides the field and the applicable terms allow it. Confirm the code before submission.'],
 ['Can I create more than one account?','Follow the current account terms. Duplicate accounts can affect verification, activity eligibility and account access.'],
 ['Who can register?','Shree Win is intended only for adults who meet the age and location requirements shown in the applicable terms.'],
 ['Is registration free?','Any current registration cost or requirement must be displayed before submission. Do not rely on third-party claims.'],
];
export default function RegisterPage(){return <PageShell active="account"><main><InfoHero eyebrow="SHREE WIN REGISTER" title="Create your account" accent="with the right details." copy="Register with a mobile number you control, secure the account with a strong password and review the current eligibility terms." current="Register" icon="✦" primary={{label:'See registration steps',href:'#details'}}/>
 <section className="content-section info-page" id="details"><div className="section-title centered"><span>CREATE YOUR ACCOUNT</span><h2>Four clear registration steps.</h2><p>Complete every field only on the verified Shree Win registration screen.</p></div><div className="start-grid"><article><i>01</i><span>📱</span><h3>Enter mobile number</h3><p>Use an active number that belongs to you and can receive verification.</p></article><article><i>02</i><span>🔑</span><h3>Create a password</h3><p>Use a unique password that is not used on another website.</p></article><article><i>03</i><span>✓</span><h3>Verify the account</h3><p>Complete the OTP or other check shown. Keep verification codes private.</p></article><article><i>04</i><span>📜</span><h3>Review the terms</h3><p>Confirm age, location, account and product conditions before registering.</p></article></div><ProductNotice>The visual site is ready, but registration data will not be collected until a verified Shree Win account service is connected.</ProductNotice></section>
 <section className="dark-info-section"><div><span>INVITATION CODE</span><h2>Use a code only when you recognise the inviter.</h2><p>An invitation code can connect the new account to a promotion relationship. Check the value before submission because it may not be editable later.</p></div><ol><li><b>01</b><span><strong>Receive the code</strong>Use the personal link or code supplied by the inviter.</span></li><li><b>02</b><span><strong>Check the field</strong>Confirm the registration page shows the code accurately.</span></li><li><b>03</b><span><strong>Read promotion terms</strong>Invitation benefits are subject to current eligibility.</span></li></ol></section>
 <FaqBlock title="Shree Win registration FAQ" items={faqs}/><section className="page-cta purple"><span>ALREADY REGISTERED?</span><h2>Return to your Shree Win account.</h2><a className="primary-button" href="/login">Go to Login →</a></section></main></PageShell>}
