import type { Metadata } from 'next';
import { PageShell } from '../components/SiteChrome';
import { FaqBlock, InfoHero, ProductNotice } from '../components/InfoBlocks';
export const metadata:Metadata={title:'Shree Win Login | Access Your Shree Win Game Account',description:'Open Shree Win Login, use your registered mobile number and password, recover account access safely and protect your OTP and account details.',alternates:{canonical:'/login'}};
const faqs:[string,string][]=[
 ['How do I log in to Shree Win?','Open the Login area, enter the mobile number connected to your account and your password, then complete any verification shown.'],
 ['I forgot my password—what should I do?','Use Forgot Password on the live login screen and complete recovery with the registered mobile number. Never use recovery links from unknown messages.'],
 ['Why did my login fail?','Check the mobile number format, password and network connection. Repeated attempts may trigger a temporary security check.'],
 ['Can I share my Shree Win account?','No. Keep your account, password and verification codes private and follow the active account terms.'],
 ['Does support need my OTP?','No. Never share an OTP, password, PIN or full payment credentials with anyone.'],
];
export default function LoginPage(){return <PageShell active="account"><main><InfoHero eyebrow="SHREE WIN LOGIN" title="Welcome back to" accent="your Shree Win account." copy="Use the mobile number and password connected to your account, then complete any security check shown by the live product." current="Login" icon="🔐" primary={{label:'Login information',href:'#details'}}/>
 <section className="content-section account-layout" id="details"><div className="account-panel"><span>ACCOUNT ACCESS</span><h2>Shree Win Login</h2><p>The live login module is connected through the Shree Win account system. This website does not collect credentials until that verified connection is configured.</p><div className="field-preview"><label>Registered mobile number</label><div>Enter on the live login screen</div></div><div className="field-preview"><label>Password</label><div>Keep your password private</div></div><a className="primary-button" href="/support">Account access support →</a><small>Never send your password or OTP through chat.</small></div><div className="account-copy"><span className="kicker dark"><i/>SIGN IN SAFELY</span><h2>Three checks before login.</h2><ol><li><b>01</b><p><strong>Confirm the domain</strong>Use the Shree Win address you trust, not a link from an unknown message.</p></li><li><b>02</b><p><strong>Use your registered details</strong>Enter the same mobile number used during registration.</p></li><li><b>03</b><p><strong>Protect verification</strong>Never disclose your password, OTP or screen to another person.</p></li></ol><ProductNotice>Account access will be enabled here only after the verified Shree Win authentication service is connected.</ProductNotice></div></section>
 <FaqBlock title="Shree Win Login FAQ" items={faqs}/><section className="page-cta"><span>NEW TO SHREE WIN?</span><h2>Create an account and explore the game lobby.</h2><a className="primary-button" href="/register">Open registration →</a></section></main></PageShell>}
