import type { Metadata } from 'next';
import { PageShell } from '../components/SiteChrome';
import { FaqBlock, InfoHero, ProductNotice } from '../components/InfoBlocks';
export const metadata:Metadata={title:'Shree Win Support | Account, Payment & Game Help',description:'Get Shree Win support preparation for login, account verification, deposits, withdrawals, gift codes, promotions and game-result questions.',alternates:{canonical:'/support'}};
const faqs:[string,string][]=[
 ['How do I contact Shree Win Support?','Use the customer-service or Support entry displayed inside the live Shree Win account. A verified email or chat link can be added here when supplied.'],
 ['What information should I include?','Provide your account ID, the affected feature, date and time, transaction or round ID, and a clear screenshot. Never include a password or OTP.'],
 ['How do I report a payment issue?','Keep the payment receipt and transaction reference, note the current wallet status and avoid submitting the same payment repeatedly.'],
 ['How do I report a game-result question?','Include the game name, room, round or period number and the result shown in your history.'],
 ['Can support guarantee a promotion reward?','Support can review eligibility and records, but active promotion terms determine qualification and calculation.'],
];
export default function SupportPage(){return <PageShell><main><InfoHero eyebrow="SHREE WIN SUPPORT" title="Get the right details" accent="to the right support channel." copy="Prepare account, transaction, game or promotion information before contacting Shree Win customer service." current="Support" icon="?" primary={{label:'Prepare a request',href:'#details'}}/>
 <section className="content-section info-page" id="details"><div className="section-title"><span>SUPPORT TOPICS</span><h2>Choose the issue you need to resolve.</h2></div><div className="info-card-grid three"><article><i>🔐</i><h2>Login & account</h2><p>Account access, password recovery, mobile-number or verification questions.</p></article><article><i>₹</i><h2>Wallet & payment</h2><p>Deposit status, bank details, withdrawal requests and transaction records.</p></article><article><i>🎮</i><h2>Game & result</h2><p>Game room, period number, history, displayed result and settlement record.</p></article><article><i>🎁</i><h2>Activity & gift code</h2><p>Campaign eligibility, gift-code validation, attendance and reward status.</p></article><article><i>👥</i><h2>Promotion & agency</h2><p>Invitation relationships, team records, agency levels and calculations.</p></article><article><i>↓</i><h2>App & installation</h2><p>Version checks, APK installation, update and compatibility questions.</p></article></div></section>
 <section className="content-section process-section"><div className="section-title"><span>SUPPORT REQUEST CHECKLIST</span><h2>Include enough information for a useful review.</h2></div><div className="check-grid"><p><b>01</b>Account ID or masked registered mobile number.</p><p><b>02</b>Exact feature, game or activity name.</p><p><b>03</b>Date, time and device used.</p><p><b>04</b>Transaction, order, round or period ID.</p><p><b>05</b>Clear screenshot without exposed credentials.</p><p><b>06</b>Short description of the expected and actual result.</p></div><ProductNotice>A verified Shree Win support email, phone number or chat URL has not been supplied, so this page does not invent one. Use the support entry inside the live product.</ProductNotice></section>
 <FaqBlock title="Shree Win Support FAQ" items={faqs}/><section className="page-cta purple"><span>ACCOUNT SAFETY</span><h2>Never share a password, OTP or payment PIN with support.</h2><a className="primary-button" href="/responsible-play">Read safety guidance →</a></section></main></PageShell>}
